namespace RELYR;

using System.Collections.Concurrent;
using System.IO;

public static class EngineIntegrationTest
{
    public static async Task<int> RunAsync(TextWriter output, bool includeRealHook = true)
    {
        var events = new List<string>();
        var detected = new List<string>();
        var inputStarts = new List<string>();
        var inputEnds = new List<string>();
        var layerStarts = new List<string>();
        var layerEnds = new List<string>();
        var report = new VerificationReport(output);
        bool rightWheelLayer = false, allWheelLayers = false, transientMiddleMapped = false, transientKeyMapped = false, spaceMappings = true, multiLayerMappings = false, plainMouseMappings = true, legacyMouseDrag = false, taskbarQualify = false, taskbarRightMapped = false, gestureMode = false, filmoraHomeGestureMode = false, rightSpaceGestureMode = false, normalRightGestureMode = false;
        Action<bool, string> Check = report.Check;
        using var engine = new InputEngine
        {
            ExitOnEmergency = false,
            QualifyInput = input => taskbarQualify ? "Taskbar+" + input : input,
            HasMapping = input => input == "A" || (gestureMode && input == "G") || (filmoraHomeGestureMode && input == "Home") || (rightSpaceGestureMode && (input is "MouseRight+*" or "MouseRight+Space")) || (normalRightGestureMode && (input is "MouseRight" or "MouseRight+*")) || (taskbarRightMapped && input == "Taskbar+MouseRight") || (input is "Taskbar+E" or "Taskbar+Delete") || (spaceMappings && (input == "Space" || input == "Space+J" || input == "Space+K" || input == "Space+U" || input == "Space+MouseLeft" || input == "Space+*")) || input == "K" || input == "Esc" || (plainMouseMappings && (input == "MouseLeft" || input == "MouseRight")) || input == "CapsLock+J" || input == "CapsLock+U" || input == "CapsLock+*" || (transientKeyMapped && input == "B") || (transientMiddleMapped && input == "MouseMiddle") || (rightWheelLayer && (input == "MouseRight+*" || input == "MouseRight+WheelUp" || input == "MouseRight+WheelDown")) || (allWheelLayers && (input is "MouseRight+*" or "MouseRight+WheelUp" or "MouseRight+WheelDown" or "MouseBack+*" or "MouseBack+WheelUp" or "MouseBack+WheelDown" or "MouseForward+*" or "MouseForward+WheelUp" or "MouseForward+WheelDown")) || (multiLayerMappings && (input is "MouseLeft+*" or "MouseLeft+J" or "MouseMiddle+*" or "MouseMiddle+J" or "MouseBack+*" or "MouseBack+J" or "MouseForward+*" or "MouseForward+J" or "MouseForward+Up" or "MouseForward+MouseLeft" or "MouseForward+MouseRight")),
            SuppressLayerTap = key => key == "CapsLock",
            HasLongPress = input => input == "K" || input == "Esc" || input == "MouseRight" || input == "Taskbar+Delete" || (taskbarRightMapped && input == "Taskbar+MouseRight"),
            IsGesturePress = input => (gestureMode && input == "G") || (filmoraHomeGestureMode && input == "Home") || (rightSpaceGestureMode && input == "MouseRight+Space") || (normalRightGestureMode && input == "MouseRight"),
            LongPressDuration = _ => 100,
            InputReceived = input => { lock (events) events.Add(input); return !input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase); }
        };
        engine.InputStarted = input => inputStarts.Add(input);
        engine.InputEnded = input => inputEnds.Add(input);
        engine.LayerStarted = input => layerStarts.Add(input);
        engine.LayerEnded = input => layerEnds.Add(input);
        engine.HasLegacyMouseDrag = input => legacyMouseDrag && input == "MouseLeft";
        int repeatCount = 0;
        engine.SpaceHoldRepeatDelayMs = 120;
        engine.SpaceHoldRepeatIntervalMs = 40;
        engine.RepeatOutputForTest = () => Interlocked.Increment(ref repeatCount);
        engine.DragPixels = 50;
        engine.EnableDirectTestInput();
        engine.Detected += x => detected.Add(x);
        try
        {
            var forwarded = (IntPtr)0x1234;
            engine.NextHookForTest = (_, _, _) => forwarded;
            Check(engine.DirectMarkedKeyForTest(0x41, false) == forwarded && engine.DirectMarkedMouseForTest(0x201) == forwarded, "app-generated keyboard and mouse input is forwarded to Windows");
            engine.NextHookForTest = null;
            int pointerMoves = 0;
            engine.PointerMoved += () => pointerMoves++;
            engine.DirectMouseForTest(0x200, 0, 10, 20);
            engine.DirectMarkedMouseForTest(0x200);
            Check(pointerMoves == 1, "one physical pointer move requests one profile check while app-generated movement is ignored");
            plainMouseMappings = false;
            engine.NextHookForTest = (_, _, _) => forwarded;
            int capturedX = -1, capturedY = -1;
            bool captureStarted = InputEngine.BeginCoordinateCapture((x, y) => (capturedX, capturedY) = (x, y));
            int eventsBeforeCapture = events.Count, detectedBeforeCapture = detected.Count;
            var capturedDown = engine.DirectMouseForTest(0x201, 0, 321, 654);
            var capturedUp = engine.DirectMouseForTest(0x202, 0, 321, 654);
            Check(captureStarted && capturedDown == (IntPtr)1 && capturedUp == (IntPtr)1 && capturedX == 321 && capturedY == 654 && events.Count == eventsBeforeCapture && detected.Count == detectedBeforeCapture && !InputEngine.CoordinateCapturePendingForTest, "coordinate capture swallows one complete left click and returns only its screen position");
            Action<int, int> cancelledCapture = (_, _) => throw new InvalidOperationException("cancelled coordinate capture ran");
            Check(InputEngine.BeginCoordinateCapture(cancelledCapture), "coordinate capture can be armed again after a complete click");
            InputEngine.CancelCoordinateCapture(cancelledCapture);
            var passedDown = engine.DirectMouseForTest(0x201, 0, 100, 200);
            var passedUp = engine.DirectMouseForTest(0x202, 0, 100, 200);
            Check(passedDown == forwarded && passedUp == forwarded && !InputEngine.CoordinateCapturePendingForTest, "cancelled coordinate capture leaves the next physical click untouched");
            engine.NextHookForTest = null;
            plainMouseMappings = true;
            InputEngine.InjectKeyForTest("A", false);
            InputEngine.InjectKeyForTest("A", true);
            await Task.Delay(50);
            Check(events.Contains("A"), "keyboard hook single press");
            events.Clear();
            engine.ResetStateForTest();
            engine.ShouldInterceptInput = () => throw new InvalidOperationException("simulated hook consumer fault");
            var recoveredFaultEvent = engine.DirectKeyForTest(0x41, false);
            engine.ShouldInterceptInput = null;
            engine.DirectKeyForTest(0x41, false);
            engine.DirectKeyForTest(0x41, true);
            await Task.Delay(40);
            Check(recoveredFaultEvent == IntPtr.Zero && events.Contains("A") && !engine.HasCapturedStateForTest(), "a hook callback fault clears captured state and the next mapped input still executes");
            gestureMode = true;
            engine.GestureCursorForTest = (100, 100);
            engine.GestureThresholdPixels = 10;
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectKeyForTest(0x47, false);
            engine.DirectKeyForTest(0x47, true);
            await Task.Delay(40);
            Check(events.SequenceEqual(["G:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "short-press gesture starts immediately and a click without movement executes its center action once");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectKeyForTest(0x47, false);
            var swallowedGestureMove = engine.DirectMouseForTest(0x200, 0, 112, 103);
            engine.DirectMouseForTest(0x200, 0, 140, 100);
            engine.DirectKeyForTest(0x47, true);
            await Task.Delay(40);
            Check(swallowedGestureMove == (IntPtr)1 && events.Count(x => x == "G:Gesture:Right") == 1 && !events.Any(x => x.EndsWith(":Center")) && !engine.HasCapturedStateForTest(), "gesture movement is swallowed and one continuous movement executes the same direction only once");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectKeyForTest(0x47, false);
            engine.DirectMouseForTest(0x200, 0, 114, 100);
            await Task.Delay(140);
            bool directGestureResynchronized = engine.TryPrepareForProfileChange(_ => false);
            engine.DirectKeyForTest(0x47, false);
            engine.DirectKeyForTest(0x47, true);
            engine.DirectKeyForTest(0x47, false);
            engine.DirectKeyForTest(0x47, true);
            await Task.Delay(40);
            Check(directGestureResynchronized && events.SequenceEqual(["G:Gesture:Right", "G:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "a committed direction survives state resynchronization and repeated down without firing center, while the next physical press restores center");
            events.Clear();
            engine.ResetStateForTest();
            var forwardedAfterSafety = (IntPtr)0x7788;
            engine.NextHookForTest = (_, _, _) => forwardedAfterSafety;
            engine.DirectKeyForTest(0x47, false);
            engine.ExpireGestureForTest();
            var moveAfterSafety = engine.DirectMouseForTest(0x200, 0, 130, 100);
            engine.DirectKeyForTest(0x47, true);
            await Task.Delay(40);
            bool safetyStateClean = !engine.HasCapturedStateForTest();
            Check(moveAfterSafety == forwardedAfterSafety && events.Count == 0 && safetyStateClean, $"gesture safety release restores normal pointer events and adds no delayed center action (move={moveAfterSafety}, events={string.Join(",", events)}, clean={safetyStateClean})");
            engine.NextHookForTest = null;
            Check(InputEngine.TryGetGestureDirection(0, -11, 10, out var gestureUp) && gestureUp == "Up" && InputEngine.TryGetGestureDirection(0, 11, 10, out var gestureDown) && gestureDown == "Down" && InputEngine.TryGetGestureDirection(-11, 0, 10, out var gestureLeft) && gestureLeft == "Left" && InputEngine.TryGetGestureDirection(11, 0, 10, out var gestureRight) && gestureRight == "Right" && !InputEngine.TryGetGestureDirection(9, 9, 10, out _), "gesture direction signs match Windows coordinates and movement below the threshold stays undecided");
            Check(InputEngine.TryGetGestureDirection(24, 14, 10, out var diagonalRight) && diagonalRight == "Right" && InputEngine.TryGetGestureDirection(-24, 14, 10, out var diagonalLeft) && diagonalLeft == "Left" && InputEngine.TryGetGestureDirection(15, -24, 10, out var diagonalUp) && diagonalUp == "Up" && InputEngine.TryGetGestureDirection(15, 24, 10, out var diagonalDown) && diagonalDown == "Down", "imperfect diagonal mouse movement still resolves to one of the four intended directions");
            Check(InputEngine.TryGetGestureDirection(12, -18, 10, out var xAreaUp) && xAreaUp == "Up" && InputEngine.TryGetGestureDirection(-12, 18, 10, out var xAreaDown) && xAreaDown == "Down" && InputEngine.TryGetGestureDirection(-18, 12, 10, out var xAreaLeft) && xAreaLeft == "Left" && InputEngine.TryGetGestureDirection(18, -12, 10, out var xAreaRight) && xAreaRight == "Right", "two 45-degree diagonal boundaries divide gesture movement into four equal X-shaped direction areas");
            gestureMode = false;
            rightSpaceGestureMode = true;
            events.Clear();
            engine.ResetStateForTest();
            bool gestureCycleClean = true;
            for (int i = 0; i < 100; i++)
            {
                engine.DirectMouseForTest(0x204, 0, 100, 100);
                engine.DirectKeyForTest(0x20, false);
                engine.DirectMouseForTest(0x200, 0, 112, 100);
                engine.DirectKeyForTest(0x20, true);
                engine.DirectMouseForTest(0x205, 0, 100, 100);
                if (engine.HasCapturedStateForTest())
                {
                    gestureCycleClean = false;
                    break;
                }
            }
            Check(gestureCycleClean && events.Count(x => x == "MouseRight+Space:Gesture:Right") == 100 && !events.Any(x => x.EndsWith(":Center")), "right-click layer plus Space gesture repeats 100 times without stale layer, key, mouse, or gesture state");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            engine.DirectMouseForTest(0x200, 0, 114, 100);
            await Task.Delay(140);
            bool layeredGesturePreserved = engine.TryPrepareForProfileChange(_ => false), layeredGestureStayedCaptured = engine.HasCapturedStateForTest();
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            await Task.Delay(40);
            Check(layeredGesturePreserved && layeredGestureStayedCaptured && events.SequenceEqual(["MouseRight+Space:Gesture:Right", "MouseRight+Space:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "a swallowed mouse gesture remains captured across a profile switch and restores center only on the next physical press");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            var repeatRightMove = engine.DirectMouseForTest(0x200, 0, 112, 100);
            await Task.Delay(140);
            var repeatLeftMove = engine.DirectMouseForTest(0x200, 0, 88, 100);
            await Task.Delay(140);
            var repeatRightAgainMove = engine.DirectMouseForTest(0x200, 0, 112, 100);
            await Task.Delay(140);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(repeatRightMove == (IntPtr)1 && repeatLeftMove == (IntPtr)1 && repeatRightAgainMove == (IntPtr)1 && events.SequenceEqual(["MouseRight+Space:Gesture:Right", "MouseRight+Space:Gesture:Left", "MouseRight+Space:Gesture:Right"]) && !engine.HasCapturedStateForTest(), "one right-click plus Space hold keeps the cursor locked and executes each stopped right-left-right movement once");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            bool continuousGestureMovesSwallowed = true;
            for (int i = 0; i < 12; i++)
            {
                continuousGestureMovesSwallowed &= engine.DirectMouseForTest(0x200, 0, i % 2 == 0 ? 112 : 88, 100) == (IntPtr)1;
                await Task.Delay(140);
            }
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(continuousGestureMovesSwallowed && events.Count == 12 && events.Where((x, i) => x == (i % 2 == 0 ? "MouseRight+Space:Gesture:Right" : "MouseRight+Space:Gesture:Left")).Count() == 12 && !engine.HasCapturedStateForTest(), "one held gesture accepts repeated move-and-stop segments without narrowing its input window or retaining state");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            bool sameDirectionMovesSwallowed = true;
            for (int i = 0; i < 200; i++)
                sameDirectionMovesSwallowed &= engine.DirectMouseForTest(0x200, 0, 70, 100) == (IntPtr)1;
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(sameDirectionMovesSwallowed && events.SequenceEqual(["MouseRight+Space:Gesture:Left"]) && !engine.HasCapturedStateForTest(), "one continuous left movement executes the left action exactly once even across 200 mouse events");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            var firstStoppedLeft = engine.DirectMouseForTest(0x200, 0, 70, 100);
            await Task.Delay(140);
            var secondStoppedLeft = engine.DirectMouseForTest(0x200, 0, 70, 100);
            await Task.Delay(140);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(firstStoppedLeft == (IntPtr)1 && secondStoppedLeft == (IntPtr)1 && events.SequenceEqual(["MouseRight+Space:Gesture:Left", "MouseRight+Space:Gesture:Left"]) && !engine.HasCapturedStateForTest(), "while the gesture stays armed, move-left then stop can be repeated in the same direction and executes once per stopped movement");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(events.SequenceEqual(["MouseRight+Space:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "right-click layer plus Space without movement executes the center action and releases both inputs");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            engine.DirectMouseForTest(0x200, 0, 101, 100);
            await Task.Delay(140);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(events.SequenceEqual(["MouseRight+Space:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "ordinary mouse jitter below the gesture threshold still executes the short-press action on release");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectKeyForTest(0x20, false);
            bool profileChangeAllowed = engine.TryPrepareForProfileChange(vk => vk is 0x02 or 0x20);
            bool gesturePreserved = engine.HasCapturedStateForTest();
            engine.DirectMouseForTest(0x200, 0, 114, 100);
            engine.DirectKeyForTest(0x20, true);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            bool profileChangeReady = engine.TryPrepareForProfileChange(_ => false);
            rightSpaceGestureMode = false;
            bool chromeProfileClean = engine.TryPrepareForProfileChange(_ => false);
            rightSpaceGestureMode = true;
            bool standardProfileClean = engine.TryPrepareForProfileChange(_ => false);
            for (int i = 0; i < 25; i++)
            {
                engine.DirectMouseForTest(0x204, 0, 100, 100);
                engine.DirectKeyForTest(0x20, false);
                engine.DirectMouseForTest(0x200, 0, 114, 100);
                engine.DirectKeyForTest(0x20, true);
                engine.DirectMouseForTest(0x205, 0, 100, 100);
            }
            Check(profileChangeAllowed && gesturePreserved && profileChangeReady && chromeProfileClean && standardProfileClean && events.Count(x => x == "MouseRight+Space:Gesture:Right") == 26 && !engine.HasCapturedStateForTest(), "profile switching preserves an active gesture and the gesture still repeats after the profile round trip");
            rightSpaceGestureMode = false;
            multiLayerMappings = true;
            events.Clear();
            engine.ResetStateForTest();
            int lifecycleStart = inputStarts.Count, lifecycleEnd = inputEnds.Count, layerStart = layerStarts.Count, layerEnd = layerEnds.Count;
            engine.DirectMouseForTest(0x20B, 2 << 16, 100, 100);
            bool forwardProfileChangeAllowed = engine.TryPrepareForProfileChange(_ => false);
            for (int i = 0; i < 40; i++)
            {
                engine.DirectMouseForTest(0x201, 0, 100, 100);
                engine.DirectMouseForTest(0x202, 0, 100, 100);
            }
            engine.DirectMouseForTest(0x20C, 2 << 16, 100, 100);
            Check(forwardProfileChangeAllowed && events.Count(x => x == "MouseForward+MouseLeft") == 40 && !engine.HasCapturedStateForTest() && inputStarts.Count - lifecycleStart == inputEnds.Count - lifecycleEnd && layerStarts.Count - layerStart == 1 && layerEnds.Count - layerEnd == 1, "a swallowed Forward layer survives a profile change even when Windows reports XBUTTON2 as up, then executes every repeated left click with balanced snapshots");
            events.Clear();
            engine.ResetStateForTest();
            int rawLayerStart = layerStarts.Count, rawLayerEnd = layerEnds.Count;
            engine.DirectMouseForTest(0x20B, 2 << 16, 100, 100);
            engine.DirectMouseForTest(0x201, 0, 100, 100);
            engine.DirectMouseForTest(0x202, 0, 100, 100);
            engine.ReconcileRawMouseButtonUpForTest("MouseLeft");
            bool rawLeftPreservedHeldForward = engine.HasCapturedStateForTest();
            // Deliberately omit the low-level XBUTTON2 Up. WM_INPUT must be able to
            // retire the layer independently when a desktop transition loses it.
            engine.ReconcileRawMouseButtonUpForTest("MouseForward");
            bool rawForwardRecovered = !engine.HasCapturedStateForTest();
            multiLayerMappings = false;
            engine.DirectMouseForTest(0x201, 0, 100, 100);
            engine.DirectMouseForTest(0x202, 0, 100, 100);
            Check(rawLeftPreservedHeldForward && rawForwardRecovered && events.Count(x => x == "MouseForward+MouseLeft") == 1 && events.Count(x => x == "MouseLeft") == 1 && layerStarts.Count - rawLayerStart == 1 && layerEnds.Count - rawLayerEnd == 1, "raw physical Up recovery clears a Forward layer whose low-level Up was lost, preserves repeated layer clicks, and returns the next ordinary click to Windows mapping");
            events.Clear();
            engine.ResetStateForTest();
            engine.SetRawInputMonitorStartedForTest(true);
            engine.NextHookForTest = (_, _, _) => forwarded;
            plainMouseMappings = true;
            var rawFirstRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.ReconcileRawMouseButtonUpForTest("MouseRight");
            var delayedLowLevelRightUp = engine.DirectMouseForTest(0x205, 0, 100, 100);
            plainMouseMappings = false;
            var nextOrdinaryRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.ObserveRawMouseButtonDownForTest("MouseRight");
            var nextOrdinaryRightUp = engine.DirectMouseForTest(0x205, 0, 100, 100);
            engine.ReconcileRawMouseButtonUpForTest("MouseRight");
            Check(rawFirstRightDown == (IntPtr)1 && delayedLowLevelRightUp == (IntPtr)1 && events.Count(x => x == "MouseRight") == 1 && nextOrdinaryRightDown == forwarded && nextOrdinaryRightUp == forwarded && !engine.HasCapturedStateForTest(), "raw-first mapped right release suppresses its delayed low-level Up exactly once, never opens a native context menu, and preserves the next ordinary right click");
            engine.SetRawInputMonitorStartedForTest(false);
            engine.NextHookForTest = null;
            multiLayerMappings = true;
            foreach (var mouseLayerCase in new[]
            {
                (Name: "MouseLeft", Down: 0x201, Data: 0),
                (Name: "MouseMiddle", Down: 0x207, Data: 0),
                (Name: "MouseBack", Down: 0x20B, Data: 1 << 16),
                (Name: "MouseForward", Down: 0x20B, Data: 2 << 16)
            })
            {
                events.Clear();
                engine.ResetStateForTest();
                int sourceLayerStarts = layerStarts.Count, sourceLayerEnds = layerEnds.Count;
                engine.DirectMouseForTest(mouseLayerCase.Down, mouseLayerCase.Data, 100, 100);
                engine.DirectKeyForTest(0x4A, false);
                engine.DirectKeyForTest(0x4A, true);
                engine.ReconcileRawMouseButtonUpForTest(mouseLayerCase.Name);
                Check(events.Count(x => x == mouseLayerCase.Name + "+J") == 1 && !engine.HasCapturedStateForTest() && layerStarts.Count - sourceLayerStarts == 1 && layerEnds.Count - sourceLayerEnds == 1, $"raw release recovery independently retires a lost {mouseLayerCase.Name} layer Up without changing its mapped key action");
            }
            multiLayerMappings = false;
            rightWheelLayer = true;
            events.Clear();
            engine.ResetStateForTest();
            int rightRawLayerStarts = layerStarts.Count, rightRawLayerEnds = layerEnds.Count;
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectMouseForTest(0x20A, 120 << 16, 100, 100);
            engine.ReconcileRawMouseButtonUpForTest("MouseRight");
            Check(events.Count(x => x == "MouseRight+WheelUp") == 1 && !engine.HasCapturedStateForTest() && layerStarts.Count - rightRawLayerStarts == 1 && layerEnds.Count - rightRawLayerEnds == 1, "raw release recovery independently retires a lost MouseRight layer Up without changing its wheel action");
            rightWheelLayer = false;
            multiLayerMappings = true;
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x20B, 2 << 16, 100, 100);
            engine.ResetForSessionTransition();
            bool clearedAtUnlock = !engine.HasCapturedStateForTest();
            engine.DirectMouseForTest(0x20B, 2 << 16, 100, 100);
            for (int i = 0; i < 20; i++)
            {
                engine.TryPrepareForProfileChange(_ => false);
                engine.DirectMouseForTest(0x201, 0, 100, 100);
                engine.DirectMouseForTest(0x202, 0, 100, 100);
                engine.TryPrepareForProfileChange(_ => false);
                engine.DirectMouseForTest(0x204, 0, 100, 100);
                engine.DirectMouseForTest(0x205, 0, 100, 100);
            }
            engine.DirectMouseForTest(0x20C, 2 << 16, 100, 100);
            Check(clearedAtUnlock && events.Count(x => x == "MouseForward+MouseLeft") == 20 && events.Count(x => x == "MouseForward+MouseRight") == 20 && !engine.HasCapturedStateForTest(), "after a Win+L session reset, a fresh held Forward press survives every profile change and repeats both desktop directions without re-pressing Forward");
            multiLayerMappings = false;
            normalRightGestureMode = true;
            events.Clear();
            engine.ResetStateForTest();
            var normalRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            var normalRightMove = engine.DirectMouseForTest(0x200, 0, 114, 100);
            var normalRightUp = engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(normalRightDown == (IntPtr)1 && normalRightMove == (IntPtr)1 && normalRightUp == (IntPtr)1 && events.SequenceEqual(["MouseRight:Gesture:Right"]) && !engine.HasCapturedStateForTest(), "gesture assigned directly to normal-layer right click takes precedence over the right-click layer, locks movement, and executes one direction");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            Check(events.SequenceEqual(["MouseRight:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "normal-layer right-click gesture without movement executes its short-press action and fully releases");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectMouseForTest(0x200, 0, 103, 102);
            await Task.Delay(180);
            engine.DirectMouseForTest(0x205, 0, 103, 102);
            Check(events.SequenceEqual(["MouseRight:Gesture:Center"]) && !engine.HasCapturedStateForTest(), "holding a normal-layer right-click gesture with small physical-mouse jitter still produces one normal short press");
            events.Clear();
            engine.ResetStateForTest();
            engine.LockCursorDuringGesture = false;
            engine.NextHookForTest = (_, _, _) => (IntPtr)0x7788;
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            var unlockedMove1 = engine.DirectMouseForTest(0x200, 0, 106, 100);
            var unlockedMove2 = engine.DirectMouseForTest(0x200, 0, 112, 100);
            engine.DirectMouseForTest(0x205, 0, 112, 100);
            Check(unlockedMove1 == (IntPtr)0x7788 && unlockedMove2 == (IntPtr)0x7788 && events.SequenceEqual(["MouseRight:Gesture:Right"]) && !engine.HasCapturedStateForTest(), "cursor-unlocked gestures forward pointer movement while accumulating relative movement into one direction action");
            engine.LockCursorDuringGesture = true;
            engine.NextHookForTest = null;
            normalRightGestureMode = false;
            engine.GestureCursorForTest = null;
            events.Clear();
            engine.ResetStateForTest();
            for (int i = 0; i < 2; i++)
            {
                taskbarQualify = true;
                engine.DirectKeyForTest(0x45, false);
                taskbarQualify = false;
                engine.DirectKeyForTest(0x45, true);
            }
            await Task.Delay(40);
            Check(events.Count(x => x == "Taskbar+E") == 2 && !engine.HasCapturedStateForTest(), "taskbar short press keeps its key-down location through key-up and remains repeatable");
            events.Clear();
            engine.ResetStateForTest();
            taskbarQualify = true;
            engine.DirectKeyForTest(0x2E, false);
            await Task.Delay(140);
            taskbarQualify = false;
            engine.DirectKeyForTest(0x2E, true);
            await Task.Delay(40);
            Check(events.Count(x => x == "Taskbar+Delete:Long") == 1 && !events.Contains("Taskbar+Delete") && !engine.HasCapturedStateForTest(), "taskbar long press executes once, suppresses its short action, and fully releases");
            events.Clear();
            layerStarts.Clear();
            engine.ResetStateForTest();
            rightWheelLayer = true;
            taskbarRightMapped = true;
            taskbarQualify = true;
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            await Task.Delay(140);
            taskbarQualify = false;
            engine.DirectMouseForTest(0x205, 0, 100, 100);
            await Task.Delay(40);
            Check(events.Count(x => x == "Taskbar+MouseRight:Long") == 1 && !layerStarts.Contains("MouseRight") && !engine.HasCapturedStateForTest(), "taskbar right-button long press wins over the normal right-click layer and fully releases");
            rightWheelLayer = false;
            taskbarRightMapped = false;
            taskbarQualify = false;
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(100);
            Check(events.Contains("Space+J"), "Space layer chord [" + string.Join(",", events) + "] detected=[" + string.Join(",", detected.TakeLast(6)) + "]");
            Check(!events.Contains("Space"), "layer chord suppresses tap action");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("U", false);
            InputEngine.InjectKeyForTest("U", false);
            InputEngine.InjectKeyForTest("U", false);
            InputEngine.InjectKeyForTest("U", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(events.Count(x => x == "Space+U") == 3 && !events.Contains("Space") && !engine.HasCapturedStateForTest(), "held Space layer key repeats on every key-down without an extra release action");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("K", false);
            InputEngine.InjectKeyForTest("K", false);
            InputEngine.InjectKeyForTest("K", false);
            InputEngine.InjectKeyForTest("K", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(events.Count(x => x == "Space+K") == 3 && !events.Contains("Space") && !engine.HasCapturedStateForTest(), "held Space+K repeats Enter-style mappings just like every other layer key");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectKeyForTest(0x20, false);
            engine.DirectKeyForTest(0x55, false);
            engine.DirectKeyForTest(0x20, true);
            var repeatAfterLayerUp = engine.DirectKeyForTest(0x55, false);
            var keyUpAfterLayerUp = engine.DirectKeyForTest(0x55, true);
            await Task.Delay(40);
            Check(events.Count(x => x == "Space+U") == 1 && repeatAfterLayerUp == (IntPtr)1 && keyUpAfterLayerUp == (IntPtr)1 && !engine.HasActiveLayerStateForTest(), "releasing Space first stops repeats and suppresses the still-held layer key until key-up");
            events.Clear();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(100);
            Check(events.Contains("Space"), "layer key single tap");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            await Task.Delay(290);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(events.Contains("Space+J") && !events.Contains("Space"), "slow Space chord remains a layer after repeat delay");
            events.Clear();
            repeatCount = 0;
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            events.Clear();
            InputEngine.InjectKeyForTest("Space", false);
            await Task.Delay(290);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(repeatCount >= 3 && !events.Contains("Space"), "Space tap then hold starts repeat without disabling layer hold");
            events.Clear();
            repeatCount = 0;
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            events.Clear();
            InputEngine.InjectKeyForTest("Space", false);
            await Task.Delay(30);
            InputEngine.InjectKeyForTest("K", false);
            InputEngine.InjectKeyForTest("K", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(events.Contains("Space+K") && !events.Contains("Space") && repeatCount == 0, "Space layer chord wins over pending second-hold repeat");
            spaceMappings = false;
            events.Clear();
            repeatCount = 0;
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            InputEngine.InjectKeyForTest("Space", false);
            await Task.Delay(290);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(repeatCount >= 3, "Space tap then hold repeats even when the Space layer has no assignments");
            spaceMappings = true;
            events.Clear();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectMouseForTest("Left", false);
            InputEngine.InjectMouseForTest("Left", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(100);
            Check(events.Contains("Space+MouseLeft") && !events.Contains("Space"), "layer mouse mapping suppresses tap");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectMouseForTest("Left", false);
            InputEngine.InjectKeyForTest("Space", true);
            InputEngine.InjectMouseForTest("Left", true);
            await Task.Delay(100);
            Check(events.Contains("Space+MouseLeft") && !events.Contains("Space"), "layer action completes when layer key is released first");
            engine.TreatF13AsCapsLock = true;
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("F13", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            await Task.Delay(60);
            Check(events.Count(x => x == "CapsLock+J") == 2 && !events.Contains("CapsLock"), "F13-remapped CapsLock hold repeats multiple layer actions");
            InputEngine.InjectKeyForTest("F13", true);
            events.Clear();
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(60);
            Check(events.Contains("Space+J"), "Space layer works immediately after releasing F13-remapped CapsLock");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("F13", false);
            await Task.Delay(120);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("F13", true);
            InputEngine.InjectKeyForTest("Space", false);
            await Task.Delay(120);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(80);
            Check(events.Contains("CapsLock+J") && events.Contains("Space+J"), "layers stay active until their actual key-up event");
            multiLayerMappings = true;
            rightWheelLayer = true;
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("F13", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("F13", true);
            InputEngine.InjectKeyForTest("Space", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("Space", true);
            engine.DirectMouseForTest(0x204);
            InputEngine.InjectWheelForTest(true);
            engine.DirectMouseForTest(0x205);
            engine.DirectMouseForTest(0x20B, 1 << 16);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x20C, 1 << 16);
            engine.DirectMouseForTest(0x20B, 2 << 16);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x20C, 2 << 16);
            InputEngine.InjectKeyForTest("F13", false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            InputEngine.InjectKeyForTest("F13", true);
            await Task.Delay(120);
            Check(events.Count(x => x == "CapsLock+J") == 2 && events.Contains("Space+J") && events.Contains("MouseRight+WheelUp") && events.Contains("MouseBack+J") && events.Contains("MouseForward+J"), "all reliable keyboard and mouse layers work sequentially without retaining prior state");
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x20B, 2 << 16);
            InputEngine.InjectKeyForTest("Up", false);
            InputEngine.InjectKeyForTest("Up", true);
            Check(events.Count(x => x == "MouseForward+Up") == 1, "forward layer confirms a keyboard action once when that key is released");
            events.Clear();
            InputEngine.InjectKeyForTest("Up", false);
            InputEngine.InjectKeyForTest("Up", false);
            InputEngine.InjectMouseForTest("Left", false);
            InputEngine.InjectMouseForTest("Left", true);
            InputEngine.InjectKeyForTest("Up", false);
            InputEngine.InjectKeyForTest("Up", true);
            engine.DirectMouseForTest(0x20C, 2 << 16);
            Check(events.Count(x => x == "MouseForward+Up") == 0 && events.Count(x => x == "MouseForward+MouseLeft") == 1, "forward layer cancels a still-held Up action when left-click becomes the selected operation");
            multiLayerMappings = false;
            rightWheelLayer = false;
            multiLayerMappings = true;
            events.Clear();
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x20B, 2 << 16, 100, 100);
            engine.DirectMouseForTest(0x200, 0, 140, 120);
            engine.DirectMouseForTest(0x201, 0, 140, 120);
            engine.DirectMouseForTest(0x200, 0, 180, 150);
            engine.DirectMouseForTest(0x202, 0, 180, 150);
            engine.DirectMouseForTest(0x20C, 2 << 16, 180, 150);
            await Task.Delay(80);
            Check(events.Count(x => x == "MouseForward+MouseLeft") == 1 && !events.Any(x => x == "MouseForward+MouseLeft:DragEnd"), "forward-layer click executes once even while the pointer keeps moving");
            multiLayerMappings = false;
            var layerReleaseFlags = new ConcurrentBag<(uint Flag, uint Data)>();
            InputEngine.MouseFlagOutputForTest = (flag, data) => layerReleaseFlags.Add((flag, data));
            multiLayerMappings = true;
            rightWheelLayer = true;
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x201);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x202);
            engine.DirectMouseForTest(0x204);
            InputEngine.InjectWheelForTest(true);
            engine.DirectMouseForTest(0x205);
            engine.DirectMouseForTest(0x207);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x208);
            engine.DirectMouseForTest(0x20B, 1 << 16);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x20C, 1 << 16);
            engine.DirectMouseForTest(0x20B, 2 << 16);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            engine.DirectMouseForTest(0x20C, 2 << 16);
            await Task.Delay(120);
            Check(layerReleaseFlags.IsEmpty, "used mouse layers never inject an unmatched source-button release");
            engine.DirectMouseForTest(0x20B, 2 << 16);
            engine.ResetStateForTest();
            await Task.Delay(120);
            Check(layerReleaseFlags.IsEmpty && !InputEngine.HasInjectedInputForTest(), "state reset does not invent a forward-button release when no down was injected");
            InputEngine.MouseFlagOutputForTest = null;
            multiLayerMappings = false;
            rightWheelLayer = false;
            var contextClickFlags = new ConcurrentQueue<uint>();
            var contextClickBatches = new ConcurrentQueue<(uint Flag, uint Data)[]>();
            InputEngine.MouseFlagOutputForTest = (flag, _) => contextClickFlags.Enqueue(flag);
            InputEngine.MouseClickBatchOutputForTest = batch => contextClickBatches.Enqueue(batch);
            plainMouseMappings = false;
            rightWheelLayer = true;
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x204);
            engine.DirectMouseForTest(0x205);
            await Task.Delay(120);
            Check(contextClickBatches.Count == 1 && contextClickBatches.Single().SequenceEqual([(8u, 0u), (16u, 0u)]) && contextClickFlags.IsEmpty, "unused right-click layer replays one atomic context click without a delayed second event");
            InputEngine.MouseClickBatchOutputForTest = null;
            contextClickFlags.Clear();
            engine.DirectMouseForTest(0x204);
            InputEngine.InjectWheelForTest(true);
            engine.DirectMouseForTest(0x205);
            await Task.Delay(120);
            Check(contextClickFlags.IsEmpty, "used right-click layer does not inject an unmatched right-button release");
            InputEngine.MouseFlagOutputForTest = null;
            plainMouseMappings = true;
            rightWheelLayer = false;
            var wheelLayerSourceFlags = new ConcurrentQueue<(uint Flag, uint Data)>();
            InputEngine.MouseFlagOutputForTest = (flag, data) => wheelLayerSourceFlags.Enqueue((flag, data));
            allWheelLayers = true;
            events.Clear();
            engine.ResetStateForTest();
            foreach (var (Name, Down, Up, Data) in new[] { (Name: "MouseRight", Down: 0x204, Up: 0x205, Data: 0), (Name: "MouseBack", Down: 0x20B, Up: 0x20C, Data: 1 << 16), (Name: "MouseForward", Down: 0x20B, Up: 0x20C, Data: 2 << 16) })
            {
                engine.DirectMouseForTest(Down, Data);
                InputEngine.InjectWheelForTest(true);
                InputEngine.InjectWheelForTest(false);
                engine.DirectMouseForTest(Up, Data);
            }
            await Task.Delay(120);
            Check(new[] { "MouseRight", "MouseBack", "MouseForward" }.All(layer => events.Contains(layer + "+WheelUp") && events.Contains(layer + "+WheelDown")) && wheelLayerSourceFlags.IsEmpty && !InputEngine.HasInjectedInputForTest(), "right, back and forward wheel layers never replay their source button on release");
            InputEngine.MouseFlagOutputForTest = null;
            allWheelLayers = false;
            var sideClickBatches = new ConcurrentQueue<(uint Flag, uint Data)[]>();
            InputEngine.MouseClickBatchOutputForTest = batch => sideClickBatches.Enqueue(batch);
            allWheelLayers = true;
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x20B, 1 << 16);
            engine.DirectMouseForTest(0x20C, 1 << 16);
            await Task.Delay(60);
            engine.DirectMouseForTest(0x20B, 2 << 16);
            engine.DirectMouseForTest(0x20C, 2 << 16);
            await Task.Delay(120);
            var sideBatches = sideClickBatches.ToArray();
            Check(sideBatches.Length == 2 && sideBatches[0].SequenceEqual([(0x80u, 1u), (0x100u, 1u)]) && sideBatches[1].SequenceEqual([(0x80u, 2u), (0x100u, 2u)]), "unused back and forward layers replay one complete native click");
            InputEngine.MouseClickBatchOutputForTest = null;
            allWheelLayers = false;
            var nativeRightDragFlags = new ConcurrentQueue<uint>();
            InputEngine.MouseFlagOutputForTest = (flag, _) => nativeRightDragFlags.Enqueue(flag);
            engine.NextHookForTest = (_, _, _) => (IntPtr)0x4567;
            plainMouseMappings = false;
            rightWheelLayer = true;
            engine.DragPixels = 5;
            events.Clear();
            engine.ResetStateForTest();
            var nativeRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            var nativeRightTriggerMove = engine.DirectMouseForTest(0x200, 0, 120, 110);
            SpinWait.SpinUntil(() => nativeRightDragFlags.Contains(8u), 500);
            var nativeRightMove = engine.DirectMouseForTest(0x200, 0, 121, 111);
            var nativeRightUp = engine.DirectMouseForTest(0x205, 0, 120, 110);
            await Task.Delay(120);
            Check(nativeRightDown == (IntPtr)1 && nativeRightTriggerMove == (IntPtr)1 && nativeRightMove == (IntPtr)0x4567 && nativeRightUp == (IntPtr)1 && nativeRightDragFlags.ToArray().SequenceEqual(new uint[] { 8, 16 }) && !events.Any(x => x.StartsWith("MouseRight+", StringComparison.OrdinalIgnoreCase)) && !InputEngine.HasInjectedInputForTest(), "moving the right button starts native drag off the hook thread, suppresses only the movement that would overtake RightDown, and releases safely");
            nativeRightDragFlags.Clear();
            events.Clear();
            engine.ResetStateForTest();
            nativeRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            nativeRightTriggerMove = engine.DirectMouseForTest(0x200, 0, 120, 110);
            SpinWait.SpinUntil(() => nativeRightDragFlags.Contains(8u), 500);
            nativeRightMove = engine.DirectMouseForTest(0x200, 0, 121, 111);
            var nativeRightWheel = engine.DirectMouseForTest(0x20A, 120 << 16, 120, 110);
            nativeRightUp = engine.DirectMouseForTest(0x205, 0, 120, 110);
            await Task.Delay(120);
            Check(nativeRightDown == (IntPtr)1 && nativeRightTriggerMove == (IntPtr)1 && nativeRightMove == (IntPtr)0x4567 && nativeRightWheel == (IntPtr)1 && nativeRightUp == (IntPtr)1 && nativeRightDragFlags.ToArray().SequenceEqual(new uint[] { 8, 16 }) && events.Contains("MouseRight+WheelUp") && !InputEngine.HasInjectedInputForTest(), "a mapped right-layer action still executes after the worker establishes native drag and safely ends passthrough");
            engine.NextHookForTest = null;
            InputEngine.MouseFlagOutputForTest = null;
            plainMouseMappings = true;
            rightWheelLayer = false;
            engine.DragPixels = 50;
            engine.TreatF13AsCapsLock = false;
            events.Clear();
            engine.ResetStateForTest();
            var nativeDown = engine.DirectKeyForTest(0x14, false);
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            var nativeUp = engine.DirectKeyForTest(0x14, true);
            await Task.Delay(80);
            Check(nativeDown != (IntPtr)1 && nativeUp != (IntPtr)1 && !events.Contains("CapsLock+J"), "native CapsLock is passed through and never starts a layer without F13 remap");
            engine.TreatF13AsCapsLock = true;
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("F13", false);
            engine.ExpireLayerForTest();
            InputEngine.InjectKeyForTest("J", false);
            InputEngine.InjectKeyForTest("J", true);
            await Task.Delay(100);
            Check(!events.Contains("CapsLock+J"), "expired F13-remapped CapsLock layer is recovered before the next input");
            InputEngine.InjectKeyForTest("F13", true);
            engine.TreatF13AsCapsLock = false;
            events.Clear();
            bool capsBefore = System.Windows.Forms.Control.IsKeyLocked(System.Windows.Forms.Keys.CapsLock);
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("CapsLock", false);
            InputEngine.InjectKeyForTest("CapsLock", true);
            await Task.Delay(150);
            bool capsAfter = System.Windows.Forms.Control.IsKeyLocked(System.Windows.Forms.Keys.CapsLock);
            Check(capsAfter == capsBefore && !events.Any(x => x.StartsWith("CapsLock")), "native CapsLock remains outside the layer state machine");
            InputEngine.InjectKeyForTest("K", false);
            await Task.Delay(180);
            InputEngine.InjectKeyForTest("K", true);
            await Task.Delay(30);
            Check(events.Contains("K:Long") && !events.Contains("K"), "long press discrimination");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Esc", false);
            await Task.Delay(180);
            InputEngine.InjectKeyForTest("Esc", true);
            await Task.Delay(30);
            Check(events.Contains("Esc:Long") && !events.Contains("Esc"), "Esc supports a long-only shortcut without firing its normal tap");
            events.Clear();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Esc", false);
            engine.CancelLongPressTimerForTest("Esc");
            await Task.Delay(180);
            InputEngine.InjectKeyForTest("Esc", true);
            await Task.Delay(30);
            Check(events.Contains("Esc:Long") && !events.Contains("Esc"), "Esc release-time fallback executes the long action even when the timer callback is unavailable");
            events.Clear();
            engine.DragPixels = int.MaxValue;
            InputEngine.InjectMouseForTest("Left", false);
            await Task.Delay(30);
            InputEngine.InjectMouseForTest("Left", true);
            await Task.Delay(100);
            Check(events.Contains("MouseLeft"), "mouse hook click");
            engine.DragPixels = 1;
            legacyMouseDrag = true;
            events.Clear();
            InputEngine.InjectMouseForTest("Left", false);
            await Task.Delay(20);
            InputEngine.InjectMouseMoveForTest(20, 10);
            await Task.Delay(100);
            InputEngine.InjectMouseForTest("Left", true);
            await Task.Delay(50);
            bool dragStart = events.Any(x => x.EndsWith("MouseLeft:DragStart", StringComparison.OrdinalIgnoreCase));
            bool dragEnd = events.Any(x => x.EndsWith("MouseLeft:DragEnd", StringComparison.OrdinalIgnoreCase));
            Check(dragStart && dragEnd, "legacy mouse drag discrimination [" + string.Join(",", events) + "]");
            legacyMouseDrag = false;
            engine.DragPixels = 50;
            events.Clear();
            for (int attempt = 0; attempt < 3 && !events.Contains("MouseRight:Long"); attempt++)
            {
                engine.ResetStateForTest();
                InputEngine.InjectMouseForTest("Right", false);
                await Task.Delay(350);
                InputEngine.InjectMouseForTest("Right", true);
                await Task.Delay(120);
            }
            Check(events.Contains("MouseRight:Long") && !events.Contains("MouseRight"), "mouse long press discrimination");
            engine.ResetStateForTest();
            transientMiddleMapped = false;
            var plainDown = engine.DirectMouseForTest(0x207);
            transientMiddleMapped = true;
            var plainUp = engine.DirectMouseForTest(0x208);
            Check(plainDown != (IntPtr)1 && plainUp != (IntPtr)1, "mapping enabled during click does not swallow physical button-up");
            engine.ResetStateForTest();
            transientMiddleMapped = true;
            var mappedDown = engine.DirectMouseForTest(0x207);
            transientMiddleMapped = false;
            var mappedUp = engine.DirectMouseForTest(0x208);
            Check(mappedDown == (IntPtr)1 && mappedUp == (IntPtr)1, "mapping disabled during click preserves down/up handling pair");
            var physicalReleaseFlags = new List<uint>();
            InputEngine.MouseFlagOutputForTest = (flag, _) => physicalReleaseFlags.Add(flag);
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x201);
            engine.DirectMouseForTest(0x202);
            engine.DirectMouseForTest(0x204);
            engine.DirectMouseForTest(0x205);
            Check(physicalReleaseFlags.Count == 0 && !InputEngine.HasInjectedInputForTest(), "physical mouse callbacks never inject reentrant button events");
            InputEngine.MouseFlagOutputForTest = null;
            transientMiddleMapped = true;
            engine.DirectMouseForTest(0x207);
            engine.Enabled = false;
            engine.Enabled = true;
            var orphanUp = engine.DirectMouseForTest(0x208);
            Check(orphanUp != (IntPtr)1, "engine toggle releases click state and passes orphan button-up");
            transientMiddleMapped = false;
            rightWheelLayer = true;
            engine.Enabled = false;
            var disabledRightDown = engine.DirectMouseForTest(0x204);
            var disabledWheel = engine.DirectMouseForTest(0x20A, 120 << 16);
            var disabledRightUp = engine.DirectMouseForTest(0x205);
            Check(disabledRightDown != (IntPtr)1 && disabledWheel != (IntPtr)1 && disabledRightUp != (IntPtr)1, "disabled engine always passes right-click layers and wheel input through");
            engine.Enabled = true;
            events.Clear();
            engine.ResetStateForTest();
            engine.DragPixels = 1;
            var movingRightWheelFlags = new List<uint>();
            var movingRightWheelMoves = new List<(int X, int Y)>();
            InputEngine.MouseFlagOutputForTest = (flag, _) => movingRightWheelFlags.Add(flag);
            InputEngine.MouseMoveOutputForTest = (x, y) => movingRightWheelMoves.Add((x, y));
            var movingRightDown = engine.DirectMouseForTest(0x204, 0, 100, 100);
            var movingRightMove = engine.DirectMouseForTest(0x200, 0, 112, 100);
            await Task.Delay(40);
            var movingWheelUp = engine.DirectMouseForTest(0x20A, 120 << 16, 112, 100);
            var movingWheelDown = engine.DirectMouseForTest(0x20A, unchecked((int)(-120 << 16)), 114, 101);
            var movingRightUp = engine.DirectMouseForTest(0x205, 0, 114, 101);
            await Task.Delay(40);
            Check(movingRightDown == (IntPtr)1 && movingRightMove == (IntPtr)1 && movingWheelUp == (IntPtr)1 && movingWheelDown == (IntPtr)1 && movingRightUp == (IntPtr)1
                && events.Contains("MouseRight+WheelUp") && events.Contains("MouseRight+WheelDown")
                && movingRightWheelFlags.SequenceEqual([8u, 16u]) && movingRightWheelMoves.SequenceEqual([(12, 0)]) && !engine.HasCapturedStateForTest(),
                "a mapped right-wheel action keeps Filmora-style native right drag and pairs its synthetic Down with movement before Up");
            InputEngine.MouseFlagOutputForTest = null;
            InputEngine.MouseMoveOutputForTest = null;
            rightWheelLayer = false;
            rightSpaceGestureMode = true;
            events.Clear();
            engine.ResetStateForTest();
            bool physicalRightButtonDown = true;
            var recoveredNativeRightDragFlags = new List<uint>();
            InputEngine.PhysicalKeyDownForTest = key => key == 0x02 && physicalRightButtonDown;
            InputEngine.MouseFlagOutputForTest = (flag, _) => recoveredNativeRightDragFlags.Add(flag);
            int nativeLayerStarts = layerStarts.Count, nativeLayerEnds = layerEnds.Count;
            engine.DirectMouseForTest(0x204, 0, 100, 100);
            engine.DirectMouseForTest(0x200, 0, 112, 100);
            physicalRightButtonDown = false;
            await Task.Delay(180);
            Check(recoveredNativeRightDragFlags.SequenceEqual([8u, 16u]) && !engine.HasCapturedStateForTest() && layerStarts.Count == nativeLayerStarts + 1 && layerEnds.Count == nativeLayerEnds + 1, "a lost right-button up after native right drag releases the synthetic drag and clears the layer snapshot");
            InputEngine.MouseFlagOutputForTest = null;
            InputEngine.PhysicalKeyDownForTest = null;
            engine.DragPixels = 50;
            rightSpaceGestureMode = false;
            engine.ResetStateForTest();
            transientKeyMapped = false;
            var plainKeyDown = engine.DirectKeyForTest(0x42, false);
            transientKeyMapped = true;
            var plainKeyUp = engine.DirectKeyForTest(0x42, true);
            Check(plainKeyDown != (IntPtr)1 && plainKeyUp != (IntPtr)1, "mapping enabled during key press does not swallow physical key-up");
            engine.ResetStateForTest();
            transientKeyMapped = true;
            var mappedKeyDown = engine.DirectKeyForTest(0x42, false);
            transientKeyMapped = false;
            var mappedKeyUp = engine.DirectKeyForTest(0x42, true);
            Check(mappedKeyDown == (IntPtr)1 && mappedKeyUp == (IntPtr)1, "mapping disabled during key press preserves down/up handling pair");
            var nativeDragOutput = new List<string>();
            string[] NativeDragSnapshot()
            {
                lock (nativeDragOutput)
                    return [.. nativeDragOutput];
            }
            void ClearNativeDrag()
            {
                lock (nativeDragOutput)
                    nativeDragOutput.Clear();
            }
            InputEngine.KeyOutputForTest = (key, up) => { lock (nativeDragOutput) nativeDragOutput.Add($"K:{key}:{(up ? "U" : "D")}"); return true; };
            InputEngine.MouseFlagOutputForTest = (flag, _) => { lock (nativeDragOutput) nativeDragOutput.Add("M:" + flag); };
            var nativeDragQueue = new BlockingCollection<string>();
            var nativeDragWorker = Task.Factory.StartNew(() =>
            {
                foreach (var input in nativeDragQueue.GetConsumingEnumerable())
                {
                    InputEngine.SendMouse(input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase) ? "CtrlDrag:Start" : "CtrlDrag:End");
                    if (input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase))
                        engine.NotifyNativeMouseDragStarted(input);
                }
            }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            engine.IsNativeMouseDrag = input => input == "Space+MouseLeft";
            engine.InputReceived = input => { lock (events) events.Add(input); if (input is "Space+MouseLeft:PressStart" or "Space+MouseLeft:PressEnd") return nativeDragQueue.TryAdd(input); return !input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase); };
            engine.DragPixels = 1;
            events.Clear();
            ClearNativeDrag();
            engine.ResetStateForTest();
            engine.NextHookForTest = (_, _, _) => forwarded;
            engine.InputReceived = input =>
            {
                lock (events) events.Add(input);
                if (input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase))
                    return true;
                if (input.EndsWith(":PressEnd", StringComparison.OrdinalIgnoreCase))
                {
                    InputEngine.SendMouse("CtrlDrag:End");
                    return true;
                }
                return false;
            };
            InputEngine.InjectKeyForTest("Space", false);
            var gatedDown = engine.DirectMouseForTest(0x201);
            var moveBeforeStart = engine.DirectMouseForTest(0x200, 0, 120, 110);
            InputEngine.SendMouse("CtrlDrag:Start");
            engine.NotifyNativeMouseDragStarted("Space+MouseLeft:PressStart");
            var moveAfterStart = engine.DirectMouseForTest(0x200, 0, 140, 120);
            var gatedUp = engine.DirectMouseForTest(0x202, 0, 140, 120);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            Check(gatedDown == (IntPtr)1 && moveBeforeStart == (IntPtr)1 && moveAfterStart == forwarded && gatedUp == (IntPtr)1 && NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2", "M:4", "K:17:U"]) && !InputEngine.HasInjectedInputForTest(), "mouse movement is held back until asynchronous Ctrl+LeftDown is ready, then mouse-up always releases Left before Ctrl");
            engine.NextHookForTest = null;
            engine.InputReceived = input => { lock (events) events.Add(input); if (input is "Space+MouseLeft:PressStart" or "Space+MouseLeft:PressEnd") return nativeDragQueue.TryAdd(input); return !input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase); };
            events.Clear();
            ClearNativeDrag();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            var dragDownResult = engine.DirectMouseForTest(0x201);
            await Task.Delay(30);
            bool startedAtPhysicalDown = dragDownResult == (IntPtr)1 && NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2"]);
            InputEngine.InjectMouseMoveForTest(20, 10);
            var dragUpResult = engine.DirectMouseForTest(0x202);
            bool endQueuedBeforeHookReturned;
            lock (events)
                endQueuedBeforeHookReturned = events.Count(x => x == "Space+MouseLeft:PressEnd") == 1;
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            Check(startedAtPhysicalDown && dragUpResult == (IntPtr)1 && !endQueuedBeforeHookReturned && NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2", "M:4", "K:17:U"]) && events.Count(x => x == "Space+MouseLeft:PressStart") == 1 && events.Count(x => x == "Space+MouseLeft:PressEnd") == 1 && !InputEngine.HasInjectedInputForTest(), "AHK-style Ctrl drag releases immediately after the physical mouse-up hook returns so Office can finalize copy-on-drop");
            events.Clear();
            ClearNativeDrag();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            var rapidDownResult = engine.DirectMouseForTest(0x201);
            var rapidUpResult = engine.DirectMouseForTest(0x202);
            InputEngine.InjectKeyForTest("Space", true);
            await Task.Delay(40);
            Check(rapidDownResult == (IntPtr)1 && rapidUpResult == (IntPtr)1 && NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2", "M:4", "K:17:U"]) && events.Count(x => x == "Space+MouseLeft:PressStart") == 1 && events.Count(x => x == "Space+MouseLeft:PressEnd") == 1, "a rapid Ctrl click keeps its ordered synthetic down/up pair instead of being discarded before the output worker wakes");
            events.Clear();
            ClearNativeDrag();
            engine.ResetStateForTest();
            InputEngine.InjectKeyForTest("Space", false);
            dragDownResult = engine.DirectMouseForTest(0x201);
            await Task.Delay(30);
            InputEngine.InjectMouseMoveForTest(20, 10);
            InputEngine.InjectKeyForTest("Space", true);
            bool ctrlHeldUntilMouseUp = NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2"]) && InputEngine.HasInjectedInputForTest();
            dragUpResult = engine.DirectMouseForTest(0x202);
            await Task.Delay(40);
            Check(dragDownResult == (IntPtr)1 && dragUpResult == (IntPtr)1 && ctrlHeldUntilMouseUp && NativeDragSnapshot().SequenceEqual(["K:17:D", "M:2", "M:4", "K:17:U"]) && events.Count(x => x == "Space+MouseLeft:PressStart") == 1 && events.Count(x => x == "Space+MouseLeft:PressEnd") == 1 && !InputEngine.HasInjectedInputForTest(), "AHK-style Ctrl drag waits for mouse release when the Space layer is released first");
            nativeDragQueue.CompleteAdding();
            await nativeDragWorker;
            string rawModifierAction = "";
            engine.InputReceived = input =>
            {
                lock (events) events.Add(input);
                if (input == "Space+MouseLeft:PressStart")
                {
                    InputEngine.SendMouse(rawModifierAction + ":Start");
                    return true;
                }
                if (input == "Space+MouseLeft:PressEnd")
                {
                    InputEngine.SendMouse(rawModifierAction + ":End");
                    return true;
                }
                return !input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase);
            };
            foreach (var modifierCase in new[] { (Action: "ShiftDrag", Key: (ushort)0x10), (Action: "CtrlDrag", Key: (ushort)0x11), (Action: "AltDrag", Key: (ushort)0x12) })
            {
                rawModifierAction = modifierCase.Action;
                events.Clear();
                ClearNativeDrag();
                engine.ResetStateForTest();
                engine.SetRawInputMonitorStartedForTest(true);
                engine.NextHookForTest = (_, _, _) => forwarded;
                spaceMappings = true;
                plainMouseMappings = false;
                engine.DirectKeyForTest(0x20, false);
                var modifierDown = engine.DirectMouseForTest(0x201);
                engine.ReconcileRawMouseButtonUpForTest("MouseLeft");
                var modifierDelayedUp = engine.DirectMouseForTest(0x202);
                engine.DirectKeyForTest(0x20, true);
                await Task.Delay(40);
                spaceMappings = false;
                var followingDown = engine.DirectMouseForTest(0x201);
                engine.ObserveRawMouseButtonDownForTest("MouseLeft");
                var followingUp = engine.DirectMouseForTest(0x202);
                engine.ReconcileRawMouseButtonUpForTest("MouseLeft");
                Check(modifierDown == (IntPtr)1 && modifierDelayedUp == (IntPtr)1 && NativeDragSnapshot().SequenceEqual([$"K:{modifierCase.Key}:D", "M:2", "M:4", $"K:{modifierCase.Key}:U"]) && events.Count(x => x == "Space+MouseLeft:PressStart") == 1 && events.Count(x => x == "Space+MouseLeft:PressEnd") == 1 && followingDown == forwarded && followingUp == forwarded && !InputEngine.HasInjectedInputForTest() && !engine.HasCapturedStateForTest(), $"raw-first {modifierCase.Action} releases its modifier and synthetic click once, suppresses the delayed source Up, and preserves the following ordinary click");
            }
            engine.SetRawInputMonitorStartedForTest(false);
            engine.NextHookForTest = null;
            spaceMappings = true;
            plainMouseMappings = true;
            engine.IsNativeMouseDrag = null;
            engine.InputReceived = input => { lock (events) events.Add(input); return !input.EndsWith(":PressStart", StringComparison.OrdinalIgnoreCase); };
            engine.DragPixels = 50;
            InputEngine.MouseFlagOutputForTest = null;
            InputEngine.KeyOutputForTest = null;
            var symbolOutput = new List<(ushort Key, bool Up)>();
            InputEngine.KeyOutputForTest = (key, up) => { symbolOutput.Add((key, up)); return true; };
            InputEngine.NeutralizePhysicalSourceKey("Space+G");
            Check(symbolOutput.SequenceEqual([((ushort)0x47, true)]), "long-press source neutralization releases G before a synthetic Windows chord");
            symbolOutput.Clear();
            bool lockRequested = false;
            InputEngine.LockWorkStationOutputForTest = () => lockRequested = true;
            InputEngine.SendShortcut("LWin+L");
            InputEngine.LockWorkStationOutputForTest = null;
            Check(lockRequested && symbolOutput.Count == 0 && !InputEngine.HasInjectedInputForTest(), "LWin+L invokes the Windows lock operation directly without leaving generated keys down");
            symbolOutput.Clear();
            InputEngine.SendShortcut("?");
            Check(symbolOutput.SequenceEqual([((ushort)0x10, false), ((ushort)0xBF, false), ((ushort)0xBF, true), ((ushort)0x10, true)]) && !InputEngine.HasInjectedInputForTest(), "JIS question mark sends Shift plus slash and releases both");
            symbolOutput.Clear();
            InputEngine.SendShortcut("!");
            Check(symbolOutput.SequenceEqual([((ushort)0x10, false), ((ushort)0x31, false), ((ushort)0x31, true), ((ushort)0x10, true)]) && !InputEngine.HasInjectedInputForTest(), "JIS exclamation sends Shift plus 1 and releases both");
            symbolOutput.Clear();
            InputEngine.SendShortcut("?", true);
            Check(symbolOutput.SequenceEqual([((ushort)0x10, false), ((ushort)0xBF, false), ((ushort)0xBF, true), ((ushort)0x10, true)]) && !InputEngine.HasInjectedInputForTest(), "US question mark sends Shift plus slash and releases both");
            symbolOutput.Clear();
            InputEngine.SendText("?");
            Check(symbolOutput.SequenceEqual([((ushort)0x10, false), ((ushort)0xBF, false), ((ushort)0xBF, true), ((ushort)0x10, true)]) && !InputEngine.HasInjectedInputForTest(), "single-character text uses browser-compatible physical JIS key events");
            symbolOutput.Clear();
            InputEngine.SendText("A", true);
            Check(symbolOutput.SequenceEqual([((ushort)0x10, false), ((ushort)0x41, false), ((ushort)0x41, true), ((ushort)0x10, true)]) && !InputEngine.HasInjectedInputForTest(), "uppercase text preserves Shift and releases every generated key");
            symbolOutput.Clear();
            var unicodeText = new List<string>();
            InputEngine.UnicodeTextOutputForTest = unicodeText.Add;
            InputEngine.SendText("日本語");
            Check(unicodeText.SequenceEqual(["日本語"]) && symbolOutput.Count == 0, "multi-character Unicode text stays exact and is emitted as one batch");
            var imeModes = new List<int>();
            InputEngine.ImeActionOutputForTest = imeModes.Add;
            InputEngine.SendShortcut("ImeOn");
            InputEngine.SendShortcut("ImeOff");
            InputEngine.SendShortcut("ImeToggle");
            Check(imeModes.SequenceEqual([1, 0, 2]), "IME on, off and toggle actions dispatch deterministic states");
            InputEngine.ImeActionOutputForTest = null;
            InputEngine.UnicodeTextOutputForTest = null;
            InputEngine.KeyOutputForTest = null;
            var modifierDragKeys = new List<(ushort Key, bool Up)>();
            var modifierDragMouse = new List<uint>();
            InputEngine.KeyOutputForTest = (key, up) => { modifierDragKeys.Add((key, up)); return true; };
            InputEngine.MouseFlagOutputForTest = (flag, _) => modifierDragMouse.Add(flag);
            InputEngine.SendMouse("ShiftDrag");
            Check(modifierDragKeys.SequenceEqual([((ushort)0x10, false), ((ushort)0x10, true)]) && modifierDragMouse.SequenceEqual(new uint[] { 2, 4 }) && !InputEngine.HasInjectedInputForTest(), "Shift drag single press sends Shift+left click and releases both");
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            InputEngine.SendMouse("ShiftDrag:Start");
            Check(modifierDragKeys.SequenceEqual([((ushort)0x10, false)]) && modifierDragMouse.SequenceEqual(new uint[] { 2 }) && InputEngine.HasInjectedInputForTest(), "Shift drag start holds Shift and synthetic left down");
            InputEngine.SendMouse("ShiftDrag:End");
            Check(modifierDragKeys.LastOrDefault() == ((ushort)0x10, true) && modifierDragMouse.LastOrDefault() == 4 && !InputEngine.HasInjectedInputForTest(), "Shift drag end releases left before Shift");
            int endedKeyCount = modifierDragKeys.Count, endedMouseCount = modifierDragMouse.Count;
            InputEngine.SendMouse("ShiftDrag:End");
            Check(modifierDragKeys.Count == endedKeyCount && modifierDragMouse.Count == endedMouseCount, "duplicate drag end never injects unrelated releases");
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            InputEngine.SendMouse("CtrlDrag");
            Check(modifierDragKeys.SequenceEqual([((ushort)0x11, false), ((ushort)0x11, true)]) && modifierDragMouse.SequenceEqual(new uint[] { 2, 4 }) && !InputEngine.HasInjectedInputForTest(), "Ctrl drag single press sends Ctrl+left click and releases both");
            InputEngine.SendMouse("CtrlDrag:Start");
            engine.ResetStateForTest();
            Check(!InputEngine.HasInjectedInputForTest() && modifierDragMouse.SequenceEqual(new uint[] { 2, 4, 2, 4 }) && modifierDragKeys.LastOrDefault() == ((ushort)0x11, true), "state reset safely releases an interrupted Ctrl drag");
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            InputEngine.PhysicalKeyDownForTest = _ => false;
            InputEngine.SendMouse("CtrlDrag:Start");
            await Task.Delay(220);
            Check(!InputEngine.HasInjectedInputForTest() && modifierDragMouse.LastOrDefault() == 4 && modifierDragKeys.LastOrDefault() == ((ushort)0x11, true), "physical mouse release watchdog ends Ctrl drag even when its hook end event is lost");
            InputEngine.PhysicalKeyDownForTest = null;
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            plainMouseMappings = false;
            engine.ResetStateForTest();
            engine.DirectMouseForTest(0x201);
            Check(InputEngine.IsObservedPhysicalMouseButtonDownForTest(1), "physical left Down is tracked independently from generated mouse state");
            InputEngine.SendMouse("CtrlDrag:Start");
            engine.DirectMouseForTest(0x202);
            SpinWait.SpinUntil(() => !InputEngine.HasInjectedInputForTest(), 500);
            Check(!InputEngine.IsObservedPhysicalMouseButtonDownForTest(1) && !InputEngine.HasInjectedInputForTest() && modifierDragMouse.SequenceEqual([2u, 4u]) && modifierDragKeys.LastOrDefault() == ((ushort)0x11, true), "physical left Up immediately releases a generated drag even when its queued action end is lost");
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            engine.DirectMouseForTest(0x201);
            InputEngine.SendMouse("CtrlDrag:Start");
            engine.DirectMouseForTest(0x201);
            engine.DirectMouseForTest(0x202);
            SpinWait.SpinUntil(() => !InputEngine.HasInjectedInputForTest(), 500);
            Check(!InputEngine.HasInjectedInputForTest() && modifierDragMouse.SequenceEqual([2u, 4u]) && modifierDragKeys.LastOrDefault() == ((ushort)0x11, true), "the next physical left Down recovers a drag after a lost physical Up instead of leaving both clicks blocked");
            plainMouseMappings = true;
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            InputEngine.SendMouse("AltDrag");
            Check(modifierDragKeys.SequenceEqual([((ushort)0x12, false), ((ushort)0x12, true)]) && modifierDragMouse.SequenceEqual(new uint[] { 2, 4 }) && !InputEngine.HasInjectedInputForTest(), "Alt drag single press sends Alt+left click and releases both");
            modifierDragKeys.Clear();
            modifierDragMouse.Clear();
            InputEngine.SendMouse("AltDrag:Start");
            engine.ResetStateForTest();
            Check(!InputEngine.HasInjectedInputForTest() && modifierDragMouse.SequenceEqual(new uint[] { 2, 4 }) && modifierDragKeys.LastOrDefault() == ((ushort)0x12, true), "state reset safely releases an interrupted Alt drag");
            InputEngine.MouseFlagOutputForTest = null;
            InputEngine.KeyOutputForTest = null;
            InputEngine.KeyOutputForTest = (_, _) => true;
            InputEngine.MouseFlagOutputForTest = (_, _) => { };
            foreach (string name in new[] { "A", "Ctrl", "Shift", "Alt", "Win", "Space", "CapsLock" })
                InputEngine.SendRecordedEvent(name + " Down");
            foreach (string name in new[] { "MouseLeft", "MouseRight", "MouseMiddle", "MouseBack", "MouseForward" })
                InputEngine.SendRecordedEvent(name + " Down");
            Check(InputEngine.HasInjectedInputForTest(), "all generated key and mouse button downs are tracked");
            InputEngine.ExpireInjectedInputsForTest();
            Check(!InputEngine.HasInjectedInputForTest(), "stale-input watchdog releases Ctrl, every tracked key, and every mouse button");
            InputEngine.MouseFlagOutputForTest = null;
            int keyUpAttempts = 0;
            InputEngine.KeyOutputForTest = (_, up) => !up || ++keyUpAttempts >= 3;
            InputEngine.SendRecordedEvent("A Down");
            InputEngine.ReleaseAll();
            Check(keyUpAttempts == 3 && !InputEngine.HasInjectedInputForTest(), "failed key-up output is retried until released");
            InputEngine.KeyOutputForTest = null;
            InputEngine.MouseFlagOutputForTest = (_, _) => { };
            MacroPlayer.Play(new MacroDefinition { Name = "incomplete mouse macro", Steps = [new() { Event = "MouseLeft Down" }] });
            await Task.Delay(120);
            Check(!InputEngine.HasInjectedInputForTest(), "macro completion releases an unmatched mouse down");
            InputEngine.MouseFlagOutputForTest = null;
            var invalidMacroResult = await MacroPlayer.PlayAsync(new MacroDefinition { Name = "invalid macro", Steps = [new() { Event = "Unknown Down" }] });
            Check(!invalidMacroResult.Succeeded && !invalidMacroResult.Cancelled && invalidMacroResult.Message.Length > 0, "macro playback reports an invalid step instead of silently failing");
            var recursiveMacro = new MacroDefinition { Name = "recursive macro" };
            recursiveMacro.Steps.Add(new MacroStep { Event = "割り当て: recursive macro", RecordedActionKind = ActionKind.Macro, RecordedActionValue = recursiveMacro.Name });
            var recursiveConfig = new AppConfig { Macros = [recursiveMacro] };
            var recursiveResult = await MacroPlayer.PlayAsync(recursiveMacro, recursiveConfig);
            Check(!recursiveResult.Succeeded && !recursiveResult.Cancelled && recursiveResult.ExecutedSteps <= 2, "recursive macro playback stops safely with a visible failure result");
            var delayedMacro = new MacroDefinition { Name = "cancel macro", Steps = [new() { Event = "Wait", DelayMs = 3000 }] };
            var delayedTask = MacroPlayer.PlayAsync(delayedMacro);
            await Task.Delay(30);
            MacroPlayer.StopAll();
            var cancelledResult = await delayedTask;
            Check(cancelledResult.Cancelled && !InputEngine.HasInjectedInputForTest(), "macro test can be stopped immediately and releases generated input");
            var mouseFlags = new List<uint>();
            InputEngine.MouseFlagOutputForTest = (flag, _) => mouseFlags.Add(flag);
            InputEngine.ReleaseAll();
            Check(mouseFlags.Count == 0, "idle recovery sends no unrelated mouse button-up");
            InputEngine.SendRecordedEvent("MouseRight Down");
            mouseFlags.Clear();
            InputEngine.ReleaseAll();
            Check(mouseFlags.SequenceEqual(new uint[] { 16 }), "recovery releases only the mouse button generated by the app");
            InputEngine.MouseFlagOutputForTest = null;
            rightWheelLayer = true;
            engine.ResetStateForTest();
            events.Clear();
            var started = Environment.TickCount64;
            InputEngine.InjectMouseForTest("Right", false);
            await Task.Delay(100);
            for (int i = 0; i < 50; i++)
            {
                InputEngine.InjectWheelForTest(true);
                await Task.Delay(10);
            }
            await Task.Delay(100);
            InputEngine.InjectMouseForTest("Right", true);
            await Task.Delay(200);
            int wheelEvents = events.Count(x => x == "MouseRight+WheelUp");
            Check(wheelEvents >= 35, $"right-click layer continuous wheel detection under synthetic input ({wheelEvents}/50)");
            int keyOutputCount = 0, mouseOutputCount = 0;
            InputEngine.KeyOutputForTest = (_, _) => { Interlocked.Increment(ref keyOutputCount); return true; };
            InputEngine.MouseFlagOutputForTest = (_, _) => Interlocked.Increment(ref mouseOutputCount);
            started = Environment.TickCount64;
            await Task.Run(() => { for (int i = 0; i < 50; i++) InputEngine.SendShortcut(i % 2 == 0 ? "Ctrl+WheelUp" : "Ctrl+WheelDown"); });
            await Task.Delay(50);
            Check(Environment.TickCount64 - started < 3000 && keyOutputCount == 100 && mouseOutputCount == 50 && !InputEngine.HasInjectedInputForTest(), "continuous Ctrl+wheel output on worker and modifier release");
            InputEngine.KeyOutputForTest = null;
            InputEngine.MouseFlagOutputForTest = null;
            rightWheelLayer = false;
            engine.ResetStateForTest();
            filmoraHomeGestureMode = true;
            events.Clear();
            engine.ResetStateForTest();
            engine.GestureCursorForTest = (100, 100);
            engine.DirectKeyForTest(0x24, false);
            engine.DirectMouseForTest(0x200, 0, 114, 100);
            engine.DirectKeyForTest(0x24, true);
            await Task.Delay(40);
            Check(events.SequenceEqual(["Home:Gesture:Right"]) && !engine.HasCapturedStateForTest(), "Filmora-profile Home gesture executes and releases cleanly");
            filmoraHomeGestureMode = false;
            engine.GestureCursorForTest = null;
            if (!includeRealHook)
                output.WriteLine("SKIP Windows real-hook test: explicitly disabled for this run");
            else
            {
                await ModifierClickScenarioTest.RunAsync(Check);
                engine.EnableDirectTestInput();
                var hookEvents = new List<string>();
                var hookDetected = new List<string>();
                using var hookEngine = new InputEngine
                {
                    ExitOnEmergency = false,
                    TreatF13AsCapsLock = true,
                    HasMapping = input => input is "CapsLock+U" or "CapsLock+*" or "Space+J" or "Space+*" or "MouseRight+WheelUp" or "MouseRight+*",
                    InputReceived = input => { lock (hookEvents) hookEvents.Add(input); return true; }
                };
                hookEngine.Detected += x => hookDetected.Add(x);
                hookEngine.Start();
                await Task.Delay(550);
                Check(hookEngine.RawInputMonitorStartedForTest, "hook thread registers the independent raw mouse release monitor");
                hookEngine.RunHookThreadSequenceForTest();
                await Task.Delay(180);
                Check(hookEvents.Count(x => x == "CapsLock+U") == 2 && hookEvents.Contains("Space+J") && hookEvents.Contains("MouseRight+WheelUp"), "dedicated hook thread keeps delayed CapsLock, Space and mouse layers active until actual release events=[" + string.Join(',', hookEvents) + "] detected=[" + string.Join(',', hookDetected.TakeLast(12)) + "]");
                Check(hookEngine.HookTestStateCleanForTest && !InputEngine.HasInjectedInputForTest(), "hook thread leaves its own layer state and generated input released");
            }
            engine.DirectMouseForTest(0x201);
            await Task.Delay(20);
            engine.DirectKeyForTest(0x11, false);
            engine.DirectKeyForTest(0x12, false);
            engine.DirectKeyForTest(0x10, false);
            engine.DirectKeyForTest(0x7B, false);
            await Task.Delay(50);
            Check(!engine.Enabled, "emergency stop" + (engine.Enabled ? " [" + string.Join(",", detected.TakeLast(8)) + "]" : ""));
            engine.DirectKeyForTest(0x7B, true);
            engine.DirectKeyForTest(0x10, true);
            engine.DirectKeyForTest(0x12, true);
            engine.DirectKeyForTest(0x11, true);
            for (int attempt = 0; attempt < 20 &&
                (InputEngine.IsKeyDownForTest(0x11) || InputEngine.IsKeyDownForTest(0x10) || InputEngine.IsKeyDownForTest(0x12)); attempt++)
                await Task.Delay(25);
            Check(!InputEngine.IsKeyDownForTest(0x11) && !InputEngine.IsKeyDownForTest(0x10) && !InputEngine.IsKeyDownForTest(0x12), "modifier release safety");
            for (int attempt = 0; attempt < 3 && InputEngine.IsKeyDownForTest(0x01); attempt++)
            {
                InputEngine.ReleaseAll();
                await Task.Delay(120);
            }
            Check(!InputEngine.IsKeyDownForTest(0x01), "mouse button release safety");
        }
        catch (Exception ex) { report.RecordException("exception", "FAIL exception: ", ex); }
        finally { InputEngine.MouseClickBatchOutputForTest = null; InputEngine.MouseFlagOutputForTest = null; InputEngine.KeyOutputForTest = null; InputEngine.PhysicalKeyDownForTest = null; InputEngine.UnicodeTextOutputForTest = null; InputEngine.ImeActionOutputForTest = null; InputEngine.ReleaseAll(); }
        return report.Complete("ENGINE INTEGRATION TEST PASSED", "ENGINE INTEGRATION TEST FAILED: ");
    }
}
