namespace RELYR;
using System.IO;
using System.Collections.Concurrent;

public static class EngineIntegrationTest
{
    public static async Task<int> RunAsync(TextWriter output,bool includeRealHook=true)
    {
        var events=new List<string>();var detected=new List<string>();var failures=new List<string>();bool rightWheelLayer=false,allWheelLayers=false,transientMiddleMapped=false,transientKeyMapped=false,spaceMappings=true,multiLayerMappings=false,plainMouseMappings=true;
        void Check(bool value,string name){output.WriteLine((value?"PASS ":"FAIL ")+name);if(!value)failures.Add(name);}
        using var engine=new InputEngine
        {
            ExitOnEmergency=false,
            HasMapping=input=>input=="A"||(spaceMappings&&(input=="Space"||input=="Space+J"||input=="Space+K"||input=="Space+U"||input=="Space+MouseLeft"||input=="Space+*"))||input=="K"||(plainMouseMappings&&(input=="MouseLeft"||input=="MouseRight"))||input=="CapsLock+J"||input=="CapsLock+U"||input=="CapsLock+*"||(transientKeyMapped&&input=="B")||(transientMiddleMapped&&input=="MouseMiddle")||(rightWheelLayer&&(input=="MouseRight+*"||input=="MouseRight+WheelUp"||input=="MouseRight+WheelDown"))||(allWheelLayers&&(input is "MouseRight+*" or "MouseRight+WheelUp" or "MouseRight+WheelDown" or "MouseBack+*" or "MouseBack+WheelUp" or "MouseBack+WheelDown" or "MouseForward+*" or "MouseForward+WheelUp" or "MouseForward+WheelDown"))||(multiLayerMappings&&(input is "MouseLeft+*" or "MouseLeft+J" or "MouseMiddle+*" or "MouseMiddle+J" or "MouseBack+*" or "MouseBack+J" or "MouseForward+*" or "MouseForward+J" or "MouseForward+Up" or "MouseForward+MouseLeft")),
            SuppressLayerTap=key=>key=="CapsLock",
            HasLongPress=input=>input=="K"||input=="MouseRight",
            LongPressDuration=_=>100,
            InputReceived=input=>{lock(events)events.Add(input);return !input.EndsWith(":PressStart",StringComparison.OrdinalIgnoreCase);}
        };
        int repeatCount=0;engine.SpaceHoldRepeatDelayMs=120;engine.SpaceHoldRepeatIntervalMs=40;engine.RepeatOutputForTest=()=>Interlocked.Increment(ref repeatCount);
        engine.DragPixels=50;
        engine.EnableDirectTestInput();
        engine.Detected+=x=>detected.Add(x);
        try
        {
            var forwarded=(IntPtr)0x1234;engine.NextHookForTest=(_,_,_)=>forwarded;Check(engine.DirectMarkedKeyForTest(0x41,false)==forwarded&&engine.DirectMarkedMouseForTest(0x201)==forwarded,"app-generated keyboard and mouse input is forwarded to Windows");engine.NextHookForTest=null;
            InputEngine.InjectKeyForTest("A",false);InputEngine.InjectKeyForTest("A",true);await Task.Delay(50);
            Check(events.Contains("A"),"keyboard hook single press");
            InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(100);
            Check(events.Contains("Space+J"),"Space layer chord ["+string.Join(",",events)+"] detected=["+string.Join(",",detected.TakeLast(6))+"]");
            Check(!events.Contains("Space"),"layer chord suppresses tap action");
            events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("U",false);InputEngine.InjectKeyForTest("U",false);InputEngine.InjectKeyForTest("U",false);InputEngine.InjectKeyForTest("U",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(events.Count(x=>x=="Space+U")==3&&!events.Contains("Space")&&!engine.HasCapturedStateForTest(),"held Space layer key repeats on every key-down without an extra release action");
            events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("K",false);InputEngine.InjectKeyForTest("K",false);InputEngine.InjectKeyForTest("K",false);InputEngine.InjectKeyForTest("K",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(events.Count(x=>x=="Space+K")==3&&!events.Contains("Space")&&!engine.HasCapturedStateForTest(),"held Space+K repeats Enter-style mappings just like every other layer key");
            events.Clear();engine.ResetStateForTest();engine.DirectKeyForTest(0x20,false);engine.DirectKeyForTest(0x55,false);engine.DirectKeyForTest(0x20,true);var repeatAfterLayerUp=engine.DirectKeyForTest(0x55,false);var keyUpAfterLayerUp=engine.DirectKeyForTest(0x55,true);await Task.Delay(40);Check(events.Count(x=>x=="Space+U")==1&&repeatAfterLayerUp==(IntPtr)1&&keyUpAfterLayerUp==(IntPtr)1&&!engine.HasActiveLayerStateForTest(),"releasing Space first stops repeats and suppresses the still-held layer key until key-up");
            events.Clear();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(100);Check(events.Contains("Space"),"layer key single tap");
            events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);await Task.Delay(290);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(events.Contains("Space+J")&&!events.Contains("Space"),"slow Space chord remains a layer after repeat delay");
            events.Clear();repeatCount=0;engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(40);events.Clear();InputEngine.InjectKeyForTest("Space",false);await Task.Delay(290);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(repeatCount>=3&&!events.Contains("Space"),"Space tap then hold starts repeat without disabling layer hold");
            events.Clear();repeatCount=0;engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(40);events.Clear();InputEngine.InjectKeyForTest("Space",false);await Task.Delay(30);InputEngine.InjectKeyForTest("K",false);InputEngine.InjectKeyForTest("K",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(events.Contains("Space+K")&&!events.Contains("Space")&&repeatCount==0,"Space layer chord wins over pending second-hold repeat");
            spaceMappings=false;events.Clear();repeatCount=0;engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(40);InputEngine.InjectKeyForTest("Space",false);await Task.Delay(290);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(repeatCount>=3,"Space tap then hold repeats even when the Space layer has no assignments");spaceMappings=true;
            events.Clear();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectMouseForTest("Left",false);InputEngine.InjectMouseForTest("Left",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(100);Check(events.Contains("Space+MouseLeft")&&!events.Contains("Space"),"layer mouse mapping suppresses tap");
            events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectMouseForTest("Left",false);InputEngine.InjectKeyForTest("Space",true);InputEngine.InjectMouseForTest("Left",true);await Task.Delay(100);Check(events.Contains("Space+MouseLeft")&&!events.Contains("Space"),"layer action completes when layer key is released first");
            engine.TreatF13AsCapsLock=true;events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("F13",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);await Task.Delay(60);Check(events.Count(x=>x=="CapsLock+J")==2&&!events.Contains("CapsLock"),"F13-remapped CapsLock hold repeats multiple layer actions");InputEngine.InjectKeyForTest("F13",true);events.Clear();InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(60);Check(events.Contains("Space+J"),"Space layer works immediately after releasing F13-remapped CapsLock");
            events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("F13",false);await Task.Delay(120);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("F13",true);InputEngine.InjectKeyForTest("Space",false);await Task.Delay(120);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(80);Check(events.Contains("CapsLock+J")&&events.Contains("Space+J"),"layers stay active until their actual key-up event");
            multiLayerMappings=true;rightWheelLayer=true;events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("F13",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("F13",true);InputEngine.InjectKeyForTest("Space",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("Space",true);engine.DirectMouseForTest(0x204);InputEngine.InjectWheelForTest(true);engine.DirectMouseForTest(0x205);engine.DirectMouseForTest(0x20B,1<<16);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x20C,1<<16);engine.DirectMouseForTest(0x20B,2<<16);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x20C,2<<16);InputEngine.InjectKeyForTest("F13",false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);InputEngine.InjectKeyForTest("F13",true);await Task.Delay(120);Check(events.Count(x=>x=="CapsLock+J")==2&&events.Contains("Space+J")&&events.Contains("MouseRight+WheelUp")&&events.Contains("MouseBack+J")&&events.Contains("MouseForward+J"),"all reliable keyboard and mouse layers work sequentially without retaining prior state");events.Clear();engine.ResetStateForTest();engine.DirectMouseForTest(0x20B,2<<16);InputEngine.InjectKeyForTest("Up",false);InputEngine.InjectKeyForTest("Up",true);Check(events.Count(x=>x=="MouseForward+Up")==1,"forward layer confirms a keyboard action once when that key is released");events.Clear();InputEngine.InjectKeyForTest("Up",false);InputEngine.InjectKeyForTest("Up",false);InputEngine.InjectMouseForTest("Left",false);InputEngine.InjectMouseForTest("Left",true);InputEngine.InjectKeyForTest("Up",false);InputEngine.InjectKeyForTest("Up",true);engine.DirectMouseForTest(0x20C,2<<16);Check(events.Count(x=>x=="MouseForward+Up")==0&&events.Count(x=>x=="MouseForward+MouseLeft")==1,"forward layer cancels a still-held Up action when left-click becomes the selected operation");multiLayerMappings=false;rightWheelLayer=false;
            var layerReleaseFlags=new ConcurrentBag<(uint Flag,uint Data)>();InputEngine.MouseFlagOutputForTest=(flag,data)=>layerReleaseFlags.Add((flag,data));multiLayerMappings=true;rightWheelLayer=true;engine.ResetStateForTest();engine.DirectMouseForTest(0x201);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x202);engine.DirectMouseForTest(0x204);InputEngine.InjectWheelForTest(true);engine.DirectMouseForTest(0x205);engine.DirectMouseForTest(0x207);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x208);engine.DirectMouseForTest(0x20B,1<<16);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x20C,1<<16);engine.DirectMouseForTest(0x20B,2<<16);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);engine.DirectMouseForTest(0x20C,2<<16);await Task.Delay(120);Check(layerReleaseFlags.IsEmpty,"used mouse layers never inject an unmatched source-button release");engine.DirectMouseForTest(0x20B,2<<16);engine.ResetStateForTest();await Task.Delay(120);Check(layerReleaseFlags.IsEmpty&&!InputEngine.HasInjectedInputForTest(),"state reset does not invent a forward-button release when no down was injected");InputEngine.MouseFlagOutputForTest=null;multiLayerMappings=false;rightWheelLayer=false;
            var contextClickFlags=new ConcurrentQueue<uint>();var contextClickBatches=new ConcurrentQueue<(uint Flag,uint Data)[]>();InputEngine.MouseFlagOutputForTest=(flag,_)=>contextClickFlags.Enqueue(flag);InputEngine.MouseClickBatchOutputForTest=batch=>contextClickBatches.Enqueue(batch);plainMouseMappings=false;rightWheelLayer=true;engine.ResetStateForTest();engine.DirectMouseForTest(0x204);engine.DirectMouseForTest(0x205);await Task.Delay(120);Check(contextClickBatches.Count==1&&contextClickBatches.Single().SequenceEqual(new[]{(8u,0u),(16u,0u)})&&contextClickFlags.IsEmpty,"unused right-click layer replays one atomic context click without a delayed second event");InputEngine.MouseClickBatchOutputForTest=null;contextClickFlags.Clear();engine.DirectMouseForTest(0x204);InputEngine.InjectWheelForTest(true);engine.DirectMouseForTest(0x205);await Task.Delay(120);Check(contextClickFlags.IsEmpty,"used right-click layer does not inject an unmatched right-button release");InputEngine.MouseFlagOutputForTest=null;plainMouseMappings=true;rightWheelLayer=false;
            var wheelLayerSourceFlags=new ConcurrentQueue<(uint Flag,uint Data)>();InputEngine.MouseFlagOutputForTest=(flag,data)=>wheelLayerSourceFlags.Enqueue((flag,data));allWheelLayers=true;events.Clear();engine.ResetStateForTest();foreach(var layer in new[]{(Name:"MouseRight",Down:0x204,Up:0x205,Data:0),(Name:"MouseBack",Down:0x20B,Up:0x20C,Data:1<<16),(Name:"MouseForward",Down:0x20B,Up:0x20C,Data:2<<16)}){engine.DirectMouseForTest(layer.Down,layer.Data);InputEngine.InjectWheelForTest(true);InputEngine.InjectWheelForTest(false);engine.DirectMouseForTest(layer.Up,layer.Data);}await Task.Delay(120);Check(new[]{"MouseRight","MouseBack","MouseForward"}.All(layer=>events.Contains(layer+"+WheelUp")&&events.Contains(layer+"+WheelDown"))&&wheelLayerSourceFlags.IsEmpty&&!InputEngine.HasInjectedInputForTest(),"right, back and forward wheel layers never replay their source button on release");InputEngine.MouseFlagOutputForTest=null;allWheelLayers=false;
            var sideClickBatches=new ConcurrentQueue<(uint Flag,uint Data)[]>();InputEngine.MouseClickBatchOutputForTest=batch=>sideClickBatches.Enqueue(batch);allWheelLayers=true;engine.ResetStateForTest();engine.DirectMouseForTest(0x20B,1<<16);engine.DirectMouseForTest(0x20C,1<<16);await Task.Delay(60);engine.DirectMouseForTest(0x20B,2<<16);engine.DirectMouseForTest(0x20C,2<<16);await Task.Delay(120);var sideBatches=sideClickBatches.ToArray();Check(sideBatches.Length==2&&sideBatches[0].SequenceEqual(new[]{(0x80u,1u),(0x100u,1u)})&&sideBatches[1].SequenceEqual(new[]{(0x80u,2u),(0x100u,2u)}),"unused back and forward layers replay one complete native click");InputEngine.MouseClickBatchOutputForTest=null;allWheelLayers=false;
            var nativeRightDragFlags=new ConcurrentQueue<uint>();InputEngine.MouseFlagOutputForTest=(flag,_)=>nativeRightDragFlags.Enqueue(flag);engine.NextHookForTest=(_,_,_)=>(IntPtr)0x4567;plainMouseMappings=false;rightWheelLayer=true;engine.DragPixels=5;events.Clear();engine.ResetStateForTest();var nativeRightDown=engine.DirectMouseForTest(0x204,0,100,100);var nativeRightMove=engine.DirectMouseForTest(0x200,0,120,110);var nativeRightWheel=engine.DirectMouseForTest(0x20A,120<<16,120,110);var nativeRightUp=engine.DirectMouseForTest(0x205,0,120,110);await Task.Delay(120);Check(nativeRightDown==(IntPtr)1&&nativeRightMove==(IntPtr)0x4567&&nativeRightWheel==(IntPtr)0x4567&&nativeRightUp==(IntPtr)1&&nativeRightDragFlags.ToArray().SequenceEqual(new uint[]{8,16})&&!events.Any(x=>x.StartsWith("MouseRight+",StringComparison.OrdinalIgnoreCase))&&!InputEngine.HasInjectedInputForTest(),"moving an unused right-click layer becomes a native right-button drag and releases safely");engine.NextHookForTest=null;InputEngine.MouseFlagOutputForTest=null;plainMouseMappings=true;rightWheelLayer=false;engine.DragPixels=50;
            engine.TreatF13AsCapsLock=false;events.Clear();engine.ResetStateForTest();var nativeDown=engine.DirectKeyForTest(0x14,false);InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);var nativeUp=engine.DirectKeyForTest(0x14,true);await Task.Delay(80);Check(nativeDown!=(IntPtr)1&&nativeUp!=(IntPtr)1&&!events.Contains("CapsLock+J"),"native CapsLock is passed through and never starts a layer without F13 remap");
            engine.TreatF13AsCapsLock=true;events.Clear();engine.ResetStateForTest();InputEngine.InjectKeyForTest("F13",false);engine.ExpireLayerForTest();InputEngine.InjectKeyForTest("J",false);InputEngine.InjectKeyForTest("J",true);await Task.Delay(100);Check(!events.Contains("CapsLock+J"),"expired F13-remapped CapsLock layer is recovered before the next input");InputEngine.InjectKeyForTest("F13",true);engine.TreatF13AsCapsLock=false;
            events.Clear();bool capsBefore=System.Windows.Forms.Control.IsKeyLocked(System.Windows.Forms.Keys.CapsLock);engine.ResetStateForTest();InputEngine.InjectKeyForTest("CapsLock",false);InputEngine.InjectKeyForTest("CapsLock",true);await Task.Delay(150);bool capsAfter=System.Windows.Forms.Control.IsKeyLocked(System.Windows.Forms.Keys.CapsLock);Check(capsAfter==capsBefore&&!events.Any(x=>x.StartsWith("CapsLock")),"native CapsLock remains outside the layer state machine");
            InputEngine.InjectKeyForTest("K",false);await Task.Delay(180);InputEngine.InjectKeyForTest("K",true);await Task.Delay(30);
            Check(events.Contains("K:Long")&&!events.Contains("K"),"long press discrimination");
            events.Clear();engine.DragPixels=int.MaxValue;InputEngine.InjectMouseForTest("Left",false);await Task.Delay(30);InputEngine.InjectMouseForTest("Left",true);await Task.Delay(100);
            Check(events.Contains("MouseLeft"),"mouse hook click");
            engine.DragPixels=1;events.Clear();InputEngine.InjectMouseForTest("Left",false);await Task.Delay(20);InputEngine.InjectMouseMoveForTest(20,10);await Task.Delay(100);InputEngine.InjectMouseForTest("Left",true);await Task.Delay(50);
            bool dragStart=events.Any(x=>x.EndsWith("MouseLeft:DragStart",StringComparison.OrdinalIgnoreCase));bool dragEnd=events.Any(x=>x.EndsWith("MouseLeft:DragEnd",StringComparison.OrdinalIgnoreCase));
            Check(dragStart&&dragEnd,"mouse drag discrimination ["+string.Join(",",events)+"]");
            engine.DragPixels=50;events.Clear();for(int attempt=0;attempt<3&&!events.Contains("MouseRight:Long");attempt++){engine.ResetStateForTest();InputEngine.InjectMouseForTest("Right",false);await Task.Delay(350);InputEngine.InjectMouseForTest("Right",true);await Task.Delay(120);}
            Check(events.Contains("MouseRight:Long")&&!events.Contains("MouseRight"),"mouse long press discrimination");
            engine.ResetStateForTest();transientMiddleMapped=false;var plainDown=engine.DirectMouseForTest(0x207);transientMiddleMapped=true;var plainUp=engine.DirectMouseForTest(0x208);Check(plainDown!=(IntPtr)1&&plainUp!=(IntPtr)1,"mapping enabled during click does not swallow physical button-up");
            engine.ResetStateForTest();transientMiddleMapped=true;var mappedDown=engine.DirectMouseForTest(0x207);transientMiddleMapped=false;var mappedUp=engine.DirectMouseForTest(0x208);Check(mappedDown==(IntPtr)1&&mappedUp==(IntPtr)1,"mapping disabled during click preserves down/up handling pair");
            var physicalReleaseFlags=new List<uint>();InputEngine.MouseFlagOutputForTest=(flag,_)=>physicalReleaseFlags.Add(flag);engine.ResetStateForTest();engine.DirectMouseForTest(0x201);engine.DirectMouseForTest(0x202);engine.DirectMouseForTest(0x204);engine.DirectMouseForTest(0x205);Check(physicalReleaseFlags.Count==0&&!InputEngine.HasInjectedInputForTest(),"physical mouse callbacks never inject reentrant button events");InputEngine.MouseFlagOutputForTest=null;
            transientMiddleMapped=true;engine.DirectMouseForTest(0x207);engine.Enabled=false;engine.Enabled=true;var orphanUp=engine.DirectMouseForTest(0x208);Check(orphanUp!=(IntPtr)1,"engine toggle releases click state and passes orphan button-up");transientMiddleMapped=false;
            rightWheelLayer=true;engine.Enabled=false;var disabledRightDown=engine.DirectMouseForTest(0x204);var disabledWheel=engine.DirectMouseForTest(0x20A,120<<16);var disabledRightUp=engine.DirectMouseForTest(0x205);Check(disabledRightDown!=(IntPtr)1&&disabledWheel!=(IntPtr)1&&disabledRightUp!=(IntPtr)1,"disabled engine always passes right-click layers and wheel input through");engine.Enabled=true;rightWheelLayer=false;
            engine.ResetStateForTest();transientKeyMapped=false;var plainKeyDown=engine.DirectKeyForTest(0x42,false);transientKeyMapped=true;var plainKeyUp=engine.DirectKeyForTest(0x42,true);Check(plainKeyDown!=(IntPtr)1&&plainKeyUp!=(IntPtr)1,"mapping enabled during key press does not swallow physical key-up");
            engine.ResetStateForTest();transientKeyMapped=true;var mappedKeyDown=engine.DirectKeyForTest(0x42,false);transientKeyMapped=false;var mappedKeyUp=engine.DirectKeyForTest(0x42,true);Check(mappedKeyDown==(IntPtr)1&&mappedKeyUp==(IntPtr)1,"mapping disabled during key press preserves down/up handling pair");
            var nativeDragOutput=new List<string>();string[] NativeDragSnapshot(){lock(nativeDragOutput)return nativeDragOutput.ToArray();}void ClearNativeDrag(){lock(nativeDragOutput)nativeDragOutput.Clear();}InputEngine.KeyOutputForTest=(key,up)=>{lock(nativeDragOutput)nativeDragOutput.Add($"K:{key}:{(up?"U":"D")}");return true;};InputEngine.MouseFlagOutputForTest=(flag,_)=>{lock(nativeDragOutput)nativeDragOutput.Add("M:"+flag);};var nativeDragQueue=new BlockingCollection<string>();var nativeDragWorker=Task.Factory.StartNew(()=>{foreach(var input in nativeDragQueue.GetConsumingEnumerable())InputEngine.SendMouse(input.EndsWith(":PressStart",StringComparison.OrdinalIgnoreCase)?"CtrlDrag:Start":"CtrlDrag:End");},CancellationToken.None,TaskCreationOptions.LongRunning,TaskScheduler.Default);engine.IsNativeMouseDrag=input=>input=="Space+MouseLeft";engine.InputReceived=input=>{lock(events)events.Add(input);if(input is "Space+MouseLeft:PressStart" or "Space+MouseLeft:PressEnd")return nativeDragQueue.TryAdd(input);return !input.EndsWith(":PressStart",StringComparison.OrdinalIgnoreCase);};engine.DragPixels=1;
            events.Clear();ClearNativeDrag();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);var dragDownResult=engine.DirectMouseForTest(0x201);await Task.Delay(30);bool startedAtPhysicalDown=dragDownResult==(IntPtr)1&&NativeDragSnapshot().SequenceEqual(new[]{"K:17:D","M:2"});InputEngine.InjectMouseMoveForTest(20,10);var dragUpResult=engine.DirectMouseForTest(0x202);InputEngine.InjectKeyForTest("Space",true);await Task.Delay(40);Check(startedAtPhysicalDown&&dragUpResult==(IntPtr)1&&NativeDragSnapshot().SequenceEqual(new[]{"K:17:D","M:2","M:4","K:17:U"})&&events.Count(x=>x=="Space+MouseLeft:PressStart")==1&&events.Count(x=>x=="Space+MouseLeft:PressEnd")==1&&!InputEngine.HasInjectedInputForTest(),"AHK-style Ctrl drag runs off the hook thread and completes after mouse release");
            events.Clear();ClearNativeDrag();engine.ResetStateForTest();InputEngine.InjectKeyForTest("Space",false);dragDownResult=engine.DirectMouseForTest(0x201);await Task.Delay(30);InputEngine.InjectMouseMoveForTest(20,10);InputEngine.InjectKeyForTest("Space",true);bool ctrlHeldUntilMouseUp=NativeDragSnapshot().SequenceEqual(new[]{"K:17:D","M:2"})&&InputEngine.HasInjectedInputForTest();dragUpResult=engine.DirectMouseForTest(0x202);await Task.Delay(40);Check(dragDownResult==(IntPtr)1&&dragUpResult==(IntPtr)1&&ctrlHeldUntilMouseUp&&NativeDragSnapshot().SequenceEqual(new[]{"K:17:D","M:2","M:4","K:17:U"})&&events.Count(x=>x=="Space+MouseLeft:PressStart")==1&&events.Count(x=>x=="Space+MouseLeft:PressEnd")==1&&!InputEngine.HasInjectedInputForTest(),"AHK-style Ctrl drag waits for mouse release when the Space layer is released first");nativeDragQueue.CompleteAdding();await nativeDragWorker;
            engine.IsNativeMouseDrag=null;engine.InputReceived=input=>{lock(events)events.Add(input);return !input.EndsWith(":PressStart",StringComparison.OrdinalIgnoreCase);};engine.DragPixels=50;InputEngine.MouseFlagOutputForTest=null;InputEngine.KeyOutputForTest=null;
            var symbolOutput=new List<(ushort Key,bool Up)>();
            InputEngine.KeyOutputForTest=(key,up)=>{symbolOutput.Add((key,up));return true;};
            InputEngine.NeutralizePhysicalSourceKey("Space+G");
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x47,true)}),"long-press source neutralization releases G before a synthetic Windows chord");
            symbolOutput.Clear();
            InputEngine.SendShortcut("?");
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0xBF,false),((ushort)0xBF,true),((ushort)0x10,true)})&&!InputEngine.HasInjectedInputForTest(),"JIS question mark sends Shift plus slash and releases both");
            symbolOutput.Clear();InputEngine.SendShortcut("!");
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0x31,false),((ushort)0x31,true),((ushort)0x10,true)})&&!InputEngine.HasInjectedInputForTest(),"JIS exclamation sends Shift plus 1 and releases both");
            symbolOutput.Clear();InputEngine.SendShortcut("?",true);
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0xBF,false),((ushort)0xBF,true),((ushort)0x10,true)})&&!InputEngine.HasInjectedInputForTest(),"US question mark sends Shift plus slash and releases both");
            symbolOutput.Clear();InputEngine.SendText("?");
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0xBF,false),((ushort)0xBF,true),((ushort)0x10,true)})&&!InputEngine.HasInjectedInputForTest(),"single-character text uses browser-compatible physical JIS key events");
            symbolOutput.Clear();InputEngine.SendText("A",true);
            Check(symbolOutput.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0x41,false),((ushort)0x41,true),((ushort)0x10,true)})&&!InputEngine.HasInjectedInputForTest(),"uppercase text preserves Shift and releases every generated key");
            symbolOutput.Clear();var unicodeText=new List<string>();InputEngine.UnicodeTextOutputForTest=unicodeText.Add;InputEngine.SendText("日本語");
            Check(unicodeText.SequenceEqual(new[]{"日本語"})&&symbolOutput.Count==0,"multi-character Unicode text stays exact and is emitted as one batch");
            var imeModes=new List<int>();InputEngine.ImeActionOutputForTest=imeModes.Add;InputEngine.SendShortcut("ImeOn");InputEngine.SendShortcut("ImeOff");InputEngine.SendShortcut("ImeToggle");Check(imeModes.SequenceEqual(new[]{1,0,2}),"IME on, off and toggle actions dispatch deterministic states");InputEngine.ImeActionOutputForTest=null;
            InputEngine.UnicodeTextOutputForTest=null;InputEngine.KeyOutputForTest=null;
            var modifierDragKeys=new List<(ushort Key,bool Up)>();var modifierDragMouse=new List<uint>();InputEngine.KeyOutputForTest=(key,up)=>{modifierDragKeys.Add((key,up));return true;};InputEngine.MouseFlagOutputForTest=(flag,_)=>modifierDragMouse.Add(flag);
            InputEngine.SendMouse("ShiftDrag");Check(modifierDragKeys.SequenceEqual(new[]{((ushort)0x10,false),((ushort)0x10,true)})&&modifierDragMouse.SequenceEqual(new uint[]{2,4})&&!InputEngine.HasInjectedInputForTest(),"Shift drag single press sends Shift+left click and releases both");
            modifierDragKeys.Clear();modifierDragMouse.Clear();InputEngine.SendMouse("ShiftDrag:Start");Check(modifierDragKeys.SequenceEqual(new[]{((ushort)0x10,false)})&&modifierDragMouse.SequenceEqual(new uint[]{2})&&InputEngine.HasInjectedInputForTest(),"Shift drag start holds Shift and synthetic left down");InputEngine.SendMouse("ShiftDrag:End");Check(modifierDragKeys.LastOrDefault()==((ushort)0x10,true)&&modifierDragMouse.LastOrDefault()==4&&!InputEngine.HasInjectedInputForTest(),"Shift drag end releases left before Shift");int endedKeyCount=modifierDragKeys.Count,endedMouseCount=modifierDragMouse.Count;InputEngine.SendMouse("ShiftDrag:End");Check(modifierDragKeys.Count==endedKeyCount&&modifierDragMouse.Count==endedMouseCount,"duplicate drag end never injects unrelated releases");
            modifierDragKeys.Clear();modifierDragMouse.Clear();InputEngine.SendMouse("CtrlDrag");Check(modifierDragKeys.SequenceEqual(new[]{((ushort)0x11,false),((ushort)0x11,true)})&&modifierDragMouse.SequenceEqual(new uint[]{2,4})&&!InputEngine.HasInjectedInputForTest(),"Ctrl drag single press sends Ctrl+left click and releases both");InputEngine.SendMouse("CtrlDrag:Start");engine.ResetStateForTest();Check(!InputEngine.HasInjectedInputForTest()&&modifierDragMouse.SequenceEqual(new uint[]{2,4,2,4})&&modifierDragKeys.LastOrDefault()==((ushort)0x11,true),"state reset safely releases an interrupted Ctrl drag");modifierDragKeys.Clear();modifierDragMouse.Clear();InputEngine.PhysicalKeyDownForTest=_=>false;InputEngine.SendMouse("CtrlDrag:Start");await Task.Delay(220);Check(!InputEngine.HasInjectedInputForTest()&&modifierDragMouse.LastOrDefault()==4&&modifierDragKeys.LastOrDefault()==((ushort)0x11,true),"physical mouse release watchdog ends Ctrl drag even when its hook end event is lost");InputEngine.PhysicalKeyDownForTest=null;InputEngine.MouseFlagOutputForTest=null;InputEngine.KeyOutputForTest=null;
            InputEngine.KeyOutputForTest=(_,_)=>true;InputEngine.MouseFlagOutputForTest=(_,_)=>{};foreach(string name in new[]{"A","Ctrl","Shift","Alt","Win","Space","CapsLock"})InputEngine.SendRecordedEvent(name+" Down");foreach(string name in new[]{"MouseLeft","MouseRight","MouseMiddle","MouseBack","MouseForward"})InputEngine.SendRecordedEvent(name+" Down");Check(InputEngine.HasInjectedInputForTest(),"all generated key and mouse button downs are tracked");InputEngine.ExpireInjectedInputsForTest();Check(!InputEngine.HasInjectedInputForTest(),"stale-input watchdog releases Ctrl, every tracked key, and every mouse button");InputEngine.MouseFlagOutputForTest=null;int keyUpAttempts=0;InputEngine.KeyOutputForTest=(_,up)=>!up||++keyUpAttempts>=3;InputEngine.SendRecordedEvent("A Down");InputEngine.ReleaseAll();Check(keyUpAttempts==3&&!InputEngine.HasInjectedInputForTest(),"failed key-up output is retried until released");InputEngine.KeyOutputForTest=null;
            InputEngine.MouseFlagOutputForTest=(_,_)=>{};MacroPlayer.Play(new MacroDefinition{Name="incomplete mouse macro",Steps=[new(){Event="MouseLeft Down"}]});await Task.Delay(120);Check(!InputEngine.HasInjectedInputForTest(),"macro completion releases an unmatched mouse down");InputEngine.MouseFlagOutputForTest=null;
            var invalidMacroResult=await MacroPlayer.PlayAsync(new MacroDefinition{Name="invalid macro",Steps=[new(){Event="Unknown Down"}]});Check(!invalidMacroResult.Succeeded&&!invalidMacroResult.Cancelled&&invalidMacroResult.Message.Length>0,"macro playback reports an invalid step instead of silently failing");
            var recursiveMacro=new MacroDefinition{Name="recursive macro"};recursiveMacro.Steps.Add(new MacroStep{Event="割り当て: recursive macro",RecordedActionKind=ActionKind.Macro,RecordedActionValue=recursiveMacro.Name});var recursiveConfig=new AppConfig{Macros=[recursiveMacro]};var recursiveResult=await MacroPlayer.PlayAsync(recursiveMacro,recursiveConfig);Check(!recursiveResult.Succeeded&&!recursiveResult.Cancelled&&recursiveResult.ExecutedSteps<=2,"recursive macro playback stops safely with a visible failure result");
            var delayedMacro=new MacroDefinition{Name="cancel macro",Steps=[new(){Event="Wait",DelayMs=3000}]};var delayedTask=MacroPlayer.PlayAsync(delayedMacro);await Task.Delay(30);MacroPlayer.StopAll();var cancelledResult=await delayedTask;Check(cancelledResult.Cancelled&&!InputEngine.HasInjectedInputForTest(),"macro test can be stopped immediately and releases generated input");
            var mouseFlags=new List<uint>();InputEngine.MouseFlagOutputForTest=(flag,_)=>mouseFlags.Add(flag);InputEngine.ReleaseAll();Check(mouseFlags.Count==0,"idle recovery sends no unrelated mouse button-up");InputEngine.SendRecordedEvent("MouseRight Down");mouseFlags.Clear();InputEngine.ReleaseAll();Check(mouseFlags.SequenceEqual(new uint[]{16}),"recovery releases only the mouse button generated by the app");InputEngine.MouseFlagOutputForTest=null;
            rightWheelLayer=true;engine.ResetStateForTest();events.Clear();var started=Environment.TickCount64;InputEngine.InjectMouseForTest("Right",false);await Task.Delay(100);for(int i=0;i<50;i++){InputEngine.InjectWheelForTest(true);await Task.Delay(10);}await Task.Delay(100);InputEngine.InjectMouseForTest("Right",true);await Task.Delay(200);int wheelEvents=events.Count(x=>x=="MouseRight+WheelUp");Check(wheelEvents>=35,$"right-click layer continuous wheel detection under synthetic input ({wheelEvents}/50)");
            int keyOutputCount=0,mouseOutputCount=0;InputEngine.KeyOutputForTest=(_,_)=>{Interlocked.Increment(ref keyOutputCount);return true;};InputEngine.MouseFlagOutputForTest=(_,_)=>Interlocked.Increment(ref mouseOutputCount);started=Environment.TickCount64;await Task.Run(()=>{for(int i=0;i<50;i++)InputEngine.SendShortcut(i%2==0?"Ctrl+WheelUp":"Ctrl+WheelDown");});await Task.Delay(50);Check(Environment.TickCount64-started<3000&&keyOutputCount==100&&mouseOutputCount==50&&!InputEngine.HasInjectedInputForTest(),"continuous Ctrl+wheel output on worker and modifier release");InputEngine.KeyOutputForTest=null;InputEngine.MouseFlagOutputForTest=null;rightWheelLayer=false;engine.ResetStateForTest();
            if(!includeRealHook)output.WriteLine("SKIP Windows real-hook test: explicitly disabled for this run");
            else
            {
                var hookEvents=new List<string>();var hookDetected=new List<string>();
                using var hookEngine=new InputEngine
                {
                    ExitOnEmergency=false,TreatF13AsCapsLock=true,
                    HasMapping=input=>input is "CapsLock+U" or "CapsLock+*" or "Space+J" or "Space+*" or "MouseRight+WheelUp" or "MouseRight+*",
                    InputReceived=input=>{lock(hookEvents)hookEvents.Add(input);return true;}
                };
                hookEngine.Detected+=x=>hookDetected.Add(x);hookEngine.Start();await Task.Delay(550);hookEngine.RunHookThreadSequenceForTest();await Task.Delay(180);
                Check(hookEvents.Count(x=>x=="CapsLock+U")==2&&hookEvents.Contains("Space+J")&&hookEvents.Contains("MouseRight+WheelUp"),"dedicated hook thread keeps delayed CapsLock, Space and mouse layers active until actual release events=["+string.Join(',',hookEvents)+"] detected=["+string.Join(',',hookDetected.TakeLast(12))+"]");
                Check(hookEngine.HookTestStateCleanForTest&&!InputEngine.HasInjectedInputForTest(),"hook thread leaves its own layer state and generated input released");
            }
            InputEngine.InjectMouseForTest("Left",false);await Task.Delay(20);
            InputEngine.InjectKeyForTest("Ctrl",false);InputEngine.InjectKeyForTest("Alt",false);InputEngine.InjectKeyForTest("Shift",false);InputEngine.InjectKeyForTest("F12",false);await Task.Delay(50);
            Check(!engine.Enabled,"emergency stop"+(engine.Enabled?" ["+string.Join(",",detected.TakeLast(8))+"]":""));
            InputEngine.InjectKeyForTest("F12",true);InputEngine.InjectKeyForTest("Shift",true);InputEngine.InjectKeyForTest("Alt",true);InputEngine.InjectKeyForTest("Ctrl",true);
            await Task.Delay(50);Check(!InputEngine.IsKeyDownForTest(0x11)&&!InputEngine.IsKeyDownForTest(0x10)&&!InputEngine.IsKeyDownForTest(0x12),"modifier release safety");
            for(int attempt=0;attempt<3&&InputEngine.IsKeyDownForTest(0x01);attempt++){InputEngine.ReleaseAll();await Task.Delay(120);}
            Check(!InputEngine.IsKeyDownForTest(0x01),"mouse button release safety");
        }
        catch(Exception ex){output.WriteLine("FAIL exception: "+ex);failures.Add("exception");}
        finally{InputEngine.MouseClickBatchOutputForTest=null;InputEngine.MouseFlagOutputForTest=null;InputEngine.KeyOutputForTest=null;InputEngine.PhysicalKeyDownForTest=null;InputEngine.UnicodeTextOutputForTest=null;InputEngine.ImeActionOutputForTest=null;InputEngine.ReleaseAll();}
        output.WriteLine(failures.Count==0?"ENGINE INTEGRATION TEST PASSED":"ENGINE INTEGRATION TEST FAILED: "+string.Join(", ",failures));
        return failures.Count==0?0:1;
    }
}
