namespace RELYR;
using System.IO;
using System.Text.Json;

public static class SelfTest
{
    public static int Run(TextWriter output)
    {
        var failures=new List<string>();
        void Check(bool value,string name){if(value)output.WriteLine("PASS "+name);else{output.WriteLine("FAIL "+name);failures.Add(name);}}
        string dir=Path.Combine(Path.GetTempPath(),"RELYR-SelfTest-"+Guid.NewGuid().ToString("N"));
        try
        {
            var service=new ConfigService(dir);var config=service.Load();
            string oldData=Path.Combine(dir,"old-appdata"),newData=Path.Combine(dir,"new-appdata");var oldService=new ConfigService(oldData);oldService.Save(new AppConfig{AutoSave=true,Profiles=[new Profile{Name="移行テスト"}]});Check(ConfigService.MigrateLegacyDirectory(oldData,newData)&&!Directory.Exists(oldData)&&new ConfigService(newData).Load().Profiles[0].Name=="移行テスト","legacy settings move to the RELYR AppData folder without data loss");
            Directory.CreateDirectory(oldData);Directory.CreateDirectory(newData);File.WriteAllText(Path.Combine(oldData,"old.json"),"{}");File.WriteAllText(Path.Combine(newData,"settings.json"),"{}");Check(ConfigService.DeleteUserDataDirectories(oldData,newData)&&!Directory.Exists(oldData)&&!Directory.Exists(newData),"complete uninstall removes both current and legacy AppData settings folders");
            Check(config.Profiles.Count==1&&config.Profiles[0].Name=="標準"&&config.Profiles[0].Mappings.Count==0,"only standard profile exists by default");
            byte[] legacyMap=[0,0,0,0,0,0,0,0,3,0,0,0,0x64,0,0x3A,0,0x0C,0,0x79,0,0,0,0,0];Check(LegacyKeyRemapService.ContainsCapsLockToF13(legacyMap),"legacy CapsLock-to-F13 registry mapping detection");
            var remapRemoved=LegacyKeyRemapService.UpdateCapsLockToF13(legacyMap,false);var remapRestored=LegacyKeyRemapService.UpdateCapsLockToF13(remapRemoved,true);Check(!LegacyKeyRemapService.ContainsCapsLockToF13(remapRemoved)&&BitConverter.ToUInt32(remapRemoved,12)==0x0079000C&&LegacyKeyRemapService.ContainsCapsLockToF13(remapRestored),"CapsLock F13 setting preserves unrelated registry remaps and can be restored");
            string legacyDir=Path.Combine(dir,"legacy-v7");var legacyService=new ConfigService(legacyDir);legacyService.Save(new AppConfig{Version=7,EngineEnabled=false});var repairedLegacy=legacyService.Load();using var repairedDocument=JsonDocument.Parse(File.ReadAllText(legacyService.FilePath));Check(repairedLegacy.Version==15&&repairedLegacy.EngineEnabled&&repairedDocument.RootElement.GetProperty("Version").GetInt32()==15&&repairedDocument.RootElement.GetProperty("EngineEnabled").GetBoolean(),"v7 reboot-disabled engine is repaired and persistently migrated once");
            string staleLongDir=Path.Combine(dir,"legacy-long-value");var staleLongService=new ConfigService(staleLongDir);staleLongService.Save(new AppConfig{Version=8,Profiles=[new Profile{Mappings=[new Mapping{Input="Space+K",Kind=ActionKind.Key,Value="Enter",LongPressKind=ActionKind.None,LongPressValue="q"},new Mapping{Input="Space+L",Kind=ActionKind.Key,Value="Right",LongPressKind=ActionKind.Launch,LongPressValue="app.exe"}]}]});var migratedLong=staleLongService.Load();Check(migratedLong.Version==15&&migratedLong.Profiles[0].Mappings[0].LongPressValue==""&&migratedLong.Profiles[0].Mappings[1].LongPressValue=="app.exe","stale disabled long-press values are removed without changing explicit long actions");
            var pendingCaps=new AppConfig{CapsLockRemapPendingRestart=true,CapsLockRemapChangedAtUtcTicks=DateTime.UtcNow.AddMinutes(-1).Ticks};Check(LegacyKeyRemapService.IsRestartStillPending(pendingCaps,DateTime.UtcNow,(long)TimeSpan.FromHours(1).TotalMilliseconds)&&!LegacyKeyRemapService.IsRestartStillPending(pendingCaps,DateTime.UtcNow,(long)TimeSpan.FromSeconds(10).TotalMilliseconds),"CapsLock remap distinguishes the current boot from a completed restart");
            Check(!App.UninstallRestartNeeded(new AppConfig(),false,false)&&App.UninstallRestartNeeded(new AppConfig(),true,false)&&!App.UninstallRestartNeeded(new AppConfig{CapsLockLayerEnabled=true},false,false)&&App.UninstallRestartNeeded(new AppConfig(),false,true),"normal updates and a saved CapsLock preference do not request a restart; only an active or pending system remap does");
            Check(config.Profiles.SelectMany(p=>p.Mappings).All(m=>!m.Input.StartsWith("F13",StringComparison.OrdinalIgnoreCase)&&!m.Layer.Equals("F13",StringComparison.OrdinalIgnoreCase)),"F13 layer settings migrate to CapsLock");
            config.Macros.Add(new MacroDefinition{Name="テストマクロ",Steps=[new(){Event="A Down",DelayMs=100},new(){Event="A Up",DelayMs=25},new(){Event="Wait",DelayMs=500},new(){Event="割り当て: Win+Left",RecordedActionKind=ActionKind.Shortcut,RecordedActionValue="Win+Left"}]});
            Check(ConfigValidator.Validate(config).Count==0,"default config validation");
            var blankAction=service.Clone(config);blankAction.Profiles[0].Mappings.Add(new Mapping{Input="Q",Kind=ActionKind.Shortcut,Value=""});Check(ConfigValidator.Validate(blankAction).Count==0,"blank execution value can be left unfinished without a validation error");
            Check(!MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.None,Value="stale",Enabled=true})&&!MainWindow.MappingInterceptsInput(new Mapping{Input="M",Kind=ActionKind.Shortcut,Value="",Enabled=true})&&MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.Disabled,Enabled=true})&&MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.None,LongPressKind=ActionKind.Key,LongPressValue="Enter",Enabled=true}),"unfinished mappings do not look assigned or block native input while disabled and long-only mappings still intercept");
            Check(MainWindow.ShouldFocusExecutionForSelectedInput(null)&&!MainWindow.ShouldFocusExecutionForSelectedInput(new Mapping{Input="A",Kind=ActionKind.Key,Value="B"}),"only an unassigned key automatically focuses the execution-value editor");
            var hoverMapping=new Mapping{Input="Space+K",Enabled=true,Kind=ActionKind.Shortcut,Value="Ctrl+C",LongPressKind=ActionKind.Launch,LongPressValue=@"C:\Apps\Sample.exe",LongPressMs=600};string? hoverText=MainWindow.AssignmentToolTipText(hoverMapping);Check(MainWindow.AssignmentToolTipText(null)==null&&hoverText?.Contains("アクション：ショートカット")==true&&hoverText.Contains("実行内容：")&&hoverText.Contains("長押し（600 ms）")&&hoverText.Contains("アクション：アプリ・ファイル・URL")&&hoverText.Contains(@"C:\Apps\Sample.exe"),"assigned keyboard hover shows short and long actions while unassigned keys show no popup");
            Check(MainWindow.DisplayInputName("MouseRight+K")=="右クリック + K"&&MainWindow.DisplayInputName("Taskbar+MouseMiddle")=="タスクバー上 + ホイールクリック"&&MainWindow.DisplayInputName("MouseBack+WheelUp")=="戻る + ホイール上","internal layer names are presented as beginner-friendly input names");
            config.Profiles.Add(new Profile{Name="アプリ用",AutoSwitchEnabled=true,AutoSwitchApplications=["notepad.exe"]});config.ActiveProfile="アプリ用";config.ShowDesktopNumberInTray=true;config.CloseWindowUnderCursor=true;config.CheckForUpdates=false;config.ThemeMode=AppThemeMode.Light;config.LastUpdateCheckUtcTicks=DateTimeOffset.UtcNow.UtcTicks;config.RecordKeyboardInputInMacros=false;config.RecordMappedActionsInMacros=true;config.RecordMouseMovementInMacros=true;config.RecordMouseMovementRelativeInMacros=false;config.ArchiveWatchFolder=@"C:\Watch";config.ArchiveDestinationFolder=@"D:\Extracted";config.AutoSave=true;config.KeyboardLayout="US";config.SpaceHoldRepeatEnabled=true;config.SpaceHoldRepeatDelayMs=450;service.Save(config);var loaded=service.Load();
            Check(loaded.ActiveProfile=="アプリ用","JSON roundtrip");
            Check(loaded.ShowDesktopNumberInTray,"tray desktop number setting roundtrip");
            Check(loaded.CloseWindowUnderCursor,"cursor-window close target setting roundtrip");
            Check(!loaded.CheckForUpdates,"update-check setting roundtrip");
            Check(loaded.ThemeMode==AppThemeMode.Light&&loaded.LastUpdateCheckUtcTicks==config.LastUpdateCheckUtcTicks,"theme mode and last update check roundtrip");
            Check(!loaded.RecordKeyboardInputInMacros,"macro keyboard recording option roundtrip");
            Check(loaded.RecordMappedActionsInMacros,"macro mapped-action recording option roundtrip");
            Check(loaded.RecordMouseMovementInMacros,"macro mouse trajectory option roundtrip");
            Check(!loaded.RecordMouseMovementRelativeInMacros,"macro mouse fixed/relative movement mode roundtrip");
            Check(loaded.ArchiveWatchFolder==@"C:\Watch"&&loaded.ArchiveDestinationFolder==@"D:\Extracted","archive watch and destination folders roundtrip");
            Check(loaded.AutoSave,"auto-save setting roundtrip");
            Check(loaded.KeyboardLayout=="US","keyboard layout setting roundtrip");
            Check(loaded.SpaceHoldRepeatEnabled&&loaded.SpaceHoldRepeatDelayMs==450,"Space hold repeat setting roundtrip");
            Check(loaded.Profiles[1].AutoSwitchEnabled&&loaded.Profiles[1].AutoSwitchApplications.Contains("notepad.exe"),"profile application auto-switch roundtrip");
            const string releaseJson="""{"tag_name":"v0.1.69","draft":false,"prerelease":false,"assets":[{"name":"RELYR-Setup-0.1.69.exe","state":"uploaded","browser_download_url":"https://github.com/zitan-source/RELYR/releases/download/v0.1.69/RELYR-Setup-0.1.69.exe","digest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},{"name":"RELYR-Setup-0.1.69.exe.sha256","state":"uploaded","browser_download_url":"https://github.com/zitan-source/RELYR/releases/download/v0.1.69/RELYR-Setup-0.1.69.exe.sha256"}]}""";
            var availableUpdate=UpdateService.ParseLatestRelease(releaseJson,new Version(0,1,68));var latestVersion=UpdateService.ParseLatestVersion(releaseJson);Check(availableUpdate is {VersionText:"0.1.69"}&&availableUpdate.InstallerFileName=="RELYR-Setup-0.1.69.exe"&&UpdateService.ParseLatestRelease(releaseJson,new Version(0,1,69))==null&&latestVersion.Version==new Version(0,1,69)&&latestVersion.VersionText=="0.1.69","GitHub release parser accepts only a newer trusted installer with its checksum and reports the latest version");
            string friendlyUpdateError=UpdateService.FriendlyError(new System.Net.Http.HttpRequestException("secret raw details"));Check(friendlyUpdateError.Contains("接続")&&!friendlyUpdateError.Contains("secret raw details"),"update errors are translated into a beginner-friendly message without raw exception details");
            var updateNow=new DateTimeOffset(2026,7,18,12,0,0,TimeSpan.Zero);Check(MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,0)&&!MainWindow.IsAutomaticUpdateCheckDue(updateNow,updateNow.AddHours(-23),0)&&MainWindow.IsAutomaticUpdateCheckDue(updateNow,updateNow.AddHours(-24),0),"automatic update checks run on first display and then at most once per day");Check(!MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,updateNow.AddHours(-23).UtcTicks)&&MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,updateNow.AddHours(-25).UtcTicks),"persisted successful update checks also enforce the one-day interval");
            Check(loaded.Macros.Any(x=>x.Name=="テストマクロ"&&x.Steps.Count==4&&x.Steps.Last().RecordedActionKind==ActionKind.Shortcut&&x.Steps.Last().RecordedActionValue=="Win+Left"&&!string.IsNullOrWhiteSpace(x.Id)),"macro JSON roundtrip with stable identity and mapped action");
            string macroArguments=ShortcutService.BuildMacroArguments("日本語 マクロ");var macroArgumentParts=macroArguments.Split(' ',2);Check(ShortcutService.TryReadMacroName(macroArgumentParts,out string shortcutMacro)&&shortcutMacro=="日本語 マクロ","legacy macro shortcut arguments preserve the exact macro name");string shortcutDirectory=Path.Combine(dir,"shortcuts");var shortcutDefinition=new MacroDefinition{Name="日本語 マクロ"};string shortcutPath=ShortcutService.CreateMacroShortcut(shortcutDefinition,shortcutDirectory,Environment.ProcessPath);var idArgumentParts=ShortcutService.BuildMacroIdArguments(shortcutDefinition.Id).Split(' ',2);Check(File.Exists(shortcutPath)&&ShortcutService.TryReadMacroId(idArgumentParts,out string shortcutMacroId)&&shortcutMacroId==shortcutDefinition.Id,"macro desktop shortcut uses stable identity");string oldShortcut=ShortcutService.CreateMacroShortcut("変更前",shortcutDirectory,Environment.ProcessPath);shortcutDefinition.Name="変更後";string? renamedShortcut=ShortcutService.MigrateRenamedMacroShortcut("変更前",shortcutDefinition,shortcutDirectory,Environment.ProcessPath);Check(!File.Exists(oldShortcut)&&renamedShortcut!=null&&File.Exists(renamedShortcut),"renaming a macro migrates its existing desktop shortcut");var legacyShortcutMacro=new MacroDefinition{Name="旧ショートカット"};string legacyShortcutPath=Path.Combine(shortcutDirectory,"旧ショートカット - Input Customizer.lnk");File.WriteAllText(legacyShortcutPath,"");string? upgradedLegacyShortcut=ShortcutService.UpgradeExistingMacroShortcut(legacyShortcutMacro,shortcutDirectory,Environment.ProcessPath);Check(!File.Exists(legacyShortcutPath)&&upgradedLegacyShortcut!=null&&File.Exists(upgradedLegacyShortcut)&&Path.GetFileName(upgradedLegacyShortcut).EndsWith(" - RELYR.lnk"),"legacy product-name macro shortcuts are replaced by RELYR shortcuts");
            string archiveTests=Path.Combine(dir,"archives");Directory.CreateDirectory(archiveTests);string archiveSource=Path.Combine(archiveTests,"source");Directory.CreateDirectory(archiveSource);File.WriteAllText(Path.Combine(archiveSource,"hello.txt"),"RELYR archive test");
            string zipPath=Path.Combine(archiveTests,"sample.zip");System.IO.Compression.ZipFile.CreateFromDirectory(archiveSource,zipPath);string zipOutput=ArchiveWatcher.ExtractArchive(zipPath);Check(File.ReadAllText(Path.Combine(zipOutput,"hello.txt"))=="RELYR archive test","ZIP extraction works with real archive");
            string tarGzPath=Path.Combine(archiveTests,"sample-tar.tar.gz");using(var compressedOutput=File.Create(tarGzPath))using(var gzip=new System.IO.Compression.GZipStream(compressedOutput,System.IO.Compression.CompressionLevel.SmallestSize))using(var tar=new System.Formats.Tar.TarWriter(gzip,leaveOpen:false))tar.WriteEntry(Path.Combine(archiveSource,"hello.txt"),"folder/hello.txt");string tarOutput=ArchiveWatcher.ExtractArchive(tarGzPath);Check(File.ReadAllText(Path.Combine(tarOutput,"folder","hello.txt"))=="RELYR archive test","TAR.GZ extraction works with real archive");
            string sevenPath=Path.Combine(archiveTests,"sample.7z");using(var seven=System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("tar.exe",$"-a -cf \"{sevenPath}\" -C \"{archiveSource}\" .") {UseShellExecute=false,CreateNoWindow=true}))seven?.WaitForExit(10000);bool sevenOk=File.Exists(sevenPath);if(sevenOk){string sevenOutput=ArchiveWatcher.ExtractArchive(sevenPath);sevenOk=File.Exists(Path.Combine(sevenOutput,"hello.txt"));}Check(sevenOk,"7Z extraction works with real archive");
            string unsafeZip=Path.Combine(archiveTests,"unsafe.zip");using(var file=File.Create(unsafeZip))using(var zip=new System.IO.Compression.ZipArchive(file,System.IO.Compression.ZipArchiveMode.Create))using(var writer=new StreamWriter(zip.CreateEntry("../outside.txt").Open()))writer.Write("blocked");bool traversalBlocked=false;try{ArchiveWatcher.ExtractArchive(unsafeZip);}catch(InvalidDataException){traversalBlocked=true;}Check(traversalBlocked&&!File.Exists(Path.Combine(archiveTests,"outside.txt")),"archive path traversal is blocked");
            string watchedDesktop=Path.Combine(archiveTests,"desktop"),watchedOutput=Path.Combine(archiveTests,"output");Directory.CreateDirectory(watchedDesktop);Directory.CreateDirectory(watchedOutput);using(var extracted=new ManualResetEventSlim())using(var watcher=new ArchiveWatcher(watchedDesktop)){watcher.Status+=message=>{if(message.StartsWith("自動解凍しました"))extracted.Set();};watcher.Apply(new AppConfig{AutoExtractDesktopArchives=true,ArchiveDestinationFolder=watchedOutput});string watchedZip=Path.Combine(watchedDesktop,"watched.zip");System.IO.Compression.ZipFile.CreateFromDirectory(archiveSource,watchedZip);bool watcherDone=extracted.Wait(8000);Check(watcherDone&&File.Exists(Path.Combine(watchedOutput,"watched","hello.txt")),"custom watch folder automatically extracts into the selected destination folder");}
            service.Save(loaded);Check(Directory.GetFiles(dir,"*.bak.json").Length>=1,"automatic backup");
            for(int i=0;i<25;i++){loaded.DoubleClickMs=300+i;service.Save(loaded);}
            Check(Directory.GetFiles(dir,"*.bak.json").Length==20,"20 generation backup retention");
            Check(!File.Exists(service.FilePath+".tmp"),"atomic save cleanup");
            string exported=Path.Combine(dir,SettingsWindow.ExportFileName);service.Export(loaded,exported);var imported=service.Import(exported);string legacyExport=Path.Combine(dir,"legacy-settings.json");service.Export(loaded,legacyExport);var importedLegacy=service.Import(legacyExport);Check(Path.GetExtension(exported)==".relyr"&&SettingsWindow.ExportFileFilter.Contains("*.relyr")&&SettingsWindow.ImportFileFilter.Contains("*.json")&&imported.Profiles.Count==loaded.Profiles.Count&&imported.Macros.Count==loaded.Macros.Count&&importedLegacy.Profiles.Count==loaded.Profiles.Count,"dedicated RELYR settings file export and legacy JSON import");
            string resetDir=Path.Combine(dir,"reset");var resetService=new ConfigService(resetDir);resetService.Save(new AppConfig{ActiveProfile="カスタム",StartWithWindows=true,CapsLockLayerEnabled=true,Macros=[new MacroDefinition()],Profiles=[new Profile{Name="カスタム",Mappings=[new Mapping{Input="A",Kind=ActionKind.Key,Value="B"}]}]});var reset=resetService.ResetToDefaults();Check(reset.FirstRunCompleted&&!reset.StartWithWindows&&!reset.CapsLockLayerEnabled&&reset.Macros.Count==0&&reset.Profiles.Count==1&&reset.Profiles[0].Name=="標準"&&reset.Profiles[0].Mappings.Count==0,"all-settings reset returns every profile, layer assignment, macro and app option to defaults");
            var missingMacro=service.Clone(loaded);missingMacro.Profiles[0].Mappings.Add(new Mapping{Input="Q",Kind=ActionKind.Macro,Value="存在しないマクロ"});Check(ConfigValidator.Validate(missingMacro).Any(x=>x.Contains("マクロ「存在しないマクロ」")),"missing macro validation");
            var missingProfile=service.Clone(loaded);missingProfile.Profiles[0].Mappings.Add(new Mapping{Input="W",Kind=ActionKind.Profile,Value="存在しないプロファイル"});Check(ConfigValidator.Validate(missingProfile).Any(x=>x.Contains("プロファイル「存在しないプロファイル」")),"missing profile validation");
            loaded.Profiles[0].Mappings.Add(new Mapping{Input="A",Kind=ActionKind.Key,Value="B"});
            loaded.Profiles[0].Mappings.Add(new Mapping{Input="A",Kind=ActionKind.Key,Value="C"});
            Check(ConfigValidator.Validate(loaded).Any(x=>x.Contains("競合")),"conflict detection");
            Check(InputEngineSmokeTest(),"input engine construct/dispose");
            TestMappingActions(Check);
            Check(ConditionMatcher.Matches("notepad.exe","NOTEPAD"),"application condition matching");
            var autoProfiles=new[]{new Profile{Name="標準"},new Profile{Name="メモ帳",AutoSwitchEnabled=true,AutoSwitchApplications=["notepad.exe"]}};Check(MainWindow.SelectAutomaticProfile(autoProfiles,"notepad").Name=="メモ帳"&&MainWindow.SelectAutomaticProfile(autoProfiles,"explorer").Name=="標準","cursor application profile selection");Check(MainWindow.IsOwnProcess("RELYR",@"C:\Program Files\RELYR\RELYR.exe")&&!MainWindow.IsOwnProcess("chrome",@"C:\Program Files\RELYR\RELYR.exe"),"profile auto-switch ignores the RELYR settings window");
            var baseMapping=new Mapping{Input="CapsLock+U",Kind=ActionKind.Key,Value="Enter",Enabled=true};var overrideMapping=new Mapping{Input="A",Kind=ActionKind.Key,Value="B",Enabled=true};var inheritedProfiles=new[]{new Profile{Name="標準",Mappings=[baseMapping]},new Profile{Name="Chrome",Mappings=[overrideMapping]}};Check(ReferenceEquals(MainWindow.FindProfileMapping(inheritedProfiles,"Chrome","CapsLock+U",x=>x.Enabled),baseMapping)&&ReferenceEquals(MainWindow.FindProfileMapping(inheritedProfiles,"Chrome","A",x=>x.Enabled),overrideMapping),"application profiles override locally and inherit missing standard mappings");
            Check(!ConditionMatcher.Matches("notepad.exe","excel"),"application condition rejection");
            Check(ConditionMatcher.IsTaskbarClass("Shell_TrayWnd")&&ConditionMatcher.IsTaskbarClass("Shell_SecondaryTrayWnd"),"taskbar class detection");
            Check(ActionCatalog.Items.Any(x=>x.Name=="コピー"&&x.Value=="Ctrl+C"),"action catalog copy preset");
            Check(ActionCatalog.Items.Select(x=>x.MajorCategory).Distinct().Count()>=8&&ActionCatalog.Search("キャッシュ").Any(x=>x.Name=="キャッシュを無視して更新"),"action catalog has major categories and searchable content");
            Check(new[]{"ImeOn","ImeOff","ImeToggle"}.All(value=>ActionCatalog.Items.Any(x=>x.Category=="IME・日本語入力"&&x.Value==value))&&InputEngine.TryGetImeAction("ImeOn",out int imeOn)&&imeOn==1&&InputEngine.TryGetImeAction("ImeOff",out int imeOff)&&imeOff==0&&InputEngine.TryGetImeAction("ImeToggle",out int imeToggle)&&imeToggle==2,"IME on, off and toggle actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="仮想デスクトップ"),"action catalog virtual desktop category");
            Check(Enumerable.Range(1,8).All(n=>ActionCatalog.Items.Any(x=>x.Value=="Desktop"+n)),"direct desktop actions 1 through 8");
            Check(ActionCatalog.Items.Any(x=>x.Name.StartsWith("ズームイン")&&x.Value=="Ctrl+Add")&&ActionCatalog.Items.Any(x=>x.Name.StartsWith("ズームアウト")&&x.Value=="Ctrl+Subtract"),"action catalog zoom presets");
            Check(ActionCatalog.Items.Any(x=>x.Category=="マウス・ホイール"&&x.Name=="Shift+ドラッグ"&&x.Kind==ActionKind.Mouse&&x.Value=="ShiftDrag")&&ActionCatalog.Items.Any(x=>x.Category=="マウス・ホイール"&&x.Name=="Ctrl+ドラッグ"&&x.Kind==ActionKind.Mouse&&x.Value=="CtrlDrag"),"modifier drag actions are available in the mouse catalog");
            Check(ActionCatalog.Items.Any(x=>x.Category=="ブラウザー・タブ操作"&&x.Name=="右のタブへ移動"&&x.Value=="Ctrl+Tab")&&ActionCatalog.Items.Any(x=>x.Category=="ブラウザー・ページ操作"&&x.Name=="キャッシュを無視して更新"&&x.Value=="Ctrl+Shift+R"),"browser navigation and hard refresh actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="エクスプローラー・移動"&&x.Name=="上の階層へ"&&x.Value=="Alt+Up")&&ActionCatalog.Items.Any(x=>x.Category=="エクスプローラー・タブ"&&x.Name=="タブを閉じる"&&x.Value=="Ctrl+W"),"file explorer navigation and tab actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="音量・メディア"&&x.Value=="VolumeMute")&&ActionCatalog.Items.Any(x=>x.Category=="入力・アクセシビリティ"&&x.Value=="Win+."),"media and accessibility actions");
            Check(ActionCatalog.Items.Any(x=>x.Value=="MoveWindowDesktopRight"),"move active window to right desktop action");
            Check(InputEngine.TryGetDirectDesktopStep("Ctrl+Win+Left",out int leftStep)&&leftStep==-1&&InputEngine.TryGetDirectDesktopStep("Ctrl+Win+Right",out int rightStep)&&rightStep==1,"adjacent desktop actions use the direct API instead of injectable shortcuts");
            Check(new[]{"Left","Right","Up","Down"}.All(d=>ActionCatalog.Items.Any(x=>x.Value=="MoveWindowMonitor"+d)),"move active window to four monitor directions");
            Check(ActionCatalog.Items.Any(x=>x.Value=="Win+Left"&&x.Name.Contains("左半分"))&&ActionCatalog.Items.Any(x=>x.Value=="Win+Right"&&x.Name.Contains("右半分")),"snap active window to left and right halves");
            Check(ActionCatalog.Items.Any(x=>x.Value=="ToggleMaximizeUnderCursor"&&x.Name.Contains("元のサイズ")),"toggle maximize under cursor action");
            Check(ActionCatalog.Items.Any(x=>x.Category=="ウィンドウ・基本操作"&&x.Name=="最小化"&&x.Value=="MinimizeActiveWindow")&&ActionCatalog.Items.Any(x=>x.Category=="ウィンドウ・基本操作"&&x.Name=="ウィンドウを閉じる"&&x.Value=="Alt+F4"),"standalone minimize and standard Alt+F4 close-window actions");
            InputEngine.ResetMinimizeAllToggleForTest();Check(InputEngine.ResolveShortcutAliasForTest("CloseActiveWindow")=="Alt+F4"&&InputEngine.ResolveShortcutAliasForTest("ToggleMinimizeAllWindows")=="Win+M"&&InputEngine.ResolveShortcutAliasForTest("ToggleMinimizeAllWindows")=="Shift+Win+M"&&ActionCatalog.Items.Any(x=>x.Value=="Win+M")&&ActionCatalog.Items.Any(x=>x.Value=="Shift+Win+M"),"close compatibility and minimize-all toggle actions");
            Check(InputEngine.ShouldCloseWindowUnderCursor("Alt+F4",true)&&InputEngine.ShouldCloseWindowUnderCursor("CloseActiveWindow",true)&&!InputEngine.ShouldCloseWindowUnderCursor("Alt+F4",false)&&!InputEngine.ShouldCloseWindowUnderCursor("Ctrl+W",true),"close-window target option affects only close-window actions");
            Check(new[]{"Progman","WorkerW","Shell_TrayWnd","Shell_SecondaryTrayWnd"}.All(WindowMonitorService.IsProtectedShellSurface)&&!WindowMonitorService.IsProtectedShellSurface("Notepad"),"cursor-window close protects desktop and taskbar shell surfaces");
            Check(new[]{"画面キャプチャ","編集・クリップボード","ファイル・文書","文書の書式","ウィンドウ・整列","ブラウザー・タブ操作","エクスプローラー・ファイル操作"}.All(category=>ActionCatalog.Items.Any(x=>x.Category==category)),"common actions are divided into task-focused categories");
            Check(ActionCatalog.Items.Where(x=>x.Kind is ActionKind.Key or ActionKind.Shortcut).All(x=>InputEngine.IsRecognizedShortcut(x.Value)),"every catalog key and shortcut action is executable");
            Check(ActionCatalog.Items.GroupBy(x=>(x.Category,x.Name)).All(x=>x.Count()==1),"catalog has no duplicate action names within a category");
            var monitorAreas=new[]{new System.Drawing.Rectangle(0,0,1920,1080),new System.Drawing.Rectangle(1920,0,1920,1080),new System.Drawing.Rectangle(0,-1080,1920,1080),new System.Drawing.Rectangle(0,1080,1920,1080)};Check(WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Right)==1&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Up)==2&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Down)==3&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Left)==-1,"monitor direction target selection");
            var desktopA=Guid.NewGuid();var desktopB=Guid.NewGuid();var desktopBytes=desktopA.ToByteArray().Concat(desktopB.ToByteArray()).ToArray();var parsedDesktops=VirtualDesktopService.ParseDesktopIds(desktopBytes);Check(parsedDesktops.SequenceEqual(new[]{desktopA,desktopB}),"virtual desktop id parsing");
            Check(InputEngine.KeyName(0x31)=="1"&&InputEngine.KeyName(0x2C)=="PrintScreen","visual and physical key names match");
            Check(InputEngine.KeyName(0xF3)=="半角/全角"&&InputEngine.KeyName(0xE2)=="_","JIS key name normalization");
            Check(InputEngine.KeyName(0x0D)=="Enter"&&InputEngine.KeyName(0x1B)=="Esc"&&InputEngine.KeyName(0x61)=="NumPad1","special key names match visual keyboard");
            Check(InputEngine.IsValidRecordedEvent("A Down")&&InputEngine.IsValidRecordedEvent("MouseLeft Up")&&InputEngine.IsValidRecordedEvent("MouseMoveRelative:12,-4")&&!InputEngine.IsValidRecordedEvent("Unknown Down"),"macro event validation including relative mouse movement");
            Check(InputEngine.TryResolveShiftedSymbolForTest("?",false,out ushort jisQuestion)&&jisQuestion==0xBF&&InputEngine.TryResolveShiftedSymbolForTest("!",false,out ushort jisExclamation)&&jisExclamation==0x31&&InputEngine.TryResolveShiftedSymbolForTest("?",true,out ushort usQuestion)&&usQuestion==0xBF&&InputEngine.TryResolveShiftedSymbolForTest("!",true,out ushort usExclamation)&&usExclamation==0x31,"shifted question and exclamation key resolution");
            Check("!\"#$%&'()=~|`{+*}<>?".All(x=>InputEngine.TryResolveShiftedSymbolForTest(x.ToString(),false,out _))&&"~!@#$%^&*()_+{}|:\"<>?".All(x=>InputEngine.TryResolveShiftedSymbolForTest(x.ToString(),true,out _)),"JIS and US shifted symbol tables are complete");
            var stopShortcut=new MacroStopShortcut();bool premature=stopShortcut.Process("F12 Down");stopShortcut.Reset();stopShortcut.Process("LeftCtrl Down");stopShortcut.Process("LeftShift Down");bool macroStop=stopShortcut.Process("F12 Down");Check(!premature&&macroStop,"macro recording stop shortcut Ctrl+Shift+F12");
            Check(!MacroWindow.ShouldRecordEvent("A Down",false)&&!MacroWindow.ShouldRecordEvent("LeftCtrl Up",false)&&MacroWindow.ShouldRecordEvent("MouseLeft Down",false)&&MacroWindow.ShouldRecordEvent("WheelUp Down",false)&&MacroWindow.ShouldRecordEvent("MouseMove:10,20",false)&&MacroWindow.ShouldRecordEvent("A Down",true),"macro keyboard recording filter preserves mouse input");
            Check(MacroWindow.DropIndexAfterRemoval(1,3,4)==2&&MacroWindow.DropIndexAfterRemoval(3,1,4)==1&&MacroWindow.DropIndexAfterRemoval(1,2,4)==1,"macro drag insertion keeps before/after positions correct when the source row is removed");
            var macroCycleConfig=new AppConfig{Macros=[new MacroDefinition{Name="循環A",Steps=[new(){Event="割り当て: 循環B",RecordedActionKind=ActionKind.Macro,RecordedActionValue="循環B"}]},new MacroDefinition{Name="循環B",Steps=[new(){Event="割り当て: 循環A",RecordedActionKind=ActionKind.Macro,RecordedActionValue="循環A"}]}]};
            Check(ConfigValidator.Validate(macroCycleConfig).Any(x=>x.Contains("循環")),"recursive macro cycles are rejected before saving");
            bool unknownRejected=false;try{InputEngine.SendShortcut("DefinitelyUnknownKey");}catch(ArgumentException){unknownRejected=true;}Check(unknownRejected,"unknown shortcut key is rejected");
            Check(StartupService.BuildCommand(@"C:\Program Files\RELYR\RELYR.exe")=="\"C:\\Program Files\\RELYR\\RELYR.exe\" --tray","startup command quoting");
            string installedShutdown=App.BuildShutdownSignalName(@"C:\Program Files\RELYR\RELYR.exe");string developmentShutdown=App.BuildShutdownSignalName(@"C:\Dev\RELYR.exe");Check(installedShutdown==App.BuildShutdownSignalName(@"c:\program files\relyr\RELYR.EXE")&&installedShutdown!=developmentShutdown,"shutdown signal targets only the same executable path");
            var withoutPreset=service.Clone(loaded);withoutPreset.Profiles.RemoveAll(x=>x.Name=="既存AHK再現");service.Save(withoutPreset);Check(!service.Load().Profiles.Any(x=>x.Name=="既存AHK再現"),"deleted preset stays deleted");
        }
        catch(Exception ex){output.WriteLine("FAIL exception: "+ex);failures.Add("exception");}
        finally{try{Directory.Delete(dir,true);}catch{}}
        output.WriteLine(failures.Count==0?"SELF-TEST PASSED":"SELF-TEST FAILED: "+string.Join(", ",failures));
        return failures.Count==0?0:1;
    }
    static bool InputEngineSmokeTest(){using var engine=new InputEngine();engine.Enabled=false;return true;}
    static void TestMappingActions(Action<bool,string> check)
    {
        var fake=new FakeOutput();var executor=new MappingExecutor(fake);
        check(executor.Execute(new Mapping{Kind=ActionKind.Disabled},"A",out _)&&fake.Calls.Count==0,"disabled mapping");
        executor.Execute(new Mapping{Kind=ActionKind.Key,Value="Esc"},"A",out _);check(fake.Calls.Last()=="shortcut:Esc","key replacement action");
        executor.Execute(new Mapping{Kind=ActionKind.Shortcut,Value="Ctrl+C"},"A",out _);check(fake.Calls.Last()=="shortcut:Ctrl+C","shortcut action");
        executor.Execute(new Mapping{Kind=ActionKind.Text,Value="日本語"},"A",out _);check(fake.Calls.Last()=="text:日本語","Unicode text action");
        executor.Execute(new Mapping{Kind=ActionKind.Mouse,Value="WheelUp"},"A",out _);check(fake.Calls.Last()=="mouse:WheelUp","mouse and wheel action");
        var modifierDrag=new Mapping{Kind=ActionKind.Mouse,Value="ShiftDrag"};executor.Execute(modifierDrag,"Space+MouseLeft",out _);check(fake.Calls.Last()=="mouse:ShiftDrag","modifier drag mapping sends a modified single click when not dragged");executor.Execute(modifierDrag,"Space+MouseLeft:PressStart",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:Start","modifier drag presses the modifier and left button immediately");executor.Execute(modifierDrag,"Space+MouseLeft:PressEnd",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:End","modifier drag releases the left button and modifier at physical release");executor.Execute(modifierDrag,"Space+MouseLeft:DragStart",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:Start","legacy drag start remains compatible");executor.Execute(modifierDrag,"Space+MouseLeft:DragEnd",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:End","legacy drag end remains compatible");
        executor.Execute(new Mapping{Kind=ActionKind.Launch,Value="sample.exe"},"A",out _);check(fake.Calls.Last()=="launch:sample.exe","application launch action");
        executor.Execute(new Mapping{Kind=ActionKind.Macro,Value="作業マクロ"},"A",out _);check(fake.Calls.Last()=="macro:作業マクロ","macro action");
        executor.Execute(new Mapping{Kind=ActionKind.Profile,Value="ゲーム"},"A",out _);check(fake.Calls.Last()=="profile:ゲーム","profile switch action");
        check(MappingExecutor.TryGetRecordedAction(new Mapping{Input="Space+Up",Layer="Space",Kind=ActionKind.Shortcut,Value="Win+Left"},"Space+Up",out var recordedKind,out string recordedValue)&&recordedKind==ActionKind.Shortcut&&recordedValue=="Win+Left","macro recording resolves the assigned action instead of the physical layer keys");
        executor.Execute(new Mapping{Kind=ActionKind.Shortcut,Value="A",LongPressKind=ActionKind.Shortcut,LongPressValue="B"},"A:Long",out _);check(fake.Calls.Last()=="shortcut:B","long press action selection");
        fake.Calls.Clear();executor.Execute(new Mapping{Input="Space+G",Kind=ActionKind.Shortcut,Value="Ctrl+V",LongPressKind=ActionKind.Shortcut,LongPressValue="LWin+V"},"Space+G:Long",out _);check(fake.Calls.SequenceEqual(new[]{"neutralize:Space+G","shortcut:LWin+V"}),"long press neutralizes its physical source before sending a Windows shortcut");
        executor.Execute(new Mapping{Kind=ActionKind.Key,Value="B",LongPressKind=ActionKind.Launch,LongPressValue="sample.exe"},"A:Long",out _);check(fake.Calls.Last()=="launch:sample.exe","independent long press action kind");
        var longKindOnly=new Mapping{Input="Q",Layer="通常",Kind=ActionKind.None,LongPressKind=ActionKind.Launch,LongPressValue="sample.exe"};executor.Execute(longKindOnly,"Q",out _);check(fake.Calls.Last()=="shortcut:Q","long-kind-only mapping preserves tap");executor.Execute(longKindOnly,"Q:Long",out _);check(fake.Calls.Last()=="launch:sample.exe","long-kind-only mapping executes hold action");
        var longOnly=new Mapping{Input="K",Layer="通常",Kind=ActionKind.Shortcut,Value="",LongPressKind=ActionKind.Shortcut,LongPressValue="Ctrl+K"};executor.Execute(longOnly,"K",out _);check(fake.Calls.Last()=="shortcut:K","long-only mapping preserves normal tap");executor.Execute(longOnly,"K:Long",out _);check(fake.Calls.Last()=="shortcut:Ctrl+K","long-only mapping executes hold action");
        check(!MainWindow.HasConfiguredLongPress(new Mapping{Kind=ActionKind.Key,Value="Enter",LongPressKind=ActionKind.None,LongPressValue="q"})&&MainWindow.HasConfiguredLongPress(new Mapping{LongPressKind=ActionKind.Key,LongPressValue="q"}),"disabled stale long-press values never block normal key repeat");
    }
    sealed class FakeOutput:IInputOutput
    {
        public List<string> Calls{get;}=[];
        public void NeutralizeSourceKey(string input)=>Calls.Add("neutralize:"+input);public void SendShortcut(string value)=>Calls.Add("shortcut:"+value);public void SendText(string value)=>Calls.Add("text:"+value);public void SendMouse(string value)=>Calls.Add("mouse:"+value);public void Launch(string value)=>Calls.Add("launch:"+value);public void RunMacro(string name)=>Calls.Add("macro:"+name);public void SwitchProfile(string name)=>Calls.Add("profile:"+name);
    }
}
