namespace RELYR;
using System.IO;
using System.Text.Json;

public static class SelfTest
{
    public static int Run(TextWriter output)
    {
        var failures=new List<string>();
        void Check(bool value,string name){if(value)output.WriteLine("PASS "+name);else{output.WriteLine("FAIL "+name);failures.Add(name);}}
        string dir=VerificationPaths.CreateRunDirectory("self-test");
        try
        {
            var service=new ConfigService(dir);var config=service.Load();
            string oldData=Path.Combine(dir,"old-appdata"),newData=Path.Combine(dir,"new-appdata");var oldService=new ConfigService(oldData);oldService.Save(new AppConfig{AutoSave=true,Profiles=[new Profile{Name="移行テスト"}]});Check(ConfigService.MigrateLegacyDirectory(oldData,newData)&&!Directory.Exists(oldData)&&new ConfigService(newData).Load().Profiles[0].Name=="移行テスト","legacy settings move to the RELYR AppData folder without data loss");
            Directory.CreateDirectory(oldData);Directory.CreateDirectory(newData);File.WriteAllText(Path.Combine(oldData,"old.json"),"{}");File.WriteAllText(Path.Combine(newData,"settings.json"),"{}");Check(ConfigService.DeleteUserDataDirectories(oldData,newData)&&!Directory.Exists(oldData)&&!Directory.Exists(newData),"complete uninstall removes both current and legacy AppData settings folders");
            Check(config.Profiles.Count==1&&config.Profiles[0].Name=="標準"&&config.Profiles[0].Mappings.Count==0,"only standard profile exists by default");
            byte[] legacyMap=[0,0,0,0,0,0,0,0,3,0,0,0,0x64,0,0x3A,0,0x0C,0,0x79,0,0,0,0,0];Check(LegacyKeyRemapService.ContainsCapsLockToF13(legacyMap),"legacy CapsLock-to-F13 registry mapping detection");
            var remapRemoved=LegacyKeyRemapService.UpdateCapsLockToF13(legacyMap,false);var remapRestored=LegacyKeyRemapService.UpdateCapsLockToF13(remapRemoved,true);Check(!LegacyKeyRemapService.ContainsCapsLockToF13(remapRemoved)&&BitConverter.ToUInt32(remapRemoved,12)==0x0079000C&&LegacyKeyRemapService.ContainsCapsLockToF13(remapRestored),"CapsLock F13 setting preserves unrelated registry remaps and can be restored");
            string legacyDir=Path.Combine(dir,"legacy-v7");var legacyService=new ConfigService(legacyDir);legacyService.Save(new AppConfig{Version=7,EngineEnabled=false});var repairedLegacy=legacyService.Load();using var repairedDocument=JsonDocument.Parse(File.ReadAllText(legacyService.FilePath));Check(repairedLegacy.Version==23&&repairedLegacy.EngineEnabled&&repairedDocument.RootElement.GetProperty("Version").GetInt32()==23&&repairedDocument.RootElement.GetProperty("EngineEnabled").GetBoolean(),"v7 reboot-disabled engine is repaired and persistently migrated once");
            string legacyDisabledDir=Path.Combine(dir,"legacy-disabled-mapping");Directory.CreateDirectory(legacyDisabledDir);File.WriteAllText(Path.Combine(legacyDisabledDir,"settings.json"),"{\"Version\":17,\"Profiles\":[{\"Name\":\"標準\",\"Mappings\":[{\"Input\":\"Q\",\"Kind\":\"Key\",\"Value\":\"A\",\"Enabled\":false},{\"Input\":\"W\",\"Kind\":\"Key\",\"Value\":\"B\",\"Enabled\":true}]}]}");var migratedDisabledService=new ConfigService(legacyDisabledDir);var migratedDisabled=migratedDisabledService.Load();string migratedDisabledJson=File.ReadAllText(migratedDisabledService.FilePath);Check(migratedDisabled.Version==23&&migratedDisabled.Profiles[0].Mappings is [{Input:"W"}]&&!migratedDisabledJson.Contains("\"Enabled\"",StringComparison.Ordinal),"legacy disabled assignments are deleted while enabled assignments remain active");
            string staleLongDir=Path.Combine(dir,"legacy-long-value");var staleLongService=new ConfigService(staleLongDir);staleLongService.Save(new AppConfig{Version=8,Profiles=[new Profile{Mappings=[new Mapping{Input="Space+K",Kind=ActionKind.Key,Value="Enter",LongPressKind=ActionKind.None,LongPressValue="q"},new Mapping{Input="Space+L",Kind=ActionKind.Key,Value="Right",LongPressKind=ActionKind.Launch,LongPressValue="app.exe"}]}]});var migratedLong=staleLongService.Load();Check(migratedLong.Version==23&&migratedLong.Profiles[0].Mappings[0].LongPressValue==""&&migratedLong.Profiles[0].Mappings[1].LongPressValue=="app.exe","stale disabled long-press values are removed without changing explicit long actions");
            string mouseFixDir=Path.Combine(dir,"legacy-mouse-action");var mouseFixService=new ConfigService(mouseFixDir);mouseFixService.Save(new AppConfig{Version=15,Profiles=[new Profile{Mappings=[new Mapping{Input="Space+MouseLeft",Kind=ActionKind.Key,Value="ShiftDrag"},new Mapping{Input="Space+MouseRight",LongPressKind=ActionKind.Shortcut,LongPressValue="Ctrl+MouseLeft"}]}]});var fixedMouse=mouseFixService.Load();Check(fixedMouse.Version==23&&fixedMouse.Profiles[0].Mappings[0] is {Kind:ActionKind.Mouse,Value:"ShiftDrag"}&&fixedMouse.Profiles[0].Mappings[1] is {LongPressKind:ActionKind.Mouse,LongPressValue:"CtrlDrag"},"misclassified modifier-click assignments are repaired during settings upgrade");
            string gestureMigrationDir=Path.Combine(dir,"legacy-long-gesture");Directory.CreateDirectory(gestureMigrationDir);File.WriteAllText(Path.Combine(gestureMigrationDir,"settings.json"),"{\"Version\":19,\"Gestures\":[{\"Name\":\"ウィンドウ操作\"}],\"Profiles\":[{\"Name\":\"標準\",\"Mappings\":[{\"Input\":\"MouseRight+Space\",\"Kind\":\"None\",\"Value\":\"\",\"LongPressKind\":\"Gesture\",\"LongPressValue\":\"ウィンドウ操作\"}]}]}");var migratedGesture=new ConfigService(gestureMigrationDir).Load();Check(migratedGesture.Version==23&&migratedGesture.Profiles[0].Mappings[0] is {Kind:ActionKind.Gesture,Value:"ウィンドウ操作",LongPressKind:ActionKind.None,LongPressValue:""},"v19 long-press-only gestures migrate to immediate short-press gestures without losing the reference");
            var pendingCaps=new AppConfig{CapsLockRemapPendingRestart=true,CapsLockRemapChangedAtUtcTicks=DateTime.UtcNow.AddMinutes(-1).Ticks};Check(LegacyKeyRemapService.IsRestartStillPending(pendingCaps,DateTime.UtcNow,(long)TimeSpan.FromHours(1).TotalMilliseconds)&&!LegacyKeyRemapService.IsRestartStillPending(pendingCaps,DateTime.UtcNow,(long)TimeSpan.FromSeconds(10).TotalMilliseconds),"CapsLock remap distinguishes the current boot from a completed restart");
            Check(!App.UninstallRestartNeeded(new AppConfig(),false,false)&&App.UninstallRestartNeeded(new AppConfig(),true,false)&&!App.UninstallRestartNeeded(new AppConfig{CapsLockLayerEnabled=true},false,false)&&App.UninstallRestartNeeded(new AppConfig(),false,true),"normal updates and a saved CapsLock preference do not request a restart; only an active or pending system remap does");
            Check(config.Profiles.SelectMany(p=>p.Mappings).All(m=>!m.Input.StartsWith("F13",StringComparison.OrdinalIgnoreCase)&&!m.Layer.Equals("F13",StringComparison.OrdinalIgnoreCase)),"F13 layer settings migrate to CapsLock");
            config.Macros.Add(new MacroDefinition{Name="テストマクロ",Steps=[new(){Event="A Down",DelayMs=100},new(){Event="A Up",DelayMs=25},new(){Event="Wait",DelayMs=500},new(){Event="割り当て: Win+Left",RecordedActionKind=ActionKind.Shortcut,RecordedActionValue="Win+Left"}]});
            config.Gestures.Add(new GestureDefinition{Name="ウィンドウ操作",UpKind=ActionKind.Shortcut,UpValue="Win+Up",DownKind=ActionKind.Shortcut,DownValue="Win+Down",CenterKind=ActionKind.Key,CenterValue="Enter"});
            config.Profiles[0].Mappings.Add(new Mapping{Input="G",Kind=ActionKind.Gesture,Value="ウィンドウ操作"});
            Check(ConfigValidator.Validate(config).Count==0,"default config validation");
            Check(MainWindow.GestureAction(config.Gestures[0],"Up")==(ActionKind.Shortcut,"Win+Up")&&MainWindow.GestureAction(config.Gestures[0],"Center")==(ActionKind.Key,"Enter"),"gesture directions and center resolve to their configured actions");
            var invalidGesture=service.Clone(config);invalidGesture.Gestures[0].LeftKind=ActionKind.Gesture;invalidGesture.Gestures[0].LeftValue="ウィンドウ操作";Check(ConfigValidator.Validate(invalidGesture).Any(x=>x.Contains("入れ子")),"nested gestures are rejected before saving");
            var missingGesture=service.Clone(config);missingGesture.Profiles[0].Mappings[0].Value="存在しないジェスチャー";Check(ConfigValidator.Validate(missingGesture).Any(x=>x.Contains("ジェスチャー「存在しないジェスチャー」")),"missing gesture references are rejected before saving");
            var gestureReferences=service.Clone(config).Profiles;GestureManagerWindow.RenameReferences(gestureReferences,"ウィンドウ操作","名前変更後");Check(gestureReferences[0].Mappings[0].Value=="名前変更後","renaming a gesture updates every mapping reference");GestureManagerWindow.ClearReferences(gestureReferences,"名前変更後");Check(gestureReferences[0].Mappings[0] is {Kind:ActionKind.None,Value:""},"deleting a gesture clears every mapping reference");
            Check(GestureManagerWindow.SupportedActionChoices.Select(x=>x.Kind).SequenceEqual(new[]{ActionKind.Key,ActionKind.Profile,ActionKind.Shortcut,ActionKind.Text,ActionKind.Launch,ActionKind.Macro}),"gesture directions expose key, profile, shortcut, text, app, and macro choices");
            var blankAction=service.Clone(config);blankAction.Profiles[0].Mappings.Add(new Mapping{Input="Q",Kind=ActionKind.Shortcut,Value=""});Check(ConfigValidator.Validate(blankAction).Count==0,"blank execution value can be left unfinished without a validation error");
            Check(!MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.None,Value="stale"})&&!MainWindow.MappingInterceptsInput(new Mapping{Input="M",Kind=ActionKind.Shortcut,Value=""})&&MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.Disabled})&&MainWindow.MappingInterceptsInput(new Mapping{Input="MouseBack",Kind=ActionKind.None,LongPressKind=ActionKind.Key,LongPressValue="Enter"}),"unfinished mappings do not look assigned or block native input while disabled and long-only mappings still intercept");
            Check(MainWindow.ShouldFocusExecutionForSelectedInput(null)&&!MainWindow.ShouldFocusExecutionForSelectedInput(new Mapping{Input="A",Kind=ActionKind.Key,Value="B"}),"only an unassigned key automatically focuses the execution-value editor");
            var hoverMapping=new Mapping{Input="Space+K",Kind=ActionKind.Shortcut,Value="Ctrl+C",LongPressKind=ActionKind.Launch,LongPressValue=@"C:\Apps\Sample.exe",LongPressMs=600};string? hoverText=MainWindow.AssignmentToolTipText(hoverMapping);Check(MainWindow.AssignmentToolTipText(null)==null&&hoverText?.Contains("アクション：ショートカット")==true&&hoverText.Contains("実行内容：")&&hoverText.Contains("長押し（600 ms）")&&hoverText.Contains("アクション：アプリ・ファイル・URL")&&hoverText.Contains(@"C:\Apps\Sample.exe"),"assigned keyboard hover shows short and long actions while unassigned keys show no popup");
            Check(MainWindow.DisplayInputName("MouseRight+K")=="右クリック + K"&&MainWindow.DisplayInputName("Taskbar+MouseMiddle")=="タスクバー上 + ホイールクリック"&&MainWindow.DisplayInputName("MouseBack+WheelUp")=="戻る + ホイール上","internal layer names are presented as beginner-friendly input names");
            var mouseDisplayCases=new Dictionary<string,string>{{"MouseLeft","マウス：左クリック"},{"MouseRight","マウス：右クリック"},{"MouseMiddle","マウス：ホイールクリック"},{"MouseBack","マウス：戻る"},{"MouseForward","マウス：進む"},{"MouseX","マウス：追加ボタン"},{"WheelUp","マウス：ホイール上"},{"WheelDown","マウス：ホイール下"},{"TiltLeft","マウス：チルト左"},{"TiltRight","マウス：チルト右"},{"ShiftDrag","マウス：Shift + 左クリック"},{"CtrlDrag","マウス：Ctrl + 左クリック"},{"AltDrag","マウス：Alt + 左クリック"}};Check(mouseDisplayCases.All(x=>MainWindow.DisplayActionValue(ActionKind.Mouse,x.Key)==x.Value&&MainWindow.NormalizeEditorAction(ActionKind.Shortcut,x.Value,ActionKind.Mouse,x.Key)==(ActionKind.Mouse,x.Key)),"every mouse execution value is readable in the editor and safely converts back to its compatible internal name");
            config.Profiles.Add(new Profile{Name="アプリ用",AutoSwitchEnabled=true,AutoSwitchApplications=["notepad.exe"]});config.ActiveProfile="アプリ用";config.AutoSwitchProfilesByCursor=false;config.ShowProfileSwitchOverlay=false;config.ShowDesktopNumberInTray=true;config.CheckForUpdates=false;config.DismissedUpdateVersion="9.9.9";config.WindowActionTarget=WindowActionTarget.WindowUnderCursor;config.ThemeMode=AppThemeMode.Light;config.LastUpdateCheckUtcTicks=DateTimeOffset.UtcNow.UtcTicks;config.RecordKeyboardInputInMacros=false;config.RecordMappedActionsInMacros=true;config.RecordMouseMovementInMacros=true;config.RecordMouseMovementRelativeInMacros=false;config.ArchiveWatchFolder=@"C:\Watch";config.ArchiveDestinationFolder=@"D:\Extracted";config.AutoSave=true;config.KeyboardLayout="US";config.SpaceHoldRepeatEnabled=true;config.SpaceHoldRepeatDelayMs=450;config.GestureThresholdPixels=12;config.LockCursorDuringGesture=false;config.ClockBackgroundMode=ClockBackgroundMode.Image;config.ClockDisplayMode=ClockDisplayMode.FullDateAndTime;config.ClockBackgroundImage=@"C:\Wallpapers\clock.jpg";config.ClockSolidColor="#123456";config.ClockShowOnAllMonitors=false;config.InputPanelOpacityPercent=67;service.Save(config);var loaded=service.Load();
            Check(loaded.ActiveProfile=="アプリ用","JSON roundtrip");
            Check(!loaded.AutoSwitchProfilesByCursor,"cursor profile auto-switch option roundtrip");
            Check(!loaded.ShowProfileSwitchOverlay,"profile switch overlay option roundtrip");
            Check(loaded.ShowDesktopNumberInTray,"tray desktop number setting roundtrip");
            Check(!loaded.CheckForUpdates&&loaded.DismissedUpdateVersion=="9.9.9","update-check and dismissed-version settings roundtrip");
            Check(loaded.WindowActionTarget==WindowActionTarget.WindowUnderCursor,"window action target setting roundtrip");
            Check(loaded.ThemeMode==AppThemeMode.Light&&loaded.LastUpdateCheckUtcTicks==config.LastUpdateCheckUtcTicks,"theme mode and last update check roundtrip");
            Check(!loaded.RecordKeyboardInputInMacros,"macro keyboard recording option roundtrip");
            Check(loaded.RecordMappedActionsInMacros,"macro mapped-action recording option roundtrip");
            Check(loaded.RecordMouseMovementInMacros,"macro mouse trajectory option roundtrip");
            Check(!loaded.RecordMouseMovementRelativeInMacros,"macro mouse fixed/relative movement mode roundtrip");
            Check(loaded.ArchiveWatchFolder==@"C:\Watch"&&loaded.ArchiveDestinationFolder==@"D:\Extracted","archive watch and destination folders roundtrip");
            Check(loaded.AutoSave,"auto-save setting roundtrip");
            Check(loaded.KeyboardLayout=="US","keyboard layout setting roundtrip");
            Check(loaded.SpaceHoldRepeatEnabled&&loaded.SpaceHoldRepeatDelayMs==450,"Space hold repeat setting roundtrip");
            Check(loaded.GestureThresholdPixels==12&&!loaded.LockCursorDuringGesture&&loaded.Gestures.Any(x=>x.Name=="ウィンドウ操作"&&x.UpValue=="Win+Up"&&x.CenterValue=="Enter")&&loaded.Profiles[0].Mappings.Any(x=>x.Kind==ActionKind.Gesture&&x.Value=="ウィンドウ操作"),"gesture definitions, references, center action, sensitivity, and cursor-lock option roundtrip");
            Check(loaded.ClockBackgroundMode==ClockBackgroundMode.Image&&loaded.ClockDisplayMode==ClockDisplayMode.FullDateAndTime&&loaded.ClockBackgroundImage==@"C:\Wallpapers\clock.jpg"&&loaded.ClockSolidColor=="#123456"&&!loaded.ClockShowOnAllMonitors,"clock overlay background, solid color, date format, image, and monitor scope roundtrip");
            Check(loaded.InputPanelOpacityPercent==67,"input-panel opacity setting roundtrip");
            Check(ScreenOverlayWindow.ParseClockColor("#123456")==System.Windows.Media.Color.FromRgb(0x12,0x34,0x56)&&ScreenOverlayWindow.ParseClockColor("invalid")==System.Windows.Media.Color.FromRgb(16,31,46),"clock solid colors accept hex values and safely fall back from invalid input");
            var gestureMigrationService=new ConfigService(Path.Combine(dir,"gesture-threshold-migration"));gestureMigrationService.Save(new AppConfig{Version=21,GestureThresholdPixels=24});var migratedGestureConfig=gestureMigrationService.Load();Check(migratedGestureConfig.Version==23&&migratedGestureConfig.GestureThresholdPixels==12,"the former 24-pixel gesture default migrates to a more forgiving 12-pixel movement threshold");
            Check(loaded.Profiles[1].AutoSwitchEnabled&&loaded.Profiles[1].AutoSwitchApplications.Contains("notepad.exe"),"profile application auto-switch roundtrip");
            const string releaseJson="""{"tag_name":"v0.1.69","draft":false,"prerelease":false,"assets":[{"name":"RELYR-Setup-0.1.69.exe","state":"uploaded","browser_download_url":"https://github.com/zitan-source/RELYR/releases/download/v0.1.69/RELYR-Setup-0.1.69.exe","digest":"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},{"name":"RELYR-Setup-0.1.69.exe.sha256","state":"uploaded","browser_download_url":"https://github.com/zitan-source/RELYR/releases/download/v0.1.69/RELYR-Setup-0.1.69.exe.sha256"}]}""";
            var availableUpdate=UpdateService.ParseLatestRelease(releaseJson,new Version(0,1,68));var latestVersion=UpdateService.ParseLatestVersion(releaseJson);Check(availableUpdate is {VersionText:"0.1.69"}&&availableUpdate.InstallerFileName=="RELYR-Setup-0.1.69.exe"&&UpdateService.ParseLatestRelease(releaseJson,new Version(0,1,69))==null&&latestVersion.Version==new Version(0,1,69)&&latestVersion.VersionText=="0.1.69","GitHub release parser accepts only a newer trusted installer with its checksum and reports the latest version");
            string friendlyUpdateError=UpdateService.FriendlyError(new System.Net.Http.HttpRequestException("secret raw details"));Check(friendlyUpdateError.Contains("接続")&&!friendlyUpdateError.Contains("secret raw details"),"update errors are translated into a beginner-friendly message without raw exception details");
            var updateNow=new DateTimeOffset(2026,7,18,12,0,0,TimeSpan.Zero);Check(MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,0)&&!MainWindow.IsAutomaticUpdateCheckDue(updateNow,updateNow.AddHours(-23),0)&&MainWindow.IsAutomaticUpdateCheckDue(updateNow,updateNow.AddHours(-24),0),"automatic update checks run on first display and then at most once per day");Check(!MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,updateNow.AddHours(-23).UtcTicks)&&MainWindow.IsAutomaticUpdateCheckDue(updateNow,default,updateNow.AddHours(-25).UtcTicks),"persisted successful update checks also enforce the one-day interval");
            Check(loaded.Macros.Any(x=>x.Name=="テストマクロ"&&x.Steps.Count==4&&x.Steps.Last().RecordedActionKind==ActionKind.Shortcut&&x.Steps.Last().RecordedActionValue=="Win+Left"&&!string.IsNullOrWhiteSpace(x.Id)),"macro JSON roundtrip with stable identity and mapped action");
            string macroArguments=ShortcutService.BuildMacroArguments("日本語 マクロ");var macroArgumentParts=macroArguments.Split(' ',2);Check(ShortcutService.TryReadMacroName(macroArgumentParts,out string shortcutMacro)&&shortcutMacro=="日本語 マクロ","legacy macro shortcut arguments preserve the exact macro name");string shortcutDirectory=Path.Combine(dir,"shortcuts");var shortcutDefinition=new MacroDefinition{Name="日本語 マクロ"};string shortcutPath=ShortcutService.CreateMacroShortcut(shortcutDefinition,shortcutDirectory,Environment.ProcessPath);var idArgumentParts=ShortcutService.BuildMacroIdArguments(shortcutDefinition.Id).Split(' ',2);Check(File.Exists(shortcutPath)&&ShortcutService.TryReadMacroId(idArgumentParts,out string shortcutMacroId)&&shortcutMacroId==shortcutDefinition.Id,"macro desktop shortcut uses stable identity");string? shortcutIcon=ShortcutService.ResolveShortcutIconLocation(shortcutPath);Check(File.Exists(Path.Combine(AppContext.BaseDirectory,"RELYR-Macro.ico"))&&shortcutIcon?.EndsWith("RELYR-Macro.ico,0",StringComparison.OrdinalIgnoreCase)==true,"macro desktop shortcut uses the distinct packaged macro icon");string oldShortcut=ShortcutService.CreateMacroShortcut("変更前",shortcutDirectory,Environment.ProcessPath);shortcutDefinition.Name="変更後";string? renamedShortcut=ShortcutService.MigrateRenamedMacroShortcut("変更前",shortcutDefinition,shortcutDirectory,Environment.ProcessPath);Check(!File.Exists(oldShortcut)&&renamedShortcut!=null&&File.Exists(renamedShortcut),"renaming a macro migrates its existing desktop shortcut");var legacyShortcutMacro=new MacroDefinition{Name="旧ショートカット"};string legacyShortcutPath=Path.Combine(shortcutDirectory,"旧ショートカット - Input Customizer.lnk");File.WriteAllText(legacyShortcutPath,"");string? upgradedLegacyShortcut=ShortcutService.UpgradeExistingMacroShortcut(legacyShortcutMacro,shortcutDirectory,Environment.ProcessPath);Check(!File.Exists(legacyShortcutPath)&&upgradedLegacyShortcut!=null&&File.Exists(upgradedLegacyShortcut)&&Path.GetFileName(upgradedLegacyShortcut).EndsWith(" - RELYR.lnk"),"legacy product-name macro shortcuts are replaced by RELYR shortcuts");
            string archiveTests=Path.Combine(dir,"archives");Directory.CreateDirectory(archiveTests);string archiveSource=Path.Combine(archiveTests,"source");Directory.CreateDirectory(archiveSource);File.WriteAllText(Path.Combine(archiveSource,"hello.txt"),"RELYR archive test");
            string zipPath=Path.Combine(archiveTests,"sample.zip");System.IO.Compression.ZipFile.CreateFromDirectory(archiveSource,zipPath);string zipOutput=ArchiveWatcher.ExtractArchive(zipPath);Check(File.ReadAllText(Path.Combine(zipOutput,"hello.txt"))=="RELYR archive test","ZIP extraction works with real archive");
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);string legacyZipPath=Path.Combine(archiveTests,"legacy-japanese.zip");using(var legacyZipFile=File.Create(legacyZipPath))using(var legacyZip=new System.IO.Compression.ZipArchive(legacyZipFile,System.IO.Compression.ZipArchiveMode.Create,false,System.Text.Encoding.GetEncoding(932)))using(var legacyWriter=new StreamWriter(legacyZip.CreateEntry("日本語ファイル.txt").Open()))legacyWriter.Write("legacy filename");string legacyZipOutput=ArchiveWatcher.ExtractArchive(legacyZipPath);Check(File.ReadAllText(Path.Combine(legacyZipOutput,"日本語ファイル.txt"))=="legacy filename","ZIP filenames stored with Japanese Windows CP932 encoding are extracted without garbling");
            string tarGzPath=Path.Combine(archiveTests,"sample-tar.tar.gz");using(var compressedOutput=File.Create(tarGzPath))using(var gzip=new System.IO.Compression.GZipStream(compressedOutput,System.IO.Compression.CompressionLevel.SmallestSize))using(var tar=new System.Formats.Tar.TarWriter(gzip,leaveOpen:false))tar.WriteEntry(Path.Combine(archiveSource,"hello.txt"),"folder/hello.txt");string tarOutput=ArchiveWatcher.ExtractArchive(tarGzPath);Check(File.ReadAllText(Path.Combine(tarOutput,"folder","hello.txt"))=="RELYR archive test","TAR.GZ extraction works with real archive");
            string sevenPath=Path.Combine(archiveTests,"sample.7z");using(var seven=System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("tar.exe",$"-a -cf \"{sevenPath}\" -C \"{archiveSource}\" .") {UseShellExecute=false,CreateNoWindow=true}))seven?.WaitForExit(10000);bool sevenOk=File.Exists(sevenPath);if(sevenOk){string sevenOutput=ArchiveWatcher.ExtractArchive(sevenPath);sevenOk=File.Exists(Path.Combine(sevenOutput,"hello.txt"));}Check(sevenOk,"7Z extraction works with real archive");
            string unsafeZip=Path.Combine(archiveTests,"unsafe.zip");using(var file=File.Create(unsafeZip))using(var zip=new System.IO.Compression.ZipArchive(file,System.IO.Compression.ZipArchiveMode.Create))using(var writer=new StreamWriter(zip.CreateEntry("../outside.txt").Open()))writer.Write("blocked");bool traversalBlocked=false;try{ArchiveWatcher.ExtractArchive(unsafeZip);}catch(InvalidDataException){traversalBlocked=true;}Check(traversalBlocked&&!File.Exists(Path.Combine(archiveTests,"outside.txt")),"archive path traversal is blocked");
            string watchedDesktop=Path.Combine(archiveTests,"desktop"),watchedOutput=Path.Combine(archiveTests,"output");Directory.CreateDirectory(watchedDesktop);Directory.CreateDirectory(watchedOutput);using(var extracted=new ManualResetEventSlim())using(var watcher=new ArchiveWatcher(watchedDesktop)){watcher.Status+=message=>{if(message.StartsWith("自動解凍しました"))extracted.Set();};watcher.Apply(new AppConfig{AutoExtractDesktopArchives=true,ArchiveDestinationFolder=watchedOutput});string watchedZip=Path.Combine(watchedDesktop,"watched.zip");System.IO.Compression.ZipFile.CreateFromDirectory(archiveSource,watchedZip);bool watcherDone=extracted.Wait(8000);Check(watcherDone&&File.Exists(Path.Combine(watchedOutput,"watched","hello.txt")),"custom watch folder automatically extracts into the selected destination folder");}
            service.Save(loaded);Check(Directory.GetFiles(dir,"*.bak.json").Length>=1,"automatic backup");
            for(int i=0;i<25;i++){loaded.DoubleClickMs=300+i;service.Save(loaded);}
            Check(Directory.GetFiles(dir,"*.bak.json").Length==20,"20 generation backup retention");
            Check(!File.Exists(service.FilePath+".tmp"),"atomic save cleanup");
            string exported=Path.Combine(dir,SettingsWindow.ExportFileName);service.Export(loaded,exported);var imported=service.Import(exported);string legacyExport=Path.Combine(dir,"legacy-settings.json");service.Export(loaded,legacyExport);var importedLegacy=service.Import(legacyExport);Check(Path.GetExtension(exported)==".relyr"&&SettingsWindow.ExportFileFilter.Contains("*.relyr")&&SettingsWindow.ImportFileFilter.Contains("*.json")&&imported.Profiles.Count==loaded.Profiles.Count&&imported.Macros.Count==loaded.Macros.Count&&importedLegacy.Profiles.Count==loaded.Profiles.Count,"dedicated RELYR settings file export and legacy JSON import");
            string resetDir=Path.Combine(dir,"reset");var resetService=new ConfigService(resetDir);resetService.Save(new AppConfig{ActiveProfile="カスタム",StartWithWindows=true,CapsLockLayerEnabled=true,Macros=[new MacroDefinition()],Profiles=[new Profile{Name="カスタム",Mappings=[new Mapping{Input="A",Kind=ActionKind.Key,Value="B"}]}]});var reset=resetService.ResetToDefaults();Check(reset.FirstRunCompleted&&!reset.StartWithWindows&&!reset.CapsLockLayerEnabled&&reset.Macros.Count==0&&reset.Profiles.Count==1&&reset.Profiles[0].Name=="標準"&&reset.Profiles[0].Mappings.Count==0,"all-settings reset returns every profile, layer assignment, macro and app option to defaults");
            var missingMacro=service.Clone(loaded);missingMacro.Profiles[0].Mappings.Add(new Mapping{Input="Q",Kind=ActionKind.Macro,Value="存在しないマクロ"});Check(ConfigValidator.Validate(missingMacro).Any(x=>x.Contains("マクロ「存在しないマクロ」")),"missing macro validation");
            var missingProfile=service.Clone(loaded);missingProfile.Profiles[0].Mappings.Add(new Mapping{Input="W",Kind=ActionKind.Profile,Value="存在しないプロファイル"});Check(ConfigValidator.Validate(missingProfile).Any(x=>x.Contains("プロファイル「存在しないプロファイル」")),"missing profile validation");
            loaded.Profiles[0].Mappings.Add(new Mapping{Input="A",Kind=ActionKind.Key,Value="B"});
            loaded.Profiles[0].Mappings.Add(new Mapping{Input="A",Kind=ActionKind.Key,Value="C"});
            Check(ConfigValidator.Validate(loaded).Any(x=>x.Contains("競合")),"conflict detection");
            Check(InputEngineSmokeTest(),"input engine construct/dispose");
            TestMappingActions(Check);
            Check(ConditionMatcher.Matches("notepad.exe","NOTEPAD"),"application condition matching");
            var autoProfiles=new[]{new Profile{Name="標準"},new Profile{Name="メモ帳",AutoSwitchEnabled=true,AutoSwitchApplications=["notepad.exe"]}};Check(MainWindow.SelectAutomaticProfile(autoProfiles,"notepad").Name=="メモ帳"&&MainWindow.SelectAutomaticProfile(autoProfiles,"explorer").Name=="標準","cursor application profile selection");Check(MainWindow.SelectAutomaticProfileNameForLocation(autoProfiles,"メモ帳","explorer",true)=="メモ帳"&&MainWindow.SelectAutomaticProfileNameForLocation(autoProfiles,"メモ帳","explorer",false)=="標準","taskbar keeps the previously selected application profile");Check(MainWindow.ShouldKeepExplicitProfile("chrome.exe","chrome",false)&&MainWindow.ShouldKeepExplicitProfile("chrome.exe","explorer",true)&&!MainWindow.ShouldKeepExplicitProfile("chrome.exe","notepad",false),"an explicit profile action remains active over the current app and yields only after the pointer moves to another app");Check(MainWindow.IsOwnProcess("RELYR",@"C:\Program Files\RELYR\RELYR.exe")&&!MainWindow.IsOwnProcess("chrome",@"C:\Program Files\RELYR\RELYR.exe"),"profile auto-switch ignores the RELYR settings window");var editingProfileConfig=new AppConfig{ActiveProfile="メモ帳",Profiles=autoProfiles.ToList()};var runtimeProfileConfig=service.Clone(editingProfileConfig);Check(MainWindow.ApplyAutomaticProfile(editingProfileConfig,runtimeProfileConfig,"標準")&&editingProfileConfig.ActiveProfile=="メモ帳"&&runtimeProfileConfig.ActiveProfile=="標準","automatic profile switching changes runtime behavior without moving the profile being edited");
            var guardedRuntimeConfig=service.Clone(editingProfileConfig);Check(!MainWindow.TryApplyAutomaticProfile(editingProfileConfig,guardedRuntimeConfig,"標準",()=>false)&&guardedRuntimeConfig.ActiveProfile=="メモ帳"&&MainWindow.TryApplyAutomaticProfile(editingProfileConfig,guardedRuntimeConfig,"標準",()=>true)&&guardedRuntimeConfig.ActiveProfile=="標準","automatic profile switching waits for captured input to be fully released");
            var mixedAutoProfiles=new[]{new Profile{Name="標準"},new Profile{Name="Chrome"},new Profile{Name="Filmora",AutoSwitchEnabled=true,AutoSwitchApplications=["Wondershare Filmora.exe"]}};var keepChrome=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"Chrome","","explorer.exe",false);var enterFilmora=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"Chrome","","Wondershare Filmora.exe",false);var enterFilmoraThroughRenderChild=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"標準","",new[]{"QtWebEngineProcess","Wondershare Filmora"},false);var leaveFilmora=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"Filmora","Chrome","explorer.exe",false);var filmoraOnOtherDesktop=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"Filmora","","explorer.exe",false);var pointerOverRelyrAfterFilmora=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"Filmora","","",false);Check(keepChrome==("Chrome","")&&enterFilmora==("Filmora","Chrome")&&enterFilmoraThroughRenderChild.Target=="Filmora"&&leaveFilmora==("Chrome","")&&filmoraOnOtherDesktop==("標準","")&&pointerOverRelyrAfterFilmora==("標準",""),"cursor auto-switch recognizes a host app behind its render child, preserves a manual profile, and returns when the app is absent or on another desktop");
            var runtimeAutoConfig=new AppConfig{ActiveProfile="標準",Profiles=mixedAutoProfiles.ToList()};var editingAutoConfig=service.Clone(runtimeAutoConfig);string deferredReturn="";bool deferredSwitch=MainWindow.TryResolveAndApplyAutomaticProfile(editingAutoConfig,runtimeAutoConfig,new[]{"Wondershare Filmora"},false,()=>false,ref deferredReturn,out _);string returnAfterReject=deferredReturn;bool appliedSwitch=MainWindow.TryResolveAndApplyAutomaticProfile(editingAutoConfig,runtimeAutoConfig,new[]{"Wondershare Filmora"},false,()=>true,ref deferredReturn,out string appliedTarget);var filmoraCandidateFromHost=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"標準","",new[]{"Wondershare Filmora"},false);var filmoraCandidateFromChangingChildren=MainWindow.ResolveAutomaticProfileTarget(mixedAutoProfiles,"標準","",new[]{"QtWebEngineProcess","Wondershare Filmora","Filmora Helper"},false);Check(!deferredSwitch&&returnAfterReject==""&&appliedSwitch&&appliedTarget=="Filmora"&&runtimeAutoConfig.ActiveProfile=="Filmora"&&deferredReturn=="標準"&&filmoraCandidateFromHost.Target==filmoraCandidateFromChangingChildren.Target,$"a rejected automatic switch keeps its return state unchanged, retries after input release, and resolves changing child-process lists to the same profile (rejected={deferredSwitch}, afterReject={returnAfterReject}, applied={appliedSwitch}, target={appliedTarget}, active={runtimeAutoConfig.ActiveProfile}, return={deferredReturn}, hostCandidate={filmoraCandidateFromHost.Target}, childCandidate={filmoraCandidateFromChangingChildren.Target})");
            var inheritedLongPress=new Mapping{Input="F6",Kind=ActionKind.None,LongPressKind=ActionKind.Shortcut,LongPressValue="Ctrl+Win+Right"};var editorMapping=MainWindow.SelectEditorMapping([],inheritedLongPress,"F6");Check(editorMapping.LongPressKind==ActionKind.Shortcut&&editorMapping.LongPressValue=="Ctrl+Win+Right"&&!ReferenceEquals(editorMapping,inheritedLongPress),"inherited long-press mapping is visible in the editor without mutating its source");
            var baseMapping=new Mapping{Input="CapsLock+U",Kind=ActionKind.Key,Value="Enter"};var overrideMapping=new Mapping{Input="A",Kind=ActionKind.Key,Value="B"};var independentProfiles=new[]{new Profile{Name="標準",Mappings=[baseMapping]},new Profile{Name="Chrome",Mappings=[overrideMapping]}};Check(MainWindow.FindProfileMapping(independentProfiles,"Chrome","CapsLock+U",MainWindow.MappingInterceptsInput)==null&&ReferenceEquals(MainWindow.FindProfileMapping(independentProfiles,"Chrome","A",MainWindow.MappingInterceptsInput),overrideMapping)&&ReferenceEquals(MainWindow.FindProfileMapping(independentProfiles,"標準","CapsLock+U",MainWindow.MappingInterceptsInput),baseMapping),"profiles are independent so no-copy creation and assignment deletion never reveal standard-profile mappings");
            Check(!ConditionMatcher.Matches("notepad.exe","excel"),"application condition rejection");
            Check(ConditionMatcher.IsTaskbarClass("Shell_TrayWnd")&&ConditionMatcher.IsTaskbarClass("Shell_SecondaryTrayWnd"),"taskbar class detection");
            Check(ActionCatalog.Items.Any(x=>x.Name=="コピー"&&x.Value=="Ctrl+C"),"action catalog copy preset");
            var windowsApps=ActionCatalog.Items.Where(x=>x.MajorCategory=="Windowsアプリ").ToList();var windowsAppCategories=ActionPickerWindow.CategoriesForMajor(ActionCatalog.Items,"Windowsアプリ");Check(new[]{"設定","コントロールパネル","ディスクの管理","タスクマネージャー","デバイスマネージャー"}.All(name=>windowsApps.Any(x=>x.Name==name))&&windowsAppCategories.FirstOrDefault()==ActionPickerWindow.AllCategories&&ActionPickerWindow.ActionsForCategory(ActionCatalog.Items,"Windowsアプリ",ActionPickerWindow.AllCategories).Count==windowsApps.Count,"Windows applications are comprehensive and every major category begins with an all-actions view");
            Check(ActionCatalog.Items.Select(x=>x.MajorCategory).Distinct().Count()>=8&&ActionCatalog.Search("キャッシュ").Any(x=>x.Name=="キャッシュを無視して更新"),"action catalog has major categories and searchable content");
            Check(new[]{"ImeOn","ImeOff","ImeToggle"}.All(value=>ActionCatalog.Items.Any(x=>x.Category=="IME・日本語入力"&&x.Value==value))&&InputEngine.TryGetImeAction("ImeOn",out int imeOn)&&imeOn==1&&InputEngine.TryGetImeAction("ImeOff",out int imeOff)&&imeOff==0&&InputEngine.TryGetImeAction("ImeToggle",out int imeToggle)&&imeToggle==2,"IME on, off and toggle actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="仮想デスクトップ"),"action catalog virtual desktop category");
            Check(Enumerable.Range(1,8).All(n=>ActionCatalog.Items.Any(x=>x.Value=="Desktop"+n)),"direct desktop actions 1 through 8");
            Check(ActionCatalog.Items.Any(x=>x.Name.StartsWith("ズームイン")&&x.Value=="Ctrl+Add")&&ActionCatalog.Items.Any(x=>x.Name.StartsWith("ズームアウト")&&x.Value=="Ctrl+Subtract"),"action catalog zoom presets");
            Check(ActionCatalog.Items.Any(x=>x.Category=="マウス・ホイール"&&x.Name=="Shift+左クリック"&&x.Kind==ActionKind.Mouse&&x.Value=="ShiftDrag")&&ActionCatalog.Items.Any(x=>x.Category=="マウス・ホイール"&&x.Name=="Ctrl+左クリック"&&x.Kind==ActionKind.Mouse&&x.Value=="CtrlDrag")&&ActionCatalog.Items.Any(x=>x.Category=="マウス・ホイール"&&x.Name=="Alt+左クリック"&&x.Kind==ActionKind.Mouse&&x.Value=="AltDrag"),"Shift, Ctrl, and Alt click actions keep drag-capable behavior under clearer names");
            Check(ActionCatalog.Items.Any(x=>x.Category=="ブラウザー・タブ操作"&&x.Name=="右のタブへ移動"&&x.Value=="Ctrl+Tab")&&ActionCatalog.Items.Any(x=>x.Category=="ブラウザー・ページ操作"&&x.Name=="キャッシュを無視して更新"&&x.Value=="Ctrl+Shift+R"),"browser navigation and hard refresh actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="エクスプローラー・移動"&&x.Name=="上の階層へ"&&x.Value=="Alt+Up")&&ActionCatalog.Items.Any(x=>x.Category=="エクスプローラー・タブ"&&x.Name=="タブを閉じる"&&x.Value=="Ctrl+W"),"file explorer navigation and tab actions");
            Check(ActionCatalog.Items.Any(x=>x.Category=="音量・メディア"&&x.Value=="VolumeMute")&&ActionCatalog.Items.Any(x=>x.Category=="入力・アクセシビリティ"&&x.Value=="Win+."),"media and accessibility actions");
            Check(ActionCatalog.Items.Any(x=>x.Value=="MoveWindowDesktopRight"),"move active window to right desktop action");
            Check(InputEngine.TryGetDirectDesktopStep("Ctrl+Win+Left",out int leftStep)&&leftStep==-1&&InputEngine.TryGetDirectDesktopStep("Ctrl+Win+Right",out int rightStep)&&rightStep==1,"adjacent desktop actions use the direct API instead of injectable shortcuts");
            Check(new[]{"Left","Right","Up","Down"}.All(d=>ActionCatalog.Items.Any(x=>x.Value=="MoveWindowMonitor"+d)),"move active window to four monitor directions");
            Check(ActionCatalog.Items.Any(x=>x.Value=="SnapWindowLeft"&&x.Name.Contains("左半分"))&&ActionCatalog.Items.Any(x=>x.Value=="SnapWindowRight"&&x.Name.Contains("右半分")),"target-aware window snap actions are available for both halves");
            Check(ActionCatalog.Items.Any(x=>x.Value==OverlayService.DeckPanelAction&&x.Name.Contains("Deck"))&&InputEngine.IsRecognizedShortcut(OverlayService.DeckPanelAction),"Deck panel overlay is available as an assignable action");
            var deckConfig=new AppConfig();
            deckConfig.Profiles[0].Mappings.Add(new Mapping{Input=DeckPanelLayout.InputName(1),Layer=DeckPanelLayout.Layer,Kind=ActionKind.Shortcut,Value="Ctrl+C",Description="コピー"});
            var deckClone=service.Clone(deckConfig);
            Check(DeckPanelLayout.SlotCount==45&&DeckPanelLayout.InputName(45)=="Deck+45"&&DeckPanelLayout.FindMapping(deckClone,1) is {Value:"Ctrl+C",Description:"コピー"},"Deck panel keeps 45 stable profile-specific slots and editable names");
            Check(ActionCatalog.Items.Any(x=>x.Value=="ToggleMaximizeWindow"&&x.Name.Contains("元のサイズ")),"target-aware toggle maximize action");
            Check(ActionCatalog.Items.Any(x=>x.Category=="ウィンドウ・基本操作"&&x.Name=="最小化"&&x.Value=="MinimizeActiveWindow")&&ActionCatalog.Items.Any(x=>x.Category=="ウィンドウ・基本操作"&&x.Name=="ウィンドウを閉じる"&&x.Value=="CloseActiveWindow"),"target-aware minimize and close-window actions");
            InputEngine.ResetMinimizeAllToggleForTest();Check(InputEngine.ResolveShortcutAliasForTest("CloseActiveWindow")=="Alt+F4"&&InputEngine.ResolveShortcutAliasForTest("ToggleMinimizeAllWindows")=="Win+M"&&InputEngine.ResolveShortcutAliasForTest("ToggleMinimizeAllWindows")=="Shift+Win+M"&&ActionCatalog.Items.Any(x=>x.Value=="Win+M")&&ActionCatalog.Items.Any(x=>x.Value=="Shift+Win+M"),"close compatibility and minimize-all toggle actions");
            Check(InputEngine.ShortcutMatchesForTest("LeftAlt+F4","Alt","F4")&&InputEngine.ShortcutMatchesForTest("RightAlt+F4","Alt","F4")&&InputEngine.ShortcutMatchesForTest("LWin+Left","Win","Left"),"left and right modifier names match target-aware window shortcuts");
            Check(new[]{"画面キャプチャ","編集・クリップボード","ファイル・文書","文書の書式","ウィンドウ・整列","ブラウザー・タブ操作","エクスプローラー・ファイル操作"}.All(category=>ActionCatalog.Items.Any(x=>x.Category==category)),"common actions are divided into task-focused categories");
            var overlayActions=ActionCatalog.Items.Where(x=>x.MajorCategory=="オーバーレイ").ToArray();
            Check(overlayActions.Select(x=>x.Value).ToHashSet().SetEquals([OverlayService.NumpadAction,OverlayService.ExtendedKeypadAction,OverlayService.DeckPanelAction,OverlayService.BlankAction,OverlayService.ClockAction]),"overlay category exposes the keypad panels, Deck, blank screen, and clock");
            Check(!OverlayService.ShouldDismissFullScreenKeyboard(false,true)
                  &&!OverlayService.ShouldDismissFullScreenKeyboard(true,false)
                  &&OverlayService.ShouldDismissFullScreenKeyboard(true,true)
                  &&!OverlayService.ShouldDismissFullScreenMouse(false,0x201,false)
                  &&!OverlayService.ShouldDismissFullScreenMouse(true,0x202,false)
                  &&OverlayService.ShouldDismissFullScreenMouse(true,0x201,false)
                  &&OverlayService.ShouldDismissFullScreenMouse(true,0x200,true),
                "fullscreen overlays ignore their source release and close only on a fresh key, click, wheel, or movement");
            var shownOverlays=new List<string>();OverlayService.ActionRequestedForTest=shownOverlays.Add;InputEngine.SendShortcut(OverlayService.NumpadAction);InputEngine.SendShortcut(OverlayService.ExtendedKeypadAction);OverlayService.ActionRequestedForTest=null;
            Check(shownOverlays.SequenceEqual([OverlayService.NumpadAction,OverlayService.ExtendedKeypadAction]),"overlay actions dispatch without being parsed as keyboard shortcuts");
            Check(ActionCatalog.Items.Where(x=>x.Kind is ActionKind.Key or ActionKind.Shortcut).All(x=>InputEngine.IsRecognizedShortcut(x.Value)),"every catalog key and shortcut action is executable");
            Check(ActionCatalog.Items.GroupBy(x=>(x.Category,x.Name)).All(x=>x.Count()==1),"catalog has no duplicate action names within a category");
            var monitorAreas=new[]{new System.Drawing.Rectangle(0,0,1920,1080),new System.Drawing.Rectangle(1920,0,1920,1080),new System.Drawing.Rectangle(0,-1080,1920,1080),new System.Drawing.Rectangle(0,1080,1920,1080)};Check(WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Right)==1&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Up)==2&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Down)==3&&WindowMonitorService.SelectTargetIndex(monitorAreas,0,WindowMonitorService.Direction.Left)==-1,"monitor direction target selection");
            var shortcutCandidates=new[]
            {
                new WindowMonitorService.WindowCandidate((IntPtr)1,"Shell_TrayWnd",true),
                new WindowMonitorService.WindowCandidate((IntPtr)2,"Windows.UI.Core.CoreWindow",true),
                new WindowMonitorService.WindowCandidate((IntPtr)3,"XamlExplorerHostIslandWindow",true),
                new WindowMonitorService.WindowCandidate((IntPtr)4,"ApplicationFrameWindow",false),
                new WindowMonitorService.WindowCandidate((IntPtr)5,"Chrome_WidgetWin_1",true)
            };
            Check(WindowMonitorService.SelectShortcutTarget(shortcutCandidates)==(IntPtr)5,"macro shortcut skips taskbar, Windows 11 shell overlays, and hidden windows");
            Check(ForegroundWindowTracker.ShouldTrackWindow(shortcutCandidates[4],40,99)
                  &&!ForegroundWindowTracker.ShouldTrackWindow(shortcutCandidates[0],40,99)
                  &&!ForegroundWindowTracker.ShouldTrackWindow(shortcutCandidates[4],99,99),
                "foreground tracker remembers only visible non-shell windows owned by another process");
            Check(WindowMonitorService.SelectShortcutLaunchTarget(shortcutCandidates[4],(IntPtr)77,handle=>handle is (IntPtr)5 or (IntPtr)77)==(IntPtr)5
                  &&WindowMonitorService.SelectShortcutLaunchTarget(shortcutCandidates[0],(IntPtr)77,handle=>handle==(IntPtr)77)==(IntPtr)77,
                "taskbar shortcut launch prefers a live foreground window and falls back to the remembered window for shell focus");
            string persistedWindowPath=Path.Combine(dir,"last-foreground-window.txt");
            ForegroundWindowTracker.PersistWindow(persistedWindowPath,(IntPtr)4321);
            Check(ForegroundWindowTracker.ReadPersistedWindow(persistedWindowPath)==(IntPtr)4321,
                "taskbar macro target survives the elevation boundary through the persisted fallback");
            Check(WindowMonitorService.SelectRememberedShortcutTarget((IntPtr)4444,handle=>handle==(IntPtr)4444)==(IntPtr)4444
                  &&WindowMonitorService.SelectRememberedShortcutTarget((IntPtr)4444,_=>false)==IntPtr.Zero,
                "taskbar macro prefers a valid window remembered by the resident process and rejects stale handles");
            Check(WindowMonitorService.SelectShortcutPreparationTarget((IntPtr)4567,handle=>handle==(IntPtr)4567)==(IntPtr)4567
                  &&WindowMonitorService.SelectShortcutPreparationTarget((IntPtr)4567,_=>false)==IntPtr.Zero,
                "taskbar macro reactivates only its captured valid window before replaying raw shortcuts");
            var leftSecondary=WindowMonitorService.SnapBounds(new System.Drawing.Rectangle(-1920,40,1920,1040),WindowMonitorService.Direction.Left);
            var rightOddSecondary=WindowMonitorService.SnapBounds(new System.Drawing.Rectangle(1920,-200,1919,1080),WindowMonitorService.Direction.Right);
            Check(leftSecondary==new System.Drawing.Rectangle(-1920,40,960,1040)
                  &&rightOddSecondary==new System.Drawing.Rectangle(2879,-200,960,1080),
                "left and right snap bounds stay on negative, offset, and odd-width secondary monitors");
            string[] targeted=App.AttachMacroShortcutTarget(["--run-macro-id","macro-1"],()=>(IntPtr)4567);
            Check(App.ReadMacroShortcutTarget(targeted)==(IntPtr)4567&&targeted.Length==4,"macro shortcut target survives elevated argument encoding");
            Check(App.AttachMacroShortcutTarget(targeted,()=>throw new InvalidOperationException()).SequenceEqual(targeted),"macro shortcut target is captured only once");
            int cursorTargetCalls=0,activeTargetCalls=0;
            IntPtr preferredShortcutTarget=WindowMonitorService.SelectResolvedTarget(
                WindowActionTarget.WindowUnderCursor,
                (IntPtr)4567,
                handle=>handle==(IntPtr)4567,
                ()=>{cursorTargetCalls++;return (IntPtr)11;},
                ()=>{activeTargetCalls++;return (IntPtr)22;});
            Check(preferredShortcutTarget==(IntPtr)4567&&cursorTargetCalls==0&&activeTargetCalls==0,"taskbar macro keeps its captured window even when the saved target mode is window-under-cursor");
            IntPtr normalCursorTarget=WindowMonitorService.SelectResolvedTarget(
                WindowActionTarget.WindowUnderCursor,
                null,
                _=>false,
                ()=>{cursorTargetCalls++;return (IntPtr)11;},
                ()=>{activeTargetCalls++;return (IntPtr)22;});
            Check(normalCursorTarget==(IntPtr)11&&cursorTargetCalls==1&&activeTargetCalls==0,"normal actions without a taskbar shortcut target still use the window under the cursor");
            IntPtr cursorFallbackTarget=WindowMonitorService.SelectResolvedTarget(
                WindowActionTarget.WindowUnderCursor,
                (IntPtr)9999,
                _=>false,
                ()=>{cursorTargetCalls++;return (IntPtr)11;},
                ()=>{activeTargetCalls++;return (IntPtr)22;});
            Check(cursorFallbackTarget==(IntPtr)11&&cursorTargetCalls==2&&activeTargetCalls==0,"invalid captured taskbar target falls back to the saved target mode");
            var desktopA=Guid.NewGuid();var desktopB=Guid.NewGuid();var desktopBytes=desktopA.ToByteArray().Concat(desktopB.ToByteArray()).ToArray();var parsedDesktops=VirtualDesktopService.ParseDesktopIds(desktopBytes);Check(parsedDesktops.SequenceEqual(new[]{desktopA,desktopB}),"virtual desktop id parsing");
            Check(InputEngine.KeyName(0x31)=="1"&&InputEngine.KeyName(0x2C)=="PrintScreen","visual and physical key names match");
            Check(InputEngine.KeyName(0xF3)=="半角/全角"&&InputEngine.KeyName(0xE2)=="_","JIS key name normalization");
            Check(InputEngine.KeyName(0x0D)=="Enter"&&InputEngine.KeyName(0x1B)=="Esc"&&InputEngine.KeyName(0x61)=="NumPad1","special key names match visual keyboard");
            Check(InputEngine.IsValidRecordedEvent("A Down")&&InputEngine.IsValidRecordedEvent("MouseLeft Up")&&InputEngine.IsValidRecordedEvent("MouseMoveRelative:12,-4")&&!InputEngine.IsValidRecordedEvent("Unknown Down"),"macro event validation including relative mouse movement");
            Check(InputEngine.TryResolveShiftedSymbolForTest("?",false,out ushort jisQuestion)&&jisQuestion==0xBF&&InputEngine.TryResolveShiftedSymbolForTest("!",false,out ushort jisExclamation)&&jisExclamation==0x31&&InputEngine.TryResolveShiftedSymbolForTest("?",true,out ushort usQuestion)&&usQuestion==0xBF&&InputEngine.TryResolveShiftedSymbolForTest("!",true,out ushort usExclamation)&&usExclamation==0x31,"shifted question and exclamation key resolution");
            Check("!\"#$%&'()=~|`{+*}<>?".All(x=>InputEngine.TryResolveShiftedSymbolForTest(x.ToString(),false,out _))&&"~!@#$%^&*()_+{}|:\"<>?".All(x=>InputEngine.TryResolveShiftedSymbolForTest(x.ToString(),true,out _)),"JIS and US shifted symbol tables are complete");
            var stopShortcut=new MacroStopShortcut();bool premature=stopShortcut.Process("F12 Down");stopShortcut.Reset();stopShortcut.Process("LeftCtrl Down");stopShortcut.Process("LeftShift Down");bool macroStop=stopShortcut.Process("F12 Down");Check(!premature&&macroStop,"macro recording stop shortcut Ctrl+Shift+F12");
            Check(!MacroWindow.ShouldRecordEvent("A Down",false)&&!MacroWindow.ShouldRecordEvent("LeftCtrl Up",false)&&MacroWindow.ShouldRecordEvent("MouseLeft Down",false)&&MacroWindow.ShouldRecordEvent("WheelUp Down",false)&&MacroWindow.ShouldRecordEvent("MouseMove:10,20",false)&&MacroWindow.ShouldRecordEvent("A Down",true),"macro keyboard recording filter preserves mouse input");
            Check(MacroWindow.DropIndexAfterRemoval(1,3,4)==2&&MacroWindow.DropIndexAfterRemoval(3,1,4)==1&&MacroWindow.DropIndexAfterRemoval(1,2,4)==1,"macro drag insertion keeps before/after positions correct when the source row is removed");
            Check(MacroWindow.VisualKindFor(new MacroStep{Event="A Down"})==MacroStepVisualKind.Keyboard
                  &&MacroWindow.VisualKindFor(new MacroStep{Event="MouseLeft Down"})==MacroStepVisualKind.Mouse
                  &&MacroWindow.VisualKindFor(new MacroStep{Event="Wait"})==MacroStepVisualKind.Wait
                  &&MacroWindow.VisualKindFor(new MacroStep{Event="割り当て",RecordedActionKind=ActionKind.Shortcut})==MacroStepVisualKind.Action
                  &&MacroWindow.VisualKindFor(new MacroStep{Event="割り当て",RecordedActionKind=ActionKind.Macro})==MacroStepVisualKind.Macro
                  &&MacroWindow.VisualKindFor(new MacroStep{Event="割り当て",RecordedActionKind=ActionKind.Text})==MacroStepVisualKind.Text,
                  "macro steps expose stable visual kinds for keyboard, mouse, wait, action, macro and text rows");
            var macroCycleConfig=new AppConfig{Macros=[new MacroDefinition{Name="循環A",Steps=[new(){Event="割り当て: 循環B",RecordedActionKind=ActionKind.Macro,RecordedActionValue="循環B"}]},new MacroDefinition{Name="循環B",Steps=[new(){Event="割り当て: 循環A",RecordedActionKind=ActionKind.Macro,RecordedActionValue="循環A"}]}]};
            Check(ConfigValidator.Validate(macroCycleConfig).Any(x=>x.Contains("循環")),"recursive macro cycles are rejected before saving");
            bool unknownRejected=false;try{InputEngine.SendShortcut("DefinitelyUnknownKey");}catch(ArgumentException){unknownRejected=true;}Check(unknownRejected,"unknown shortcut key is rejected");
            Check(StartupService.BuildCommand(@"C:\Program Files\RELYR\RELYR.exe")=="\"C:\\Program Files\\RELYR\\RELYR.exe\" --tray","startup command quoting");
            string installedShutdown=App.BuildShutdownSignalName(@"C:\Program Files\RELYR\RELYR.exe");string developmentShutdown=App.BuildShutdownSignalName(@"C:\Dev\RELYR.exe");Check(installedShutdown==App.BuildShutdownSignalName(@"c:\program files\relyr\RELYR.EXE")&&installedShutdown!=developmentShutdown,"shutdown signal targets only the same executable path");
            var withoutPreset=service.Clone(loaded);withoutPreset.Profiles.RemoveAll(x=>x.Name=="既存AHK再現");service.Save(withoutPreset);Check(!service.Load().Profiles.Any(x=>x.Name=="既存AHK再現"),"deleted preset stays deleted");
        }
        catch(Exception ex){output.WriteLine("FAIL exception: "+ex);failures.Add("exception");}
        finally{try{Directory.Delete(dir,true);}catch{}}
        output.WriteLine(failures.Count==0?"SELF-TEST PASSED":"SELF-TEST FAILED: "+string.Join(", ",failures));
        return failures.Count==0?0:1;
    }
    static bool InputEngineSmokeTest(){using var engine=new InputEngine();engine.Enabled=false;return true;}
    static void TestMappingActions(Action<bool,string> check)
    {
        var fake=new FakeOutput();var executor=new MappingExecutor(fake);
        check(executor.Execute(new Mapping{Kind=ActionKind.Disabled},"A",out _)&&fake.Calls.Count==0,"disabled mapping");
        executor.Execute(new Mapping{Kind=ActionKind.Key,Value="Esc"},"A",out _);check(fake.Calls.Last()=="shortcut:Esc","key replacement action");
        executor.Execute(new Mapping{Kind=ActionKind.Shortcut,Value="Ctrl+C"},"A",out _);check(fake.Calls.Last()=="shortcut:Ctrl+C","shortcut action");
        executor.Execute(new Mapping{Kind=ActionKind.Text,Value="日本語"},"A",out _);check(fake.Calls.Last()=="text:日本語","Unicode text action");
        executor.Execute(new Mapping{Kind=ActionKind.Mouse,Value="WheelUp"},"A",out _);check(fake.Calls.Last()=="mouse:WheelUp","mouse and wheel action");
        var modifierDrag=new Mapping{Kind=ActionKind.Mouse,Value="ShiftDrag"};executor.Execute(modifierDrag,"Space+MouseLeft",out _);check(fake.Calls.Last()=="mouse:ShiftDrag","modifier drag mapping sends a modified single click when not dragged");executor.Execute(modifierDrag,"Space+MouseLeft:PressStart",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:Start","modifier drag presses the modifier and left button immediately");executor.Execute(modifierDrag,"Space+MouseLeft:PressEnd",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:End","modifier drag releases the left button and modifier at physical release");executor.Execute(modifierDrag,"Space+MouseLeft:DragStart",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:Start","legacy drag start remains compatible");executor.Execute(modifierDrag,"Space+MouseLeft:DragEnd",out _);check(fake.Calls.Last()=="mouse:ShiftDrag:End","legacy drag end remains compatible");modifierDrag.Value="AltDrag";executor.Execute(modifierDrag,"Space+MouseLeft:PressStart",out _);check(fake.Calls.Last()=="mouse:AltDrag:Start","Alt drag uses the same safe press lifecycle");executor.Execute(modifierDrag,"Space+MouseLeft:PressEnd",out _);check(fake.Calls.Last()=="mouse:AltDrag:End","Alt drag uses the same safe release lifecycle");
        executor.Execute(new Mapping{Kind=ActionKind.Launch,Value="sample.exe"},"A",out _);check(fake.Calls.Last()=="launch:sample.exe","application launch action");
        executor.Execute(new Mapping{Kind=ActionKind.Macro,Value="作業マクロ"},"A",out _);check(fake.Calls.Last()=="macro:作業マクロ","macro action");
        executor.Execute(new Mapping{Kind=ActionKind.Profile,Value="ゲーム"},"A",out _);check(fake.Calls.Last()=="profile:ゲーム","profile switch action");
        check(MappingExecutor.TryGetRecordedAction(new Mapping{Input="Space+Up",Layer="Space",Kind=ActionKind.Shortcut,Value="Win+Left"},"Space+Up",out var recordedKind,out string recordedValue)&&recordedKind==ActionKind.Shortcut&&recordedValue=="Win+Left","macro recording resolves the assigned action instead of the physical layer keys");
        executor.Execute(new Mapping{Kind=ActionKind.Shortcut,Value="A",LongPressKind=ActionKind.Shortcut,LongPressValue="B"},"A:Long",out _);check(fake.Calls.Last()=="shortcut:B","long press action selection");
        fake.Calls.Clear();executor.Execute(new Mapping{Input="Space+G",Kind=ActionKind.Shortcut,Value="Ctrl+V",LongPressKind=ActionKind.Shortcut,LongPressValue="LWin+V"},"Space+G:Long",out _);check(fake.Calls.SequenceEqual(new[]{"neutralize:Space+G","shortcut:LWin+V"}),"long press neutralizes its physical source before sending a Windows shortcut");
        executor.Execute(new Mapping{Kind=ActionKind.Key,Value="B",LongPressKind=ActionKind.Launch,LongPressValue="sample.exe"},"A:Long",out _);check(fake.Calls.Last()=="launch:sample.exe","independent long press action kind");
        var longKindOnly=new Mapping{Input="Q",Layer="通常",Kind=ActionKind.None,LongPressKind=ActionKind.Launch,LongPressValue="sample.exe"};executor.Execute(longKindOnly,"Q",out _);check(fake.Calls.Last()=="shortcut:Q","long-kind-only mapping preserves tap");executor.Execute(longKindOnly,"Q:Long",out _);check(fake.Calls.Last()=="launch:sample.exe","long-kind-only mapping executes hold action");
        var longOnly=new Mapping{Input="K",Layer="通常",Kind=ActionKind.Shortcut,Value="",LongPressKind=ActionKind.Shortcut,LongPressValue="Ctrl+K"};executor.Execute(longOnly,"K",out _);check(fake.Calls.Last()=="shortcut:K","long-only mapping preserves normal tap");executor.Execute(longOnly,"K:Long",out _);check(fake.Calls.Last()=="shortcut:Ctrl+K","long-only mapping executes hold action");
        check(!MainWindow.HasConfiguredLongPress(new Mapping{Kind=ActionKind.Key,Value="Enter",LongPressKind=ActionKind.None,LongPressValue="q"})&&MainWindow.HasConfiguredLongPress(new Mapping{LongPressKind=ActionKind.Key,LongPressValue="q"}),"disabled stale long-press values never block normal key repeat");
    }
    sealed class FakeOutput:IInputOutput
    {
        public List<string> Calls{get;}=[];
        public void NeutralizeSourceKey(string input)=>Calls.Add("neutralize:"+input);public void SendShortcut(string value)=>Calls.Add("shortcut:"+value);public void SendText(string value)=>Calls.Add("text:"+value);public void SendMouse(string value)=>Calls.Add("mouse:"+value);public void Launch(string value)=>Calls.Add("launch:"+value);public void RunMacro(string name)=>Calls.Add("macro:"+name);public void SwitchProfile(string name)=>Calls.Add("profile:"+name);
    }
}
